package assets

import "strings"

// Symbol 은 특수문자 drawer 에서 고를 수 있는 글자 하나다.
//
// 표(CuratedSymbols) 와 같은 자리에 둔다. 유니코드를 훑어 얻은 글자도 이 모양으로 담기지만
// (core/symbol.go 의 indexSymbols) 담기는 것이 이름과 글자뿐이라 여기가 그 정의의 집이다.
type Symbol struct {
	// Char 는 넣을 글자다. grapheme cluster 하나이고 여러 rune 일 수 있다(ZWJ 이모지).
	Char string

	// Name 은 격자 아래 한 줄에 보이는 이름이다. 큐레이션한 것은 한국어이고
	// 훑어서 얻은 것은 유니코드 영문 이름이다.
	Name string

	// Keywords 는 이름 말고도 걸릴 말이다. 공백으로 잇는다 — `▲` 는 이름이
	// 「검은 위쪽 삼각형」이지만 `세모` 로도 찾을 수 있어야 한다.
	Keywords string

	// Aliases 는 `:+1:` 처럼 편집 화면에서 곧바로 쳐서 넣는 이름이다. 공백으로 잇는다.
	//
	// **Keywords 와 다른 몫이다.** 저쪽은 특수문자 판에서 눈으로 찾을 때 걸리는 말이라
	// 한국어와 뜻이 넓은 말이 들어가는데, 여기는 치는 이름이라 ASCII 소문자와 `+ - _`
	// 뿐이고(`:` 뒤에 칠 수 있는 글자다) 뜻이 하나로 좁아야 한다.
	//
	// github 표기를 따른다. 손으로 적은 것만 있고 훑어서 얻은 글자에는 없다 (ADR-0135).
	Aliases string
}

// AliasList 는 이 글자에 붙은 별칭들이다. 없으면 빈 조각이다.
func (s Symbol) AliasList() []string {
	return strings.Fields(s.Aliases)
}

// Label 은 매칭이 보는 글자다. 보이는 순서와 같아야 맞은 자리를 그대로 강조에 쓸 수 있다
// (core 의 paletteCommand.label 과 같은 규칙이다).
//
// 규칙이 아니라 적어 둔 글에서 곧바로 나오는 것이라 표와 같이 둔다.
func (s Symbol) Label() string {
	return strings.TrimRight(s.Name+" "+s.Keywords, " ")
}

// 특수문자 drawer 가 먼저 보여주는 글자 표다. 한국어 이름으로 찾을 수 있는 것이 여기까지다
// (ADR-0056).
//
// 유니코드 공식 이름은 영문뿐이라(`BLACK UP-POINTING TRIANGLE`) `삼각형` 으로는 걸리지
// 않는다. 그래서 자주 쓰는 것만 손으로 적는다. 여기 없는 글자도 목록에는 있지만 영문
// 이름으로만 찾을 수 있다(core/symbol.go 의 indexSymbols).
//
// **새 글자는 이 표에 한 줄이 는다.** 팔레트 명령 표(core/palette.go 의 paletteCommands) 와
// 같은 방식인데 그쪽은 실행할 함수를 들고 있어서 core 에 남는다 — 여기 든 것은 글뿐이다.
// 갈래는 눈으로 찾기 위한 주석일 뿐이고 코드가 읽지 않는다 — 걸러내는 것은 이름과 keywords 다.
//
// 보이지 않는 글자(`NO-BREAK SPACE`·`ZERO WIDTH SPACE`) 는 넣지 않았다. 격자에서 빈 칸으로
// 보여 서로 구별되지 않는다. 영문 이름으로는 그대로 찾을 수 있다.
var CuratedSymbols = []Symbol{
	// 화살표 (arrow)
	{Char: "←", Name: "왼쪽 화살표", Keywords: "화살표 arrow left"},
	{Char: "→", Name: "오른쪽 화살표", Keywords: "화살표 arrow right"},
	{Char: "↑", Name: "위쪽 화살표", Keywords: "화살표 arrow up"},
	{Char: "↓", Name: "아래쪽 화살표", Keywords: "화살표 arrow down"},
	{Char: "↔", Name: "좌우 화살표", Keywords: "화살표 arrow left right"},
	{Char: "↕", Name: "위아래 화살표", Keywords: "화살표 arrow up down"},
	{Char: "↖", Name: "왼쪽 위 화살표", Keywords: "화살표 arrow upper left"},
	{Char: "↗", Name: "오른쪽 위 화살표", Keywords: "화살표 arrow upper right"},
	{Char: "↘", Name: "오른쪽 아래 화살표", Keywords: "화살표 arrow lower right"},
	{Char: "↙", Name: "왼쪽 아래 화살표", Keywords: "화살표 arrow lower left"},
	{Char: "↚", Name: "왼쪽 화살표 부정", Keywords: "화살표 arrow left not"},
	{Char: "↛", Name: "오른쪽 화살표 부정", Keywords: "화살표 arrow right not"},
	{Char: "↝", Name: "물결 오른쪽 화살표", Keywords: "화살표 물결 arrow squiggle right"},
	{Char: "↞", Name: "왼쪽 두겹 머리 화살표", Keywords: "화살표 arrow left two head"},
	{Char: "↠", Name: "오른쪽 두겹 머리 화살표", Keywords: "화살표 arrow right two head"},
	{Char: "↢", Name: "왼쪽 꼬리 화살표", Keywords: "화살표 arrow left tail"},
	{Char: "↣", Name: "오른쪽 꼬리 화살표", Keywords: "화살표 arrow right tail"},
	{Char: "↦", Name: "오른쪽 막대 화살표", Keywords: "화살표 arrow maps to"},
	{Char: "↩", Name: "왼쪽 갈고리 화살표", Keywords: "화살표 arrow hook left"},
	{Char: "↪", Name: "오른쪽 갈고리 화살표", Keywords: "화살표 arrow hook right"},
	{Char: "↰", Name: "위에서 왼쪽 화살표", Keywords: "화살표 arrow up left"},
	{Char: "↱", Name: "위에서 오른쪽 화살표", Keywords: "화살표 arrow up right"},
	{Char: "↲", Name: "아래에서 왼쪽 화살표", Keywords: "화살표 arrow down left"},
	{Char: "↳", Name: "아래에서 오른쪽 화살표", Keywords: "화살표 arrow down right"},
	{Char: "↵", Name: "줄바꿈 화살표", Keywords: "화살표 엔터 arrow return enter newline"},
	{Char: "↶", Name: "반시계 반원 화살표", Keywords: "화살표 되돌리기 arrow undo anticlockwise"},
	{Char: "↷", Name: "시계 반원 화살표", Keywords: "화살표 다시하기 arrow redo clockwise"},
	{Char: "↺", Name: "반시계 열린 원 화살표", Keywords: "화살표 회전 arrow rotate anticlockwise"},
	{Char: "↻", Name: "시계 열린 원 화살표", Keywords: "화살표 회전 arrow rotate clockwise"},
	{Char: "↼", Name: "왼쪽 위 갈래 화살표", Keywords: "화살표 arrow harpoon left up"},
	{Char: "⇀", Name: "오른쪽 위 갈래 화살표", Keywords: "화살표 arrow harpoon right up"},
	{Char: "⇄", Name: "오른쪽 왼쪽 화살표", Keywords: "화살표 교환 arrow swap right left"},
	{Char: "⇅", Name: "위아래 나란한 화살표", Keywords: "화살표 arrow up down pair"},
	{Char: "⇆", Name: "왼쪽 오른쪽 화살표", Keywords: "화살표 교환 arrow swap left right"},
	{Char: "⇇", Name: "왼쪽 겹 화살표", Keywords: "화살표 arrow left pair"},
	{Char: "⇉", Name: "오른쪽 겹 화살표", Keywords: "화살표 arrow right pair"},
	{Char: "⇐", Name: "왼쪽 두 줄 화살표", Keywords: "화살표 arrow double left"},
	{Char: "⇑", Name: "위쪽 두 줄 화살표", Keywords: "화살표 arrow double up"},
	{Char: "⇒", Name: "오른쪽 두 줄 화살표", Keywords: "화살표 함의 arrow double right implies"},
	{Char: "⇓", Name: "아래쪽 두 줄 화살표", Keywords: "화살표 arrow double down"},
	{Char: "⇔", Name: "좌우 두 줄 화살표", Keywords: "화살표 동치 arrow double left right iff"},
	{Char: "⇕", Name: "위아래 두 줄 화살표", Keywords: "화살표 arrow double up down"},
	{Char: "⇠", Name: "왼쪽 점선 화살표", Keywords: "화살표 점선 arrow dashed left"},
	{Char: "⇡", Name: "위쪽 점선 화살표", Keywords: "화살표 점선 arrow dashed up"},
	{Char: "⇢", Name: "오른쪽 점선 화살표", Keywords: "화살표 점선 arrow dashed right"},
	{Char: "⇣", Name: "아래쪽 점선 화살표", Keywords: "화살표 점선 arrow dashed down"},
	{Char: "⇦", Name: "왼쪽 흰 화살표", Keywords: "화살표 arrow white left"},
	{Char: "⇧", Name: "위쪽 흰 화살표", Keywords: "화살표 시프트 arrow white up shift"},
	{Char: "⇨", Name: "오른쪽 흰 화살표", Keywords: "화살표 arrow white right"},
	{Char: "⇩", Name: "아래쪽 흰 화살표", Keywords: "화살표 arrow white down"},
	{Char: "⇥", Name: "오른쪽 막대 화살표 탭", Keywords: "화살표 탭 arrow tab right"},
	{Char: "⇤", Name: "왼쪽 막대 화살표 탭", Keywords: "화살표 탭 arrow tab left"},
	{Char: "⌁", Name: "되돌림", Keywords: "arrow delete escape"},
	{Char: "⌃", Name: "위 꺾쇠 컨트롤", Keywords: "컨트롤 control caret up"},
	{Char: "⌄", Name: "아래 꺾쇠", Keywords: "caret down"},
	{Char: "⌘", Name: "커맨드 키", Keywords: "맥 명령 command mac cloverleaf"},
	{Char: "⌥", Name: "옵션 키", Keywords: "맥 알트 option alt mac"},
	{Char: "⎋", Name: "이스케이프 키", Keywords: "이스케이프 escape esc"},
	{Char: "⏎", Name: "리턴 키", Keywords: "엔터 리턴 return enter"},
	{Char: "⏏", Name: "꺼내기", Keywords: "이젝트 eject"},
	{Char: "⌫", Name: "지우기 왼쪽", Keywords: "백스페이스 backspace delete"},
	{Char: "⌦", Name: "지우기 오른쪽", Keywords: "딜리트 delete forward"},
	{Char: "➔", Name: "굵은 오른쪽 화살표", Keywords: "화살표 arrow heavy right"},
	{Char: "➜", Name: "굵은 둥근 오른쪽 화살표", Keywords: "화살표 arrow heavy round right"},
	{Char: "➡", Name: "오른쪽 화살표 그림", Keywords: "화살표 arrow right black"},
	{Char: "⬅", Name: "왼쪽 화살표 그림", Keywords: "화살표 arrow left black"},
	{Char: "⬆", Name: "위쪽 화살표 그림", Keywords: "화살표 arrow up black"},
	{Char: "⬇", Name: "아래쪽 화살표 그림", Keywords: "화살표 arrow down black"},
	{Char: "⤴", Name: "위로 굽은 화살표", Keywords: "화살표 arrow curve up"},
	{Char: "⤵", Name: "아래로 굽은 화살표", Keywords: "화살표 arrow curve down"},
	{Char: "⟵", Name: "긴 왼쪽 화살표", Keywords: "화살표 arrow long left"},
	{Char: "⟶", Name: "긴 오른쪽 화살표", Keywords: "화살표 arrow long right"},
	{Char: "⟷", Name: "긴 좌우 화살표", Keywords: "화살표 arrow long left right"},
	{Char: "⟸", Name: "긴 왼쪽 두 줄 화살표", Keywords: "화살표 arrow long double left"},
	{Char: "⟹", Name: "긴 오른쪽 두 줄 화살표", Keywords: "화살표 arrow long double right"},
	{Char: "⟺", Name: "긴 좌우 두 줄 화살표", Keywords: "화살표 arrow long double left right"},
	{Char: "↯", Name: "번개 화살표", Keywords: "화살표 번개 arrow lightning"},
	{Char: "⇋", Name: "평형 화살표", Keywords: "화살표 평형 arrow equilibrium"},
	{Char: "⇌", Name: "평형 화살표 반대", Keywords: "화살표 평형 arrow equilibrium"},

	// 도형 (shape)
	{Char: "▲", Name: "검은 위쪽 삼각형", Keywords: "삼각형 세모 triangle up black"},
	{Char: "△", Name: "흰 위쪽 삼각형", Keywords: "삼각형 세모 triangle up white"},
	{Char: "▼", Name: "검은 아래쪽 삼각형", Keywords: "삼각형 세모 triangle down black"},
	{Char: "▽", Name: "흰 아래쪽 삼각형", Keywords: "삼각형 세모 triangle down white"},
	{Char: "◀", Name: "검은 왼쪽 삼각형", Keywords: "삼각형 세모 triangle left black"},
	{Char: "◁", Name: "흰 왼쪽 삼각형", Keywords: "삼각형 세모 triangle left white"},
	{Char: "▶", Name: "검은 오른쪽 삼각형", Keywords: "삼각형 세모 triangle right black"},
	{Char: "▷", Name: "흰 오른쪽 삼각형", Keywords: "삼각형 세모 triangle right white"},
	{Char: "▴", Name: "검은 작은 위쪽 삼각형", Keywords: "삼각형 세모 triangle up small black"},
	{Char: "▵", Name: "흰 작은 위쪽 삼각형", Keywords: "삼각형 세모 triangle up small white"},
	{Char: "▾", Name: "검은 작은 아래쪽 삼각형", Keywords: "삼각형 세모 triangle down small black"},
	{Char: "▿", Name: "흰 작은 아래쪽 삼각형", Keywords: "삼각형 세모 triangle down small white"},
	{Char: "◂", Name: "검은 작은 왼쪽 삼각형", Keywords: "삼각형 세모 triangle left small black"},
	{Char: "◃", Name: "흰 작은 왼쪽 삼각형", Keywords: "삼각형 세모 triangle left small white"},
	{Char: "▸", Name: "검은 작은 오른쪽 삼각형", Keywords: "삼각형 세모 triangle right small black"},
	{Char: "▹", Name: "흰 작은 오른쪽 삼각형", Keywords: "삼각형 세모 triangle right small white"},
	{Char: "◤", Name: "검은 왼쪽 위 삼각형", Keywords: "삼각형 세모 triangle upper left"},
	{Char: "◥", Name: "검은 오른쪽 위 삼각형", Keywords: "삼각형 세모 triangle upper right"},
	{Char: "◣", Name: "검은 왼쪽 아래 삼각형", Keywords: "삼각형 세모 triangle lower left"},
	{Char: "◢", Name: "검은 오른쪽 아래 삼각형", Keywords: "삼각형 세모 triangle lower right"},
	{Char: "⊿", Name: "직각 삼각형", Keywords: "삼각형 세모 triangle right angle"},
	{Char: "■", Name: "검은 사각형", Keywords: "네모 사각형 square black"},
	{Char: "□", Name: "흰 사각형", Keywords: "네모 사각형 square white"},
	{Char: "▪", Name: "검은 작은 사각형", Keywords: "네모 사각형 square small black"},
	{Char: "▫", Name: "흰 작은 사각형", Keywords: "네모 사각형 square small white"},
	{Char: "▬", Name: "검은 가로 막대", Keywords: "네모 막대 rectangle black"},
	{Char: "▭", Name: "흰 가로 막대", Keywords: "네모 막대 rectangle white"},
	{Char: "▮", Name: "검은 세로 막대", Keywords: "네모 막대 rectangle vertical black"},
	{Char: "▯", Name: "흰 세로 막대", Keywords: "네모 막대 rectangle vertical white"},
	{Char: "◆", Name: "검은 마름모", Keywords: "마름모 다이아 diamond black"},
	{Char: "◇", Name: "흰 마름모", Keywords: "마름모 다이아 diamond white"},
	{Char: "◈", Name: "마름모 속 마름모", Keywords: "마름모 다이아 diamond in diamond"},
	{Char: "◊", Name: "마름모꼴", Keywords: "마름모 다이아 lozenge"},
	{Char: "●", Name: "검은 원", Keywords: "동그라미 원 circle black"},
	{Char: "○", Name: "흰 원", Keywords: "동그라미 원 circle white"},
	{Char: "◎", Name: "겹동그라미", Keywords: "동그라미 원 circle bullseye"},
	{Char: "◉", Name: "가운데 찬 동그라미", Keywords: "동그라미 원 circle fisheye"},
	{Char: "◌", Name: "점선 동그라미", Keywords: "동그라미 원 circle dotted"},
	{Char: "◯", Name: "큰 원", Keywords: "동그라미 원 circle large"},
	{Char: "⬤", Name: "큰 검은 원", Keywords: "동그라미 원 circle large black"},
	{Char: "◐", Name: "왼쪽 반 검은 원", Keywords: "동그라미 반원 circle half left"},
	{Char: "◑", Name: "오른쪽 반 검은 원", Keywords: "동그라미 반원 circle half right"},
	{Char: "◒", Name: "아래 반 검은 원", Keywords: "동그라미 반원 circle half bottom"},
	{Char: "◓", Name: "위 반 검은 원", Keywords: "동그라미 반원 circle half top"},
	{Char: "⬛", Name: "큰 검은 정사각형", Keywords: "네모 사각형 square large black"},
	{Char: "⬜", Name: "큰 흰 정사각형", Keywords: "네모 사각형 square large white"},
	{Char: "⯀", Name: "검은 중간 사각형", Keywords: "네모 사각형 square medium black"},
	{Char: "★", Name: "검은 별", Keywords: "별 star black"},
	{Char: "☆", Name: "흰 별", Keywords: "별 star white"},
	{Char: "✦", Name: "네 꼭짓점 검은 별", Keywords: "별 star four point"},
	{Char: "✧", Name: "네 꼭짓점 흰 별", Keywords: "별 star four point white"},
	{Char: "✩", Name: "얇은 흰 별", Keywords: "별 star outline"},
	{Char: "✪", Name: "동그라미 속 별", Keywords: "별 star circled"},
	{Char: "✫", Name: "가운데 뚫린 별", Keywords: "별 star open centre"},
	{Char: "✮", Name: "가운데 찬 별", Keywords: "별 star centre"},
	{Char: "✯", Name: "회전한 별", Keywords: "별 star pinwheel"},
	{Char: "❂", Name: "동그라미 속 여덟살 별", Keywords: "별 star circled eight"},
	{Char: "✱", Name: "굵은 별표", Keywords: "별표 asterisk heavy"},
	{Char: "✲", Name: "열린 별표", Keywords: "별표 asterisk open"},
	{Char: "❉", Name: "여섯살 별표", Keywords: "별표 asterisk six"},
	{Char: "❋", Name: "여덟살 별표", Keywords: "별표 asterisk eight"},
	{Char: "⬟", Name: "검은 오각형", Keywords: "오각형 pentagon black"},
	{Char: "⬠", Name: "흰 오각형", Keywords: "오각형 pentagon white"},
	{Char: "⬢", Name: "검은 육각형", Keywords: "육각형 hexagon black"},
	{Char: "⬣", Name: "흰 육각형", Keywords: "육각형 hexagon white"},
	{Char: "⯃", Name: "검은 팔각형", Keywords: "팔각형 octagon black"},
	{Char: "▰", Name: "검은 기울인 사각형", Keywords: "네모 사각형 parallelogram black"},
	{Char: "▱", Name: "흰 기울인 사각형", Keywords: "네모 사각형 parallelogram white"},
	{Char: "◫", Name: "세로로 나뉜 사각형", Keywords: "네모 사각형 square divided"},
	{Char: "◪", Name: "반쯤 찬 사각형", Keywords: "네모 사각형 square half filled"},
	{Char: "▩", Name: "빗금친 사각형", Keywords: "네모 사각형 square crosshatch"},
	{Char: "▨", Name: "빗금 사각형", Keywords: "네모 사각형 square diagonal hatch"},
	{Char: "▤", Name: "가로줄 사각형", Keywords: "네모 사각형 square horizontal fill"},
	{Char: "▥", Name: "세로줄 사각형", Keywords: "네모 사각형 square vertical fill"},
	{Char: "▦", Name: "격자 사각형", Keywords: "네모 사각형 square grid fill"},
	{Char: "░", Name: "옅은 음영", Keywords: "음영 블록 shade light"},
	{Char: "▒", Name: "중간 음영", Keywords: "음영 블록 shade medium"},
	{Char: "▓", Name: "짙은 음영", Keywords: "음영 블록 shade dark"},
	{Char: "█", Name: "꽉 찬 블록", Keywords: "블록 block full"},
	{Char: "▄", Name: "아래 반 블록", Keywords: "블록 block lower half"},
	{Char: "▀", Name: "위 반 블록", Keywords: "블록 block upper half"},
	{Char: "▌", Name: "왼쪽 반 블록", Keywords: "블록 block left half"},
	{Char: "▐", Name: "오른쪽 반 블록", Keywords: "블록 block right half"},
	{Char: "▁", Name: "아래 여덟분의 일 블록", Keywords: "블록 그래프 block eighth"},
	{Char: "▂", Name: "아래 사분의 일 블록", Keywords: "블록 그래프 block quarter"},
	{Char: "▃", Name: "아래 팔분의 삼 블록", Keywords: "블록 그래프 block"},
	{Char: "▅", Name: "아래 팔분의 오 블록", Keywords: "블록 그래프 block"},
	{Char: "▆", Name: "아래 사분의 삼 블록", Keywords: "블록 그래프 block"},
	{Char: "▇", Name: "아래 팔분의 칠 블록", Keywords: "블록 그래프 block"},

	// 수학 (math)
	{Char: "±", Name: "플러스 마이너스", Keywords: "더하기 빼기 plus minus"},
	{Char: "∓", Name: "마이너스 플러스", Keywords: "빼기 더하기 minus plus"},
	{Char: "×", Name: "곱하기", Keywords: "곱셈 multiply times"},
	{Char: "÷", Name: "나누기", Keywords: "나눗셈 divide"},
	{Char: "∕", Name: "나눗셈 사선", Keywords: "나눗셈 division slash"},
	{Char: "∗", Name: "별표 연산", Keywords: "곱 asterisk operator"},
	{Char: "∘", Name: "합성", Keywords: "고리 ring composition"},
	{Char: "∙", Name: "가운뎃점 연산", Keywords: "점 bullet operator"},
	{Char: "⋅", Name: "점 곱", Keywords: "점 dot product"},
	{Char: "≠", Name: "같지 않음", Keywords: "부등호 not equal"},
	{Char: "≈", Name: "거의 같음", Keywords: "근사 approximately equal"},
	{Char: "≅", Name: "합동", Keywords: "근사 congruent"},
	{Char: "≡", Name: "항등", Keywords: "합동 identical equivalent"},
	{Char: "≢", Name: "항등 아님", Keywords: "not identical"},
	{Char: "≒", Name: "근사 등호", Keywords: "근사 approximately equal"},
	{Char: "≤", Name: "작거나 같음", Keywords: "부등호 less than or equal"},
	{Char: "≥", Name: "크거나 같음", Keywords: "부등호 greater than or equal"},
	{Char: "≪", Name: "훨씬 작음", Keywords: "부등호 much less than"},
	{Char: "≫", Name: "훨씬 큼", Keywords: "부등호 much greater than"},
	{Char: "∞", Name: "무한대", Keywords: "무한 infinity"},
	{Char: "∝", Name: "비례", Keywords: "proportional to"},
	{Char: "∂", Name: "편미분", Keywords: "미분 partial differential"},
	{Char: "∇", Name: "나블라", Keywords: "델 nabla del gradient"},
	{Char: "∫", Name: "적분", Keywords: "integral"},
	{Char: "∬", Name: "이중 적분", Keywords: "적분 double integral"},
	{Char: "∮", Name: "선적분", Keywords: "적분 contour integral"},
	{Char: "∑", Name: "시그마 합", Keywords: "합 sum sigma"},
	{Char: "∏", Name: "파이 곱", Keywords: "곱 product pi"},
	{Char: "√", Name: "제곱근", Keywords: "루트 square root"},
	{Char: "∛", Name: "세제곱근", Keywords: "루트 cube root"},
	{Char: "∜", Name: "네제곱근", Keywords: "루트 fourth root"},
	{Char: "∀", Name: "모든", Keywords: "전칭 for all"},
	{Char: "∃", Name: "존재", Keywords: "존재 there exists"},
	{Char: "∄", Name: "존재하지 않음", Keywords: "there does not exist"},
	{Char: "∅", Name: "공집합", Keywords: "집합 empty set"},
	{Char: "∈", Name: "원소", Keywords: "집합 element of"},
	{Char: "∉", Name: "원소 아님", Keywords: "집합 not element of"},
	{Char: "∋", Name: "포함 원소", Keywords: "집합 contains as member"},
	{Char: "⊂", Name: "부분집합", Keywords: "집합 subset"},
	{Char: "⊃", Name: "포함집합", Keywords: "집합 superset"},
	{Char: "⊆", Name: "부분집합 또는 같음", Keywords: "집합 subset or equal"},
	{Char: "⊇", Name: "포함집합 또는 같음", Keywords: "집합 superset or equal"},
	{Char: "⊄", Name: "부분집합 아님", Keywords: "집합 not subset"},
	{Char: "∪", Name: "합집합", Keywords: "집합 union"},
	{Char: "∩", Name: "교집합", Keywords: "집합 intersection"},
	{Char: "∖", Name: "차집합", Keywords: "집합 set minus"},
	{Char: "∧", Name: "논리곱", Keywords: "그리고 logical and wedge"},
	{Char: "∨", Name: "논리합", Keywords: "또는 logical or vee"},
	{Char: "¬", Name: "부정", Keywords: "논리 not negation"},
	{Char: "⊕", Name: "배타적 논리합", Keywords: "엑스오 xor circled plus"},
	{Char: "⊗", Name: "텐서 곱", Keywords: "circled times tensor"},
	{Char: "⊥", Name: "수직", Keywords: "직교 perpendicular"},
	{Char: "∥", Name: "평행", Keywords: "parallel to"},
	{Char: "∠", Name: "각", Keywords: "각도 angle"},
	{Char: "∟", Name: "직각", Keywords: "각도 right angle"},
	{Char: "°", Name: "도", Keywords: "각도 온도 degree"},
	{Char: "′", Name: "프라임", Keywords: "분 prime minute"},
	{Char: "″", Name: "더블 프라임", Keywords: "초 double prime second"},
	{Char: "∴", Name: "그러므로", Keywords: "therefore"},
	{Char: "∵", Name: "왜냐하면", Keywords: "because"},
	{Char: "∼", Name: "물결 관계", Keywords: "닮음 tilde operator similar"},
	{Char: "≃", Name: "점근 같음", Keywords: "닮음 asymptotically equal"},
	{Char: "≜", Name: "정의에 의해 같음", Keywords: "정의 delta equal to"},
	{Char: "≝", Name: "정의됨", Keywords: "정의 equal by definition"},
	{Char: "≟", Name: "같은지 물음", Keywords: "questioned equal"},
	{Char: "⌈", Name: "천장 왼쪽", Keywords: "올림 ceiling left"},
	{Char: "⌉", Name: "천장 오른쪽", Keywords: "올림 ceiling right"},
	{Char: "⌊", Name: "바닥 왼쪽", Keywords: "내림 floor left"},
	{Char: "⌋", Name: "바닥 오른쪽", Keywords: "내림 floor right"},
	{Char: "⟨", Name: "왼쪽 꺾쇠", Keywords: "괄호 angle bracket left"},
	{Char: "⟩", Name: "오른쪽 꺾쇠", Keywords: "괄호 angle bracket right"},
	{Char: "ℝ", Name: "실수 집합", Keywords: "집합 real numbers"},
	{Char: "ℕ", Name: "자연수 집합", Keywords: "집합 natural numbers"},
	{Char: "ℤ", Name: "정수 집합", Keywords: "집합 integers"},
	{Char: "ℚ", Name: "유리수 집합", Keywords: "집합 rational numbers"},
	{Char: "ℂ", Name: "복소수 집합", Keywords: "집합 complex numbers"},
	{Char: "ℵ", Name: "알레프", Keywords: "aleph"},
	{Char: "ℓ", Name: "필기체 엘", Keywords: "script small l"},
	{Char: "℘", Name: "바이어슈트라스 피", Keywords: "weierstrass p"},
	{Char: "ℏ", Name: "플랑크 상수", Keywords: "planck constant hbar"},
	{Char: "∎", Name: "증명 끝", Keywords: "증명 end of proof qed"},
	{Char: "⊤", Name: "참", Keywords: "논리 top true"},
	{Char: "⊢", Name: "귀결", Keywords: "논리 turnstile proves"},
	{Char: "⊨", Name: "만족", Keywords: "논리 models entails"},
	{Char: "⋮", Name: "세로 생략", Keywords: "생략 vertical ellipsis"},
	{Char: "⋯", Name: "가운데 생략", Keywords: "생략 midline ellipsis"},
	{Char: "⋱", Name: "대각 생략", Keywords: "생략 diagonal ellipsis"},
	{Char: "≺", Name: "선행", Keywords: "순서 precedes"},
	{Char: "≻", Name: "후행", Keywords: "순서 succeeds"},
	{Char: "⊑", Name: "포함 사각", Keywords: "순서 square image of or equal"},
	{Char: "⌀", Name: "지름", Keywords: "공집합 diameter"},
	{Char: "∆", Name: "증분 델타", Keywords: "델타 increment delta"},
	{Char: "µ", Name: "마이크로", Keywords: "micro"},
	{Char: "Ω", Name: "옴", Keywords: "옴 ohm omega"},
	{Char: "Å", Name: "옹스트롬", Keywords: "angstrom"},
	{Char: "‰", Name: "퍼밀", Keywords: "천분율 per mille"},
	{Char: "‱", Name: "퍼밀리아드", Keywords: "만분율 per ten thousand"},
	{Char: "%", Name: "퍼센트", Keywords: "백분율 percent"},

	// 구두점 (punctuation)
	{Char: "…", Name: "말줄임표", Keywords: "생략 ellipsis dots"},
	{Char: "‥", Name: "두 점 말줄임", Keywords: "생략 two dot leader"},
	{Char: "–", Name: "엔 대시", Keywords: "줄표 en dash"},
	{Char: "—", Name: "엠 대시", Keywords: "줄표 em dash"},
	{Char: "―", Name: "가로줄", Keywords: "줄표 horizontal bar"},
	{Char: "‐", Name: "붙임표", Keywords: "하이픈 hyphen"},
	{Char: "‑", Name: "안 끊기는 붙임표", Keywords: "하이픈 non breaking hyphen"},
	{Char: "·", Name: "가운뎃점", Keywords: "점 middle dot interpunct"},
	{Char: "•", Name: "글머리 점", Keywords: "불릿 점 bullet"},
	{Char: "◦", Name: "흰 글머리 점", Keywords: "불릿 점 bullet white"},
	{Char: "‣", Name: "삼각 글머리 점", Keywords: "불릿 점 triangular bullet"},
	{Char: "⁃", Name: "하이픈 글머리 점", Keywords: "불릿 점 hyphen bullet"},
	{Char: "‧", Name: "이음 가운뎃점", Keywords: "점 hyphenation point"},
	{Char: "†", Name: "칼표", Keywords: "각주 dagger"},
	{Char: "‡", Name: "겹칼표", Keywords: "각주 double dagger"},
	{Char: "§", Name: "절 기호", Keywords: "섹션 section sign"},
	{Char: "¶", Name: "단락 기호", Keywords: "필크로 pilcrow paragraph"},
	{Char: "‖", Name: "겹세로줄", Keywords: "double vertical line"},
	{Char: "¦", Name: "끊긴 세로줄", Keywords: "broken bar"},
	{Char: "“", Name: "왼쪽 큰따옴표", Keywords: "따옴표 quote left double"},
	{Char: "”", Name: "오른쪽 큰따옴표", Keywords: "따옴표 quote right double"},
	{Char: "‘", Name: "왼쪽 작은따옴표", Keywords: "따옴표 quote left single"},
	{Char: "’", Name: "오른쪽 작은따옴표", Keywords: "따옴표 어퍼스트로피 quote right single apostrophe"},
	{Char: "„", Name: "아래 큰따옴표", Keywords: "따옴표 quote low double"},
	{Char: "‚", Name: "아래 작은따옴표", Keywords: "따옴표 quote low single"},
	{Char: "«", Name: "왼쪽 겹화살괄호", Keywords: "따옴표 guillemet left"},
	{Char: "»", Name: "오른쪽 겹화살괄호", Keywords: "따옴표 guillemet right"},
	{Char: "‹", Name: "왼쪽 홑화살괄호", Keywords: "따옴표 guillemet single left"},
	{Char: "›", Name: "오른쪽 홑화살괄호", Keywords: "따옴표 guillemet single right"},
	{Char: "¡", Name: "거꾸로 느낌표", Keywords: "느낌표 inverted exclamation"},
	{Char: "¿", Name: "거꾸로 물음표", Keywords: "물음표 inverted question"},
	{Char: "‽", Name: "물음느낌표", Keywords: "interrobang"},
	{Char: "⁇", Name: "겹물음표", Keywords: "물음표 double question"},
	{Char: "⁈", Name: "물음느낌", Keywords: "question exclamation"},
	{Char: "⁉", Name: "느낌물음", Keywords: "exclamation question"},
	{Char: "‼", Name: "겹느낌표", Keywords: "느낌표 double exclamation"},
	{Char: "※", Name: "참고표", Keywords: "코메 reference mark"},
	{Char: "⁂", Name: "별 세 개", Keywords: "asterism"},
	{Char: "⌗", Name: "우물 정", Keywords: "샵 해시 hash number sign"},
	{Char: "№", Name: "번호", Keywords: "넘버 numero"},
	{Char: "℗", Name: "저작인접권", Keywords: "phonogram copyright"},
	{Char: "©", Name: "저작권", Keywords: "카피라이트 copyright"},
	{Char: "®", Name: "등록상표", Keywords: "registered trademark"},
	{Char: "™", Name: "상표", Keywords: "트레이드마크 trademark"},
	{Char: "℠", Name: "서비스표", Keywords: "service mark"},
	{Char: "＿", Name: "전각 밑줄", Keywords: "밑줄 fullwidth low line"},
	{Char: "〜", Name: "물결표", Keywords: "물결 wave dash"},
	{Char: "～", Name: "전각 물결표", Keywords: "물결 fullwidth tilde"},
	{Char: "〰", Name: "물결 점선", Keywords: "물결 wavy dash"},
	{Char: "ᵎ", Name: "작은 느낌표", Keywords: "느낌표 small exclamation"},
	{Char: "〽", Name: "노래 기호", Keywords: "part alternation"},

	// 괄호 (bracket)
	{Char: "「", Name: "홑낫표 열기", Keywords: "괄호 낫표 corner bracket left"},
	{Char: "」", Name: "홑낫표 닫기", Keywords: "괄호 낫표 corner bracket right"},
	{Char: "『", Name: "겹낫표 열기", Keywords: "괄호 낫표 white corner bracket left"},
	{Char: "』", Name: "겹낫표 닫기", Keywords: "괄호 낫표 white corner bracket right"},
	{Char: "〈", Name: "홑화살괄호 열기", Keywords: "괄호 angle bracket left"},
	{Char: "〉", Name: "홑화살괄호 닫기", Keywords: "괄호 angle bracket right"},
	{Char: "《", Name: "겹화살괄호 열기", Keywords: "괄호 double angle bracket left"},
	{Char: "》", Name: "겹화살괄호 닫기", Keywords: "괄호 double angle bracket right"},
	{Char: "【", Name: "굵은 대괄호 열기", Keywords: "괄호 black lenticular left"},
	{Char: "】", Name: "굵은 대괄호 닫기", Keywords: "괄호 black lenticular right"},
	{Char: "〔", Name: "거북 등 괄호 열기", Keywords: "괄호 tortoise shell left"},
	{Char: "〕", Name: "거북 등 괄호 닫기", Keywords: "괄호 tortoise shell right"},
	{Char: "〖", Name: "흰 대괄호 열기", Keywords: "괄호 white lenticular left"},
	{Char: "〗", Name: "흰 대괄호 닫기", Keywords: "괄호 white lenticular right"},
	{Char: "（", Name: "전각 소괄호 열기", Keywords: "괄호 fullwidth paren left"},
	{Char: "）", Name: "전각 소괄호 닫기", Keywords: "괄호 fullwidth paren right"},
	{Char: "［", Name: "전각 대괄호 열기", Keywords: "괄호 fullwidth bracket left"},
	{Char: "］", Name: "전각 대괄호 닫기", Keywords: "괄호 fullwidth bracket right"},
	{Char: "｛", Name: "전각 중괄호 열기", Keywords: "괄호 fullwidth brace left"},
	{Char: "｝", Name: "전각 중괄호 닫기", Keywords: "괄호 fullwidth brace right"},
	{Char: "⦗", Name: "굵은 홈 괄호 열기", Keywords: "괄호 tortoise shell bracket left"},
	{Char: "⦘", Name: "굵은 홈 괄호 닫기", Keywords: "괄호 tortoise shell bracket right"},
	{Char: "⟦", Name: "겹대괄호 열기", Keywords: "괄호 double bracket left"},
	{Char: "⟧", Name: "겹대괄호 닫기", Keywords: "괄호 double bracket right"},
	{Char: "⟪", Name: "겹꺾쇠 열기", Keywords: "괄호 double angle left"},
	{Char: "⟫", Name: "겹꺾쇠 닫기", Keywords: "괄호 double angle right"},
	{Char: "⌜", Name: "왼쪽 위 모서리", Keywords: "괄호 corner top left"},
	{Char: "⌝", Name: "오른쪽 위 모서리", Keywords: "괄호 corner top right"},
	{Char: "⌞", Name: "왼쪽 아래 모서리", Keywords: "괄호 corner bottom left"},
	{Char: "⌟", Name: "오른쪽 아래 모서리", Keywords: "괄호 corner bottom right"},

	// 통화 (currency)
	{Char: "₩", Name: "원", Keywords: "화폐 통화 won korea"},
	{Char: "$", Name: "달러", Keywords: "화폐 통화 dollar"},
	{Char: "¢", Name: "센트", Keywords: "화폐 통화 cent"},
	{Char: "€", Name: "유로", Keywords: "화폐 통화 euro"},
	{Char: "£", Name: "파운드", Keywords: "화폐 통화 pound sterling"},
	{Char: "¥", Name: "엔", Keywords: "화폐 통화 yen japan"},
	{Char: "元", Name: "위안", Keywords: "화폐 통화 yuan china"},
	{Char: "₽", Name: "루블", Keywords: "화폐 통화 ruble russia"},
	{Char: "₹", Name: "루피", Keywords: "화폐 통화 rupee india"},
	{Char: "₫", Name: "동", Keywords: "화폐 통화 dong vietnam"},
	{Char: "₺", Name: "리라", Keywords: "화폐 통화 lira turkey"},
	{Char: "₴", Name: "흐리우냐", Keywords: "화폐 통화 hryvnia ukraine"},
	{Char: "₦", Name: "나이라", Keywords: "화폐 통화 naira nigeria"},
	{Char: "₱", Name: "페소", Keywords: "화폐 통화 peso philippines"},
	{Char: "฿", Name: "바트", Keywords: "화폐 통화 baht thailand"},
	{Char: "₪", Name: "셰켈", Keywords: "화폐 통화 shekel israel"},
	{Char: "₸", Name: "텡게", Keywords: "화폐 통화 tenge kazakhstan"},
	{Char: "₡", Name: "콜론", Keywords: "화폐 통화 colon"},
	{Char: "₲", Name: "과라니", Keywords: "화폐 통화 guarani"},
	{Char: "₵", Name: "세디", Keywords: "화폐 통화 cedi"},
	{Char: "₭", Name: "킵", Keywords: "화폐 통화 kip laos"},
	{Char: "₮", Name: "투그릭", Keywords: "화폐 통화 tugrik mongolia"},
	{Char: "₾", Name: "라리", Keywords: "화폐 통화 lari georgia"},
	{Char: "¤", Name: "통화 기호", Keywords: "화폐 통화 currency sign"},
	{Char: "₿", Name: "비트코인", Keywords: "화폐 통화 bitcoin"},

	// 괘선 (box drawing)
	{Char: "─", Name: "가로줄", Keywords: "괘선 박스 box horizontal"},
	{Char: "│", Name: "세로줄", Keywords: "괘선 박스 box vertical"},
	{Char: "┌", Name: "왼쪽 위 모서리", Keywords: "괘선 박스 box corner top left"},
	{Char: "┐", Name: "오른쪽 위 모서리", Keywords: "괘선 박스 box corner top right"},
	{Char: "└", Name: "왼쪽 아래 모서리", Keywords: "괘선 박스 box corner bottom left"},
	{Char: "┘", Name: "오른쪽 아래 모서리", Keywords: "괘선 박스 box corner bottom right"},
	{Char: "├", Name: "왼쪽 갈림", Keywords: "괘선 박스 box tee left"},
	{Char: "┤", Name: "오른쪽 갈림", Keywords: "괘선 박스 box tee right"},
	{Char: "┬", Name: "위 갈림", Keywords: "괘선 박스 box tee down"},
	{Char: "┴", Name: "아래 갈림", Keywords: "괘선 박스 box tee up"},
	{Char: "┼", Name: "십자 교차", Keywords: "괘선 박스 box cross"},
	{Char: "━", Name: "굵은 가로줄", Keywords: "괘선 박스 box horizontal heavy"},
	{Char: "┃", Name: "굵은 세로줄", Keywords: "괘선 박스 box vertical heavy"},
	{Char: "┏", Name: "굵은 왼쪽 위 모서리", Keywords: "괘선 박스 box heavy corner"},
	{Char: "┓", Name: "굵은 오른쪽 위 모서리", Keywords: "괘선 박스 box heavy corner"},
	{Char: "┗", Name: "굵은 왼쪽 아래 모서리", Keywords: "괘선 박스 box heavy corner"},
	{Char: "┛", Name: "굵은 오른쪽 아래 모서리", Keywords: "괘선 박스 box heavy corner"},
	{Char: "┣", Name: "굵은 왼쪽 갈림", Keywords: "괘선 박스 box heavy tee"},
	{Char: "┫", Name: "굵은 오른쪽 갈림", Keywords: "괘선 박스 box heavy tee"},
	{Char: "┳", Name: "굵은 위 갈림", Keywords: "괘선 박스 box heavy tee"},
	{Char: "┻", Name: "굵은 아래 갈림", Keywords: "괘선 박스 box heavy tee"},
	{Char: "╋", Name: "굵은 십자 교차", Keywords: "괘선 박스 box heavy cross"},
	{Char: "═", Name: "두 줄 가로줄", Keywords: "괘선 박스 box double horizontal"},
	{Char: "║", Name: "두 줄 세로줄", Keywords: "괘선 박스 box double vertical"},
	{Char: "╔", Name: "두 줄 왼쪽 위 모서리", Keywords: "괘선 박스 box double corner"},
	{Char: "╗", Name: "두 줄 오른쪽 위 모서리", Keywords: "괘선 박스 box double corner"},
	{Char: "╚", Name: "두 줄 왼쪽 아래 모서리", Keywords: "괘선 박스 box double corner"},
	{Char: "╝", Name: "두 줄 오른쪽 아래 모서리", Keywords: "괘선 박스 box double corner"},
	{Char: "╠", Name: "두 줄 왼쪽 갈림", Keywords: "괘선 박스 box double tee"},
	{Char: "╣", Name: "두 줄 오른쪽 갈림", Keywords: "괘선 박스 box double tee"},
	{Char: "╦", Name: "두 줄 위 갈림", Keywords: "괘선 박스 box double tee"},
	{Char: "╩", Name: "두 줄 아래 갈림", Keywords: "괘선 박스 box double tee"},
	{Char: "╬", Name: "두 줄 십자 교차", Keywords: "괘선 박스 box double cross"},
	{Char: "╭", Name: "둥근 왼쪽 위 모서리", Keywords: "괘선 박스 box round corner"},
	{Char: "╮", Name: "둥근 오른쪽 위 모서리", Keywords: "괘선 박스 box round corner"},
	{Char: "╯", Name: "둥근 오른쪽 아래 모서리", Keywords: "괘선 박스 box round corner"},
	{Char: "╰", Name: "둥근 왼쪽 아래 모서리", Keywords: "괘선 박스 box round corner"},
	{Char: "╱", Name: "오른쪽 위 대각선", Keywords: "괘선 박스 box diagonal"},
	{Char: "╲", Name: "오른쪽 아래 대각선", Keywords: "괘선 박스 box diagonal"},
	{Char: "╳", Name: "대각선 교차", Keywords: "괘선 박스 box diagonal cross"},
	{Char: "┄", Name: "점선 가로줄", Keywords: "괘선 박스 box dashed horizontal"},
	{Char: "┆", Name: "점선 세로줄", Keywords: "괘선 박스 box dashed vertical"},
	{Char: "╌", Name: "짧은 점선 가로줄", Keywords: "괘선 박스 box dashed horizontal"},
	{Char: "╎", Name: "짧은 점선 세로줄", Keywords: "괘선 박스 box dashed vertical"},

	// 기호 (sign)
	{Char: "✓", Name: "체크", Keywords: "체크 확인 check mark tick"},
	{Char: "✔", Name: "굵은 체크", Keywords: "체크 확인 check mark heavy"},
	{Char: "☑", Name: "체크 상자", Keywords: "체크 확인 ballot box checked"},
	{Char: "☐", Name: "빈 상자", Keywords: "체크 ballot box empty"},
	{Char: "☒", Name: "엑스 상자", Keywords: "체크 ballot box x"},
	{Char: "✗", Name: "엑스", Keywords: "엑스 취소 ballot x"},
	{Char: "✘", Name: "굵은 엑스", Keywords: "엑스 취소 ballot x heavy"},
	{Char: "✕", Name: "곱셈 엑스", Keywords: "엑스 multiplication x"},
	{Char: "✖", Name: "굵은 곱셈 엑스", Keywords: "엑스 multiplication x heavy"},
	{Char: "✚", Name: "굵은 십자", Keywords: "더하기 heavy greek cross"},
	{Char: "✛", Name: "열린 십자", Keywords: "더하기 open centre cross"},
	{Char: "⚠", Name: "경고", Keywords: "주의 warning", Aliases: "warning"},
	{Char: "⚡", Name: "번개", Keywords: "전기 high voltage lightning", Aliases: "zap"},
	{Char: "☠", Name: "해골", Keywords: "죽음 skull crossbones"},
	{Char: "☢", Name: "방사능", Keywords: "위험 radioactive"},
	{Char: "☣", Name: "생물학적 위험", Keywords: "위험 biohazard"},
	{Char: "♻", Name: "재활용", Keywords: "recycling"},
	{Char: "⚙", Name: "톱니바퀴", Keywords: "설정 gear"},
	{Char: "⚛", Name: "원자", Keywords: "atom"},
	{Char: "⚖", Name: "저울", Keywords: "균형 scales balance"},
	{Char: "⚓", Name: "닻", Keywords: "anchor"},
	{Char: "⚔", Name: "칼 두 자루", Keywords: "무기 crossed swords"},
	{Char: "⚑", Name: "깃발", Keywords: "flag"},
	{Char: "⚐", Name: "흰 깃발", Keywords: "flag white"},
	{Char: "⚕", Name: "의료 지팡이", Keywords: "의료 medical staff aesculapius"},
	{Char: "☮", Name: "평화", Keywords: "peace"},
	{Char: "☯", Name: "음양", Keywords: "태극 yin yang"},
	{Char: "☰", Name: "건 삼괘", Keywords: "괘 trigram heaven"},
	{Char: "☷", Name: "곤 삼괘", Keywords: "괘 trigram earth"},
	{Char: "♠", Name: "스페이드", Keywords: "카드 spade"},
	{Char: "♥", Name: "하트", Keywords: "카드 사랑 heart"},
	{Char: "♦", Name: "다이아몬드", Keywords: "카드 diamond"},
	{Char: "♣", Name: "클로버", Keywords: "카드 club"},
	{Char: "♤", Name: "흰 스페이드", Keywords: "카드 spade white"},
	{Char: "♡", Name: "흰 하트", Keywords: "카드 사랑 heart white"},
	{Char: "♢", Name: "흰 다이아몬드", Keywords: "카드 diamond white"},
	{Char: "♧", Name: "흰 클로버", Keywords: "카드 club white"},
	{Char: "☀", Name: "해", Keywords: "날씨 sun"},
	{Char: "☁", Name: "구름", Keywords: "날씨 cloud"},
	{Char: "☂", Name: "우산", Keywords: "날씨 umbrella"},
	{Char: "☃", Name: "눈사람", Keywords: "날씨 snowman"},
	{Char: "❄", Name: "눈송이", Keywords: "날씨 snowflake"},
	{Char: "☾", Name: "초승달", Keywords: "달 crescent moon"},
	{Char: "☽", Name: "상현달", Keywords: "달 first quarter moon"},
	{Char: "♀", Name: "여성", Keywords: "성별 female venus"},
	{Char: "♂", Name: "남성", Keywords: "성별 male mars"},
	{Char: "⚥", Name: "남녀", Keywords: "성별 male and female"},
	{Char: "♪", Name: "8분음표", Keywords: "음악 음표 note eighth"},
	{Char: "♫", Name: "이어진 8분음표", Keywords: "음악 음표 note beamed"},
	{Char: "♬", Name: "이어진 16분음표", Keywords: "음악 음표 note beamed sixteenth"},
	{Char: "♩", Name: "4분음표", Keywords: "음악 음표 note quarter"},
	{Char: "♭", Name: "플랫", Keywords: "음악 flat"},
	{Char: "♯", Name: "샾", Keywords: "음악 sharp"},
	{Char: "♮", Name: "제자리표", Keywords: "음악 natural"},
	{Char: "☎", Name: "전화", Keywords: "phone telephone"},
	{Char: "✉", Name: "편지", Keywords: "메일 envelope mail"},
	{Char: "✂", Name: "가위", Keywords: "scissors"},
	{Char: "✈", Name: "비행기", Keywords: "airplane"},
	{Char: "✏", Name: "연필", Keywords: "pencil"},
	{Char: "✒", Name: "펜촉", Keywords: "nib pen"},
	{Char: "☞", Name: "오른쪽 손가락", Keywords: "손 pointing right hand"},
	{Char: "☜", Name: "왼쪽 손가락", Keywords: "손 pointing left hand"},
	{Char: "☝", Name: "위쪽 손가락", Keywords: "손 pointing up hand"},
	{Char: "☟", Name: "아래쪽 손가락", Keywords: "손 pointing down hand"},
	{Char: "✍", Name: "쓰는 손", Keywords: "손 writing hand"},
	{Char: "⌚", Name: "손목시계", Keywords: "시계 watch"},
	{Char: "⌛", Name: "모래시계", Keywords: "시계 hourglass"},
	{Char: "⏰", Name: "알람 시계", Keywords: "시계 alarm clock", Aliases: "alarm_clock"},
	{Char: "⏳", Name: "흐르는 모래시계", Keywords: "시계 hourglass flowing"},
	{Char: "⏱", Name: "스톱워치", Keywords: "시계 stopwatch"},
	{Char: "⏲", Name: "타이머", Keywords: "시계 timer clock"},
	{Char: "⚀", Name: "주사위 일", Keywords: "주사위 die one"},
	{Char: "⚁", Name: "주사위 이", Keywords: "주사위 die two"},
	{Char: "⚂", Name: "주사위 삼", Keywords: "주사위 die three"},
	{Char: "⚃", Name: "주사위 사", Keywords: "주사위 die four"},
	{Char: "⚄", Name: "주사위 오", Keywords: "주사위 die five"},
	{Char: "⚅", Name: "주사위 육", Keywords: "주사위 die six"},
	{Char: "☕", Name: "커피", Keywords: "음료 hot beverage coffee"},
	{Char: "♨", Name: "온천", Keywords: "hot springs"},
	{Char: "⚘", Name: "꽃", Keywords: "flower"},
	{Char: "✿", Name: "겹꽃", Keywords: "flower blossom"},
	{Char: "❀", Name: "흰 꽃", Keywords: "flower white"},
	{Char: "❁", Name: "동그란 꽃", Keywords: "flower eight petalled"},
	{Char: "☘", Name: "세잎클로버", Keywords: "행운 shamrock"},
	{Char: "⚜", Name: "백합 문장", Keywords: "fleur de lis"},
	{Char: "〄", Name: "일본 공업 규격", Keywords: "jis mark"},
	{Char: "♿", Name: "휠체어", Keywords: "장애인 wheelchair"},
	{Char: "⚟", Name: "위쪽 반원", Keywords: "notched left semicircle"},
	{Char: "⏩", Name: "빨리 감기", Keywords: "재생 fast forward"},
	{Char: "⏪", Name: "되감기", Keywords: "재생 rewind"},
	{Char: "⏸", Name: "일시정지", Keywords: "재생 pause"},
	{Char: "⏹", Name: "정지", Keywords: "재생 stop"},
	{Char: "⏺", Name: "녹화", Keywords: "재생 record"},
	{Char: "⏯", Name: "재생 일시정지", Keywords: "재생 play pause"},
	{Char: "♲", Name: "재활용 흰색", Keywords: "recycling white"},
	{Char: "✳", Name: "여덟살 별표", Keywords: "별표 asterisk eight spoked"},
	{Char: "✴", Name: "여덟꼭짓점 별", Keywords: "별 star eight pointed"},
	{Char: "❇", Name: "반짝임", Keywords: "sparkle"},
	{Char: "✨", Name: "반짝반짝", Keywords: "sparkles", Aliases: "sparkles"},
	{Char: "❖", Name: "검은 마름모 꽃", Keywords: "마름모 diamond minus"},
	{Char: "➤", Name: "검은 오른쪽 화살촉", Keywords: "화살표 arrowhead right"},
	{Char: "➢", Name: "오른쪽 화살촉", Keywords: "화살표 arrowhead right three"},
	{Char: "⟡", Name: "흰 마름모", Keywords: "마름모 diamond"},
	{Char: "⌂", Name: "집", Keywords: "house home"},
	{Char: "⏻", Name: "전원", Keywords: "power symbol"},
	{Char: "⏼", Name: "전원 켜짐", Keywords: "power on off"},
	{Char: "⭘", Name: "전원 끄기", Keywords: "power off"},

	// 문자와 숫자 (letter and number)
	{Char: "α", Name: "알파", Keywords: "그리스 greek alpha"},
	{Char: "β", Name: "베타", Keywords: "그리스 greek beta"},
	{Char: "γ", Name: "감마", Keywords: "그리스 greek gamma"},
	{Char: "δ", Name: "델타", Keywords: "그리스 greek delta"},
	{Char: "ε", Name: "엡실론", Keywords: "그리스 greek epsilon"},
	{Char: "ζ", Name: "제타", Keywords: "그리스 greek zeta"},
	{Char: "η", Name: "에타", Keywords: "그리스 greek eta"},
	{Char: "θ", Name: "세타", Keywords: "그리스 greek theta"},
	{Char: "ι", Name: "이오타", Keywords: "그리스 greek iota"},
	{Char: "κ", Name: "카파", Keywords: "그리스 greek kappa"},
	{Char: "λ", Name: "람다", Keywords: "그리스 greek lambda"},
	{Char: "μ", Name: "뮤", Keywords: "그리스 greek mu"},
	{Char: "ν", Name: "뉴", Keywords: "그리스 greek nu"},
	{Char: "ξ", Name: "크시", Keywords: "그리스 greek xi"},
	{Char: "π", Name: "파이", Keywords: "그리스 greek pi"},
	{Char: "ρ", Name: "로", Keywords: "그리스 greek rho"},
	{Char: "σ", Name: "시그마", Keywords: "그리스 greek sigma"},
	{Char: "τ", Name: "타우", Keywords: "그리스 greek tau"},
	{Char: "υ", Name: "윕실론", Keywords: "그리스 greek upsilon"},
	{Char: "φ", Name: "피", Keywords: "그리스 greek phi"},
	{Char: "χ", Name: "카이", Keywords: "그리스 greek chi"},
	{Char: "ψ", Name: "프시", Keywords: "그리스 greek psi"},
	{Char: "ω", Name: "오메가", Keywords: "그리스 greek omega"},
	{Char: "Γ", Name: "대문자 감마", Keywords: "그리스 greek capital gamma"},
	{Char: "Δ", Name: "대문자 델타", Keywords: "그리스 greek capital delta"},
	{Char: "Θ", Name: "대문자 세타", Keywords: "그리스 greek capital theta"},
	{Char: "Λ", Name: "대문자 람다", Keywords: "그리스 greek capital lambda"},
	{Char: "Ξ", Name: "대문자 크시", Keywords: "그리스 greek capital xi"},
	{Char: "Π", Name: "대문자 파이", Keywords: "그리스 greek capital pi"},
	{Char: "Σ", Name: "대문자 시그마", Keywords: "그리스 greek capital sigma"},
	{Char: "Φ", Name: "대문자 피", Keywords: "그리스 greek capital phi"},
	{Char: "Ψ", Name: "대문자 프시", Keywords: "그리스 greek capital psi"},
	{Char: "⁰", Name: "0 위첨자", Keywords: "위첨자 첨자 superscript 0"},
	{Char: "¹", Name: "1 위첨자", Keywords: "위첨자 첨자 superscript 1"},
	{Char: "²", Name: "2 위첨자", Keywords: "위첨자 첨자 superscript 2"},
	{Char: "³", Name: "3 위첨자", Keywords: "위첨자 첨자 superscript 3"},
	{Char: "⁴", Name: "4 위첨자", Keywords: "위첨자 첨자 superscript 4"},
	{Char: "⁵", Name: "5 위첨자", Keywords: "위첨자 첨자 superscript 5"},
	{Char: "⁶", Name: "6 위첨자", Keywords: "위첨자 첨자 superscript 6"},
	{Char: "⁷", Name: "7 위첨자", Keywords: "위첨자 첨자 superscript 7"},
	{Char: "⁸", Name: "8 위첨자", Keywords: "위첨자 첨자 superscript 8"},
	{Char: "⁹", Name: "9 위첨자", Keywords: "위첨자 첨자 superscript 9"},
	{Char: "⁺", Name: "더하기 위첨자", Keywords: "위첨자 첨자 superscript plus"},
	{Char: "⁻", Name: "빼기 위첨자", Keywords: "위첨자 첨자 superscript minus"},
	{Char: "ⁿ", Name: "n 위첨자", Keywords: "위첨자 첨자 superscript n"},
	{Char: "₀", Name: "0 아래첨자", Keywords: "아래첨자 첨자 subscript 0"},
	{Char: "₁", Name: "1 아래첨자", Keywords: "아래첨자 첨자 subscript 1"},
	{Char: "₂", Name: "2 아래첨자", Keywords: "아래첨자 첨자 subscript 2"},
	{Char: "₃", Name: "3 아래첨자", Keywords: "아래첨자 첨자 subscript 3"},
	{Char: "₄", Name: "4 아래첨자", Keywords: "아래첨자 첨자 subscript 4"},
	{Char: "₅", Name: "5 아래첨자", Keywords: "아래첨자 첨자 subscript 5"},
	{Char: "₆", Name: "6 아래첨자", Keywords: "아래첨자 첨자 subscript 6"},
	{Char: "₇", Name: "7 아래첨자", Keywords: "아래첨자 첨자 subscript 7"},
	{Char: "₈", Name: "8 아래첨자", Keywords: "아래첨자 첨자 subscript 8"},
	{Char: "₉", Name: "9 아래첨자", Keywords: "아래첨자 첨자 subscript 9"},
	{Char: "₊", Name: "더하기 아래첨자", Keywords: "아래첨자 첨자 subscript plus"},
	{Char: "₋", Name: "빼기 아래첨자", Keywords: "아래첨자 첨자 subscript minus"},
	{Char: "½", Name: "이분의 일", Keywords: "분수 fraction half"},
	{Char: "⅓", Name: "삼분의 일", Keywords: "분수 fraction third"},
	{Char: "⅔", Name: "삼분의 이", Keywords: "분수 fraction two thirds"},
	{Char: "¼", Name: "사분의 일", Keywords: "분수 fraction quarter"},
	{Char: "¾", Name: "사분의 삼", Keywords: "분수 fraction three quarters"},
	{Char: "⅕", Name: "오분의 일", Keywords: "분수 fraction fifth"},
	{Char: "⅛", Name: "팔분의 일", Keywords: "분수 fraction eighth"},
	{Char: "⅜", Name: "팔분의 삼", Keywords: "분수 fraction three eighths"},
	{Char: "⅚", Name: "육분의 오", Keywords: "분수 fraction five sixths"},
	{Char: "⅞", Name: "팔분의 칠", Keywords: "분수 fraction seven eighths"},
	{Char: "Ⅰ", Name: "로마 숫자 1", Keywords: "로마 숫자 roman numeral one"},
	{Char: "Ⅱ", Name: "로마 숫자 2", Keywords: "로마 숫자 roman numeral two"},
	{Char: "Ⅲ", Name: "로마 숫자 3", Keywords: "로마 숫자 roman numeral three"},
	{Char: "Ⅳ", Name: "로마 숫자 4", Keywords: "로마 숫자 roman numeral four"},
	{Char: "Ⅴ", Name: "로마 숫자 5", Keywords: "로마 숫자 roman numeral five"},
	{Char: "Ⅵ", Name: "로마 숫자 6", Keywords: "로마 숫자 roman numeral six"},
	{Char: "Ⅶ", Name: "로마 숫자 7", Keywords: "로마 숫자 roman numeral seven"},
	{Char: "Ⅷ", Name: "로마 숫자 8", Keywords: "로마 숫자 roman numeral eight"},
	{Char: "Ⅸ", Name: "로마 숫자 9", Keywords: "로마 숫자 roman numeral nine"},
	{Char: "Ⅹ", Name: "로마 숫자 10", Keywords: "로마 숫자 roman numeral ten"},
	{Char: "①", Name: "동그라미 숫자 1", Keywords: "원문자 동그라미 숫자 circled number 1"},
	{Char: "②", Name: "동그라미 숫자 2", Keywords: "원문자 동그라미 숫자 circled number 2"},
	{Char: "③", Name: "동그라미 숫자 3", Keywords: "원문자 동그라미 숫자 circled number 3"},
	{Char: "④", Name: "동그라미 숫자 4", Keywords: "원문자 동그라미 숫자 circled number 4"},
	{Char: "⑤", Name: "동그라미 숫자 5", Keywords: "원문자 동그라미 숫자 circled number 5"},
	{Char: "⑥", Name: "동그라미 숫자 6", Keywords: "원문자 동그라미 숫자 circled number 6"},
	{Char: "⑦", Name: "동그라미 숫자 7", Keywords: "원문자 동그라미 숫자 circled number 7"},
	{Char: "⑧", Name: "동그라미 숫자 8", Keywords: "원문자 동그라미 숫자 circled number 8"},
	{Char: "⑨", Name: "동그라미 숫자 9", Keywords: "원문자 동그라미 숫자 circled number 9"},
	{Char: "⑩", Name: "동그라미 숫자 10", Keywords: "원문자 동그라미 숫자 circled number 10"},
	{Char: "⑪", Name: "동그라미 숫자 11", Keywords: "원문자 동그라미 숫자 circled number 11"},
	{Char: "⑫", Name: "동그라미 숫자 12", Keywords: "원문자 동그라미 숫자 circled number 12"},
	{Char: "⑬", Name: "동그라미 숫자 13", Keywords: "원문자 동그라미 숫자 circled number 13"},
	{Char: "⑭", Name: "동그라미 숫자 14", Keywords: "원문자 동그라미 숫자 circled number 14"},
	{Char: "⑮", Name: "동그라미 숫자 15", Keywords: "원문자 동그라미 숫자 circled number 15"},
	{Char: "⑯", Name: "동그라미 숫자 16", Keywords: "원문자 동그라미 숫자 circled number 16"},
	{Char: "⑰", Name: "동그라미 숫자 17", Keywords: "원문자 동그라미 숫자 circled number 17"},
	{Char: "⑱", Name: "동그라미 숫자 18", Keywords: "원문자 동그라미 숫자 circled number 18"},
	{Char: "⑲", Name: "동그라미 숫자 19", Keywords: "원문자 동그라미 숫자 circled number 19"},
	{Char: "⑳", Name: "동그라미 숫자 20", Keywords: "원문자 동그라미 숫자 circled number 20"},
	{Char: "❶", Name: "검은 동그라미 숫자 1", Keywords: "원문자 동그라미 숫자 circled number black 1"},
	{Char: "❷", Name: "검은 동그라미 숫자 2", Keywords: "원문자 동그라미 숫자 circled number black 2"},
	{Char: "❸", Name: "검은 동그라미 숫자 3", Keywords: "원문자 동그라미 숫자 circled number black 3"},
	{Char: "❹", Name: "검은 동그라미 숫자 4", Keywords: "원문자 동그라미 숫자 circled number black 4"},
	{Char: "❺", Name: "검은 동그라미 숫자 5", Keywords: "원문자 동그라미 숫자 circled number black 5"},
	{Char: "❻", Name: "검은 동그라미 숫자 6", Keywords: "원문자 동그라미 숫자 circled number black 6"},
	{Char: "❼", Name: "검은 동그라미 숫자 7", Keywords: "원문자 동그라미 숫자 circled number black 7"},
	{Char: "❽", Name: "검은 동그라미 숫자 8", Keywords: "원문자 동그라미 숫자 circled number black 8"},
	{Char: "❾", Name: "검은 동그라미 숫자 9", Keywords: "원문자 동그라미 숫자 circled number black 9"},
	{Char: "❿", Name: "검은 동그라미 숫자 10", Keywords: "원문자 동그라미 숫자 circled number black 10"},
	{Char: "⑴", Name: "괄호 숫자 1", Keywords: "괄호 숫자 parenthesized number 1"},
	{Char: "⑵", Name: "괄호 숫자 2", Keywords: "괄호 숫자 parenthesized number 2"},
	{Char: "⑶", Name: "괄호 숫자 3", Keywords: "괄호 숫자 parenthesized number 3"},
	{Char: "⑷", Name: "괄호 숫자 4", Keywords: "괄호 숫자 parenthesized number 4"},
	{Char: "⑸", Name: "괄호 숫자 5", Keywords: "괄호 숫자 parenthesized number 5"},
	{Char: "⑹", Name: "괄호 숫자 6", Keywords: "괄호 숫자 parenthesized number 6"},
	{Char: "⑺", Name: "괄호 숫자 7", Keywords: "괄호 숫자 parenthesized number 7"},
	{Char: "⑻", Name: "괄호 숫자 8", Keywords: "괄호 숫자 parenthesized number 8"},
	{Char: "⑼", Name: "괄호 숫자 9", Keywords: "괄호 숫자 parenthesized number 9"},
	{Char: "⑽", Name: "괄호 숫자 10", Keywords: "괄호 숫자 parenthesized number 10"},
	{Char: "㎜", Name: "밀리미터", Keywords: "단위 unit millimeter mm"},
	{Char: "㎝", Name: "센티미터", Keywords: "단위 unit centimeter cm"},
	{Char: "㎞", Name: "킬로미터", Keywords: "단위 unit kilometer km"},
	{Char: "㎡", Name: "제곱미터", Keywords: "단위 unit square meter"},
	{Char: "㎥", Name: "세제곱미터", Keywords: "단위 unit cubic meter"},
	{Char: "㎏", Name: "킬로그램", Keywords: "단위 unit kilogram kg"},
	{Char: "㎎", Name: "밀리그램", Keywords: "단위 unit milligram mg"},
	{Char: "㎖", Name: "밀리리터", Keywords: "단위 unit milliliter ml"},
	{Char: "㏄", Name: "시시", Keywords: "단위 unit cc"},
	{Char: "㎈", Name: "킬로칼로리", Keywords: "단위 unit kilocalorie"},
	{Char: "℃", Name: "섭씨", Keywords: "온도 단위 unit celsius degree"},
	{Char: "℉", Name: "화씨", Keywords: "온도 단위 unit fahrenheit degree"},
	{Char: "㎐", Name: "헤르츠", Keywords: "단위 unit hertz hz"},
	{Char: "㎅", Name: "킬로바이트", Keywords: "단위 unit kilobyte kb"},
	{Char: "㎆", Name: "메가바이트", Keywords: "단위 unit megabyte mb"},
	{Char: "㎇", Name: "기가바이트", Keywords: "단위 unit gigabyte gb"},
	{Char: "㎾", Name: "킬로와트", Keywords: "단위 unit kilowatt kw"},
	{Char: "㏈", Name: "데시벨", Keywords: "단위 unit decibel db"},
	{Char: "㎳", Name: "밀리초", Keywords: "단위 unit millisecond ms"},
	{Char: "㎲", Name: "마이크로초", Keywords: "단위 unit microsecond"},
	{Char: "㉠", Name: "동그라미 ㄱ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㄱ"},
	{Char: "㉡", Name: "동그라미 ㄴ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㄴ"},
	{Char: "㉢", Name: "동그라미 ㄷ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㄷ"},
	{Char: "㉣", Name: "동그라미 ㄹ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㄹ"},
	{Char: "㉤", Name: "동그라미 ㅁ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅁ"},
	{Char: "㉥", Name: "동그라미 ㅂ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅂ"},
	{Char: "㉦", Name: "동그라미 ㅅ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅅ"},
	{Char: "㉧", Name: "동그라미 ㅇ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅇ"},
	{Char: "㉨", Name: "동그라미 ㅈ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅈ"},
	{Char: "㉩", Name: "동그라미 ㅊ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅊ"},
	{Char: "㉪", Name: "동그라미 ㅋ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅋ"},
	{Char: "㉫", Name: "동그라미 ㅌ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅌ"},
	{Char: "㉬", Name: "동그라미 ㅍ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅍ"},
	{Char: "㉭", Name: "동그라미 ㅎ", Keywords: "원문자 동그라미 한글 자음 circled hangul ㅎ"},
	{Char: "㉮", Name: "동그라미 가", Keywords: "원문자 동그라미 한글 circled hangul 가"},
	{Char: "㉯", Name: "동그라미 나", Keywords: "원문자 동그라미 한글 circled hangul 나"},
	{Char: "㉰", Name: "동그라미 다", Keywords: "원문자 동그라미 한글 circled hangul 다"},
	{Char: "㉱", Name: "동그라미 라", Keywords: "원문자 동그라미 한글 circled hangul 라"},
	{Char: "㉲", Name: "동그라미 마", Keywords: "원문자 동그라미 한글 circled hangul 마"},
	{Char: "㉳", Name: "동그라미 바", Keywords: "원문자 동그라미 한글 circled hangul 바"},
	{Char: "㉴", Name: "동그라미 사", Keywords: "원문자 동그라미 한글 circled hangul 사"},
	{Char: "㉵", Name: "동그라미 아", Keywords: "원문자 동그라미 한글 circled hangul 아"},
	{Char: "㉶", Name: "동그라미 자", Keywords: "원문자 동그라미 한글 circled hangul 자"},
	{Char: "㉷", Name: "동그라미 차", Keywords: "원문자 동그라미 한글 circled hangul 차"},
	{Char: "㉸", Name: "동그라미 카", Keywords: "원문자 동그라미 한글 circled hangul 카"},
	{Char: "㉹", Name: "동그라미 타", Keywords: "원문자 동그라미 한글 circled hangul 타"},
	{Char: "㉺", Name: "동그라미 파", Keywords: "원문자 동그라미 한글 circled hangul 파"},
	{Char: "㉻", Name: "동그라미 하", Keywords: "원문자 동그라미 한글 circled hangul 하"},
	{Char: "㈀", Name: "괄호 ㄱ", Keywords: "괄호 한글 자음 parenthesized hangul ㄱ"},
	{Char: "㈁", Name: "괄호 ㄴ", Keywords: "괄호 한글 자음 parenthesized hangul ㄴ"},
	{Char: "㈂", Name: "괄호 ㄷ", Keywords: "괄호 한글 자음 parenthesized hangul ㄷ"},
	{Char: "㈃", Name: "괄호 ㄹ", Keywords: "괄호 한글 자음 parenthesized hangul ㄹ"},
	{Char: "㈄", Name: "괄호 ㅁ", Keywords: "괄호 한글 자음 parenthesized hangul ㅁ"},
	{Char: "㈅", Name: "괄호 ㅂ", Keywords: "괄호 한글 자음 parenthesized hangul ㅂ"},
	{Char: "㈆", Name: "괄호 ㅅ", Keywords: "괄호 한글 자음 parenthesized hangul ㅅ"},
	{Char: "㈇", Name: "괄호 ㅇ", Keywords: "괄호 한글 자음 parenthesized hangul ㅇ"},
	{Char: "㈈", Name: "괄호 ㅈ", Keywords: "괄호 한글 자음 parenthesized hangul ㅈ"},
	{Char: "㈉", Name: "괄호 ㅊ", Keywords: "괄호 한글 자음 parenthesized hangul ㅊ"},
	{Char: "㈊", Name: "괄호 ㅋ", Keywords: "괄호 한글 자음 parenthesized hangul ㅋ"},
	{Char: "㈋", Name: "괄호 ㅌ", Keywords: "괄호 한글 자음 parenthesized hangul ㅌ"},
	{Char: "㈌", Name: "괄호 ㅍ", Keywords: "괄호 한글 자음 parenthesized hangul ㅍ"},
	{Char: "㈍", Name: "괄호 ㅎ", Keywords: "괄호 한글 자음 parenthesized hangul ㅎ"},
	{Char: "㈎", Name: "괄호 가", Keywords: "괄호 한글 parenthesized hangul 가"},
	{Char: "㈏", Name: "괄호 나", Keywords: "괄호 한글 parenthesized hangul 나"},
	{Char: "㈐", Name: "괄호 다", Keywords: "괄호 한글 parenthesized hangul 다"},
	{Char: "㈑", Name: "괄호 라", Keywords: "괄호 한글 parenthesized hangul 라"},
	{Char: "㈒", Name: "괄호 마", Keywords: "괄호 한글 parenthesized hangul 마"},
	{Char: "㈓", Name: "괄호 바", Keywords: "괄호 한글 parenthesized hangul 바"},
	{Char: "㈔", Name: "괄호 사", Keywords: "괄호 한글 parenthesized hangul 사"},
	{Char: "㈕", Name: "괄호 아", Keywords: "괄호 한글 parenthesized hangul 아"},
	{Char: "㈖", Name: "괄호 자", Keywords: "괄호 한글 parenthesized hangul 자"},
	{Char: "㈗", Name: "괄호 차", Keywords: "괄호 한글 parenthesized hangul 차"},
	{Char: "㈘", Name: "괄호 카", Keywords: "괄호 한글 parenthesized hangul 카"},
	{Char: "㈙", Name: "괄호 타", Keywords: "괄호 한글 parenthesized hangul 타"},
	{Char: "㈚", Name: "괄호 파", Keywords: "괄호 한글 parenthesized hangul 파"},
	{Char: "㈛", Name: "괄호 하", Keywords: "괄호 한글 parenthesized hangul 하"},

	// 이모지 표정 (emoji face)
	{Char: "😀", Name: "활짝 웃는 얼굴", Keywords: "이모지 표정 웃음 grinning face"},
	{Char: "😃", Name: "눈웃음 짓는 얼굴", Keywords: "이모지 표정 웃음 grinning big eyes"},
	{Char: "😄", Name: "웃으며 눈웃음 짓는 얼굴", Keywords: "이모지 표정 웃음 grinning smiling eyes", Aliases: "smile"},
	{Char: "😁", Name: "활짝 웃으며 눈웃음", Keywords: "이모지 표정 웃음 beaming face"},
	{Char: "😆", Name: "눈 감고 크게 웃는 얼굴", Keywords: "이모지 표정 웃음 grinning squinting"},
	{Char: "😅", Name: "식은땀 흘리며 웃는 얼굴", Keywords: "이모지 표정 웃음 땀 grinning sweat"},
	{Char: "🤣", Name: "바닥을 구르며 웃는 얼굴", Keywords: "이모지 표정 웃음 rolling on the floor laughing"},
	{Char: "😂", Name: "눈물 나게 웃는 얼굴", Keywords: "이모지 표정 웃음 눈물 tears of joy", Aliases: "joy"},
	{Char: "🙂", Name: "살짝 웃는 얼굴", Keywords: "이모지 표정 웃음 slightly smiling"},
	{Char: "🙃", Name: "거꾸로 된 얼굴", Keywords: "이모지 표정 upside down face"},
	{Char: "😉", Name: "윙크하는 얼굴", Keywords: "이모지 표정 winking face", Aliases: "wink"},
	{Char: "😊", Name: "활짝 웃는 눈웃음 얼굴", Keywords: "이모지 표정 웃음 smiling eyes", Aliases: "blush"},
	{Char: "😇", Name: "천사 얼굴", Keywords: "이모지 표정 halo angel"},
	{Char: "🥰", Name: "하트에 둘러싸인 얼굴", Keywords: "이모지 표정 사랑 smiling hearts"},
	{Char: "😍", Name: "하트 눈 얼굴", Keywords: "이모지 표정 사랑 heart eyes"},
	{Char: "🤩", Name: "별 눈 얼굴", Keywords: "이모지 표정 star struck"},
	{Char: "😘", Name: "뽀뽀하는 얼굴", Keywords: "이모지 표정 사랑 blowing a kiss"},
	{Char: "😗", Name: "입 오므린 얼굴", Keywords: "이모지 표정 kissing face"},
	{Char: "😚", Name: "눈 감고 뽀뽀하는 얼굴", Keywords: "이모지 표정 kissing closed eyes"},
	{Char: "😙", Name: "웃으며 뽀뽀하는 얼굴", Keywords: "이모지 표정 kissing smiling eyes"},
	{Char: "😋", Name: "맛있는 얼굴", Keywords: "이모지 표정 savoring food yum"},
	{Char: "😛", Name: "혀 내민 얼굴", Keywords: "이모지 표정 tongue out"},
	{Char: "😜", Name: "윙크하며 혀 내민 얼굴", Keywords: "이모지 표정 winking tongue"},
	{Char: "🤪", Name: "엉뚱한 얼굴", Keywords: "이모지 표정 zany face"},
	{Char: "😝", Name: "눈 감고 혀 내민 얼굴", Keywords: "이모지 표정 squinting tongue"},
	{Char: "🤑", Name: "돈 좋아하는 얼굴", Keywords: "이모지 표정 돈 money mouth"},
	{Char: "🤗", Name: "안아주는 얼굴", Keywords: "이모지 표정 hugging face"},
	{Char: "🤭", Name: "입 가린 얼굴", Keywords: "이모지 표정 hand over mouth"},
	{Char: "🤫", Name: "조용히 하라는 얼굴", Keywords: "이모지 표정 shushing face"},
	{Char: "🤔", Name: "생각하는 얼굴", Keywords: "이모지 표정 thinking face", Aliases: "thinking"},
	{Char: "🤐", Name: "입 지퍼 얼굴", Keywords: "이모지 표정 zipper mouth"},
	{Char: "🤨", Name: "눈썹 치켜올린 얼굴", Keywords: "이모지 표정 raised eyebrow"},
	{Char: "😐", Name: "무표정한 얼굴", Keywords: "이모지 표정 neutral face"},
	{Char: "😑", Name: "심드렁한 얼굴", Keywords: "이모지 표정 expressionless"},
	{Char: "😶", Name: "입 없는 얼굴", Keywords: "이모지 표정 no mouth"},
	{Char: "😏", Name: "능글맞은 얼굴", Keywords: "이모지 표정 smirking face"},
	{Char: "😒", Name: "떨떠름한 얼굴", Keywords: "이모지 표정 unamused face"},
	{Char: "🙄", Name: "눈 굴리는 얼굴", Keywords: "이모지 표정 rolling eyes"},
	{Char: "😬", Name: "이 드러낸 얼굴", Keywords: "이모지 표정 grimacing face"},
	{Char: "🤥", Name: "거짓말하는 얼굴", Keywords: "이모지 표정 lying face"},
	{Char: "😌", Name: "안도하는 얼굴", Keywords: "이모지 표정 relieved face"},
	{Char: "😔", Name: "시무룩한 얼굴", Keywords: "이모지 표정 pensive face"},
	{Char: "😪", Name: "졸린 얼굴", Keywords: "이모지 표정 sleepy face"},
	{Char: "🤤", Name: "침 흘리는 얼굴", Keywords: "이모지 표정 drooling face"},
	{Char: "😴", Name: "자는 얼굴", Keywords: "이모지 표정 sleeping face"},
	{Char: "😷", Name: "마스크 쓴 얼굴", Keywords: "이모지 표정 medical mask"},
	{Char: "🤒", Name: "체온계 문 얼굴", Keywords: "이모지 표정 face with thermometer"},
	{Char: "🤕", Name: "머리 다친 얼굴", Keywords: "이모지 표정 head bandage"},
	{Char: "🤢", Name: "메스꺼운 얼굴", Keywords: "이모지 표정 nauseated face"},
	{Char: "🤮", Name: "토하는 얼굴", Keywords: "이모지 표정 vomiting face"},
	{Char: "🤧", Name: "재채기하는 얼굴", Keywords: "이모지 표정 sneezing face"},
	{Char: "🥵", Name: "더워하는 얼굴", Keywords: "이모지 표정 hot face"},
	{Char: "🥶", Name: "추워하는 얼굴", Keywords: "이모지 표정 cold face"},
	{Char: "😵", Name: "어지러운 얼굴", Keywords: "이모지 표정 dizzy face"},
	{Char: "🤯", Name: "머리 터지는 얼굴", Keywords: "이모지 표정 exploding head"},
	{Char: "🤠", Name: "카우보이 얼굴", Keywords: "이모지 표정 cowboy hat"},
	{Char: "🥳", Name: "파티하는 얼굴", Keywords: "이모지 표정 partying face"},
	{Char: "😎", Name: "선글라스 낀 얼굴", Keywords: "이모지 표정 sunglasses cool"},
	{Char: "🤓", Name: "안경 쓴 얼굴", Keywords: "이모지 표정 nerd face"},
	{Char: "🧐", Name: "외알 안경 얼굴", Keywords: "이모지 표정 monocle"},
	{Char: "😕", Name: "헷갈리는 얼굴", Keywords: "이모지 표정 confused face"},
	{Char: "😟", Name: "걱정하는 얼굴", Keywords: "이모지 표정 worried face"},
	{Char: "🙁", Name: "살짝 찡그린 얼굴", Keywords: "이모지 표정 slightly frowning"},
	{Char: "😮", Name: "입 벌린 얼굴", Keywords: "이모지 표정 open mouth"},
	{Char: "😯", Name: "놀란 얼굴", Keywords: "이모지 표정 hushed face"},
	{Char: "😲", Name: "깜짝 놀란 얼굴", Keywords: "이모지 표정 astonished face"},
	{Char: "😳", Name: "얼굴 붉힌 얼굴", Keywords: "이모지 표정 flushed face"},
	{Char: "🥺", Name: "애원하는 얼굴", Keywords: "이모지 표정 pleading face"},
	{Char: "😦", Name: "찡그리며 입 벌린 얼굴", Keywords: "이모지 표정 frowning open mouth"},
	{Char: "😨", Name: "겁먹은 얼굴", Keywords: "이모지 표정 fearful face"},
	{Char: "😰", Name: "식은땀 흘리는 얼굴", Keywords: "이모지 표정 땀 anxious sweat"},
	{Char: "😥", Name: "슬픈 안도의 얼굴", Keywords: "이모지 표정 sad but relieved"},
	{Char: "😢", Name: "우는 얼굴", Keywords: "이모지 표정 눈물 crying face", Aliases: "cry"},
	{Char: "😭", Name: "엉엉 우는 얼굴", Keywords: "이모지 표정 눈물 loudly crying"},
	{Char: "😱", Name: "비명 지르는 얼굴", Keywords: "이모지 표정 screaming in fear"},
	{Char: "😖", Name: "괴로운 얼굴", Keywords: "이모지 표정 confounded face"},
	{Char: "😣", Name: "참고 있는 얼굴", Keywords: "이모지 표정 persevering face"},
	{Char: "😞", Name: "실망한 얼굴", Keywords: "이모지 표정 disappointed face"},
	{Char: "😓", Name: "식은땀 흘리며 낙담", Keywords: "이모지 표정 땀 downcast sweat"},
	{Char: "😩", Name: "지친 얼굴", Keywords: "이모지 표정 weary face"},
	{Char: "😫", Name: "진저리 나는 얼굴", Keywords: "이모지 표정 tired face"},
	{Char: "🥱", Name: "하품하는 얼굴", Keywords: "이모지 표정 yawning face"},
	{Char: "😤", Name: "씩씩대는 얼굴", Keywords: "이모지 표정 face with steam"},
	{Char: "😡", Name: "화난 붉은 얼굴", Keywords: "이모지 표정 화 pouting face"},
	{Char: "😠", Name: "화난 얼굴", Keywords: "이모지 표정 화 angry face"},
	{Char: "🤬", Name: "욕하는 얼굴", Keywords: "이모지 표정 화 cursing face"},
	{Char: "😈", Name: "뿔 달린 웃는 얼굴", Keywords: "이모지 표정 devil smiling horns"},
	{Char: "👿", Name: "뿔 달린 화난 얼굴", Keywords: "이모지 표정 angry devil"},
	{Char: "💀", Name: "해골", Keywords: "이모지 죽음 skull"},
	{Char: "💩", Name: "똥", Keywords: "이모지 poop"},
	{Char: "🤡", Name: "광대", Keywords: "이모지 표정 clown face"},
	{Char: "👻", Name: "유령", Keywords: "이모지 ghost"},
	{Char: "👽", Name: "외계인", Keywords: "이모지 alien"},
	{Char: "🤖", Name: "로봇", Keywords: "이모지 robot", Aliases: "robot"},
	{Char: "😺", Name: "웃는 고양이", Keywords: "이모지 고양이 grinning cat"},
	{Char: "😻", Name: "하트 눈 고양이", Keywords: "이모지 고양이 heart eyes cat"},
	{Char: "😹", Name: "눈물 나게 웃는 고양이", Keywords: "이모지 고양이 cat tears of joy"},
	{Char: "🙀", Name: "놀란 고양이", Keywords: "이모지 고양이 weary cat"},
	{Char: "😿", Name: "우는 고양이", Keywords: "이모지 고양이 crying cat"},
	{Char: "🙈", Name: "눈 가린 원숭이", Keywords: "이모지 원숭이 see no evil monkey"},
	{Char: "🙉", Name: "귀 막은 원숭이", Keywords: "이모지 원숭이 hear no evil monkey"},
	{Char: "🙊", Name: "입 막은 원숭이", Keywords: "이모지 원숭이 speak no evil monkey"},

	// 이모지 손과 사람 (emoji hand and person)
	{Char: "👍", Name: "엄지척", Keywords: "이모지 손 좋아요 thumbs up", Aliases: "+1 thumbsup"},
	{Char: "👎", Name: "엄지 아래", Keywords: "이모지 손 싫어요 thumbs down", Aliases: "-1 thumbsdown"},
	{Char: "👌", Name: "오케이 손", Keywords: "이모지 손 ok hand", Aliases: "ok_hand ok"},
	{Char: "✌", Name: "브이", Keywords: "이모지 손 victory hand peace"},
	{Char: "🤞", Name: "행운을 비는 손", Keywords: "이모지 손 crossed fingers"},
	{Char: "🤟", Name: "사랑해 손", Keywords: "이모지 손 love you gesture"},
	{Char: "🤘", Name: "뿔 손", Keywords: "이모지 손 sign of the horns"},
	{Char: "🤙", Name: "전화해 손", Keywords: "이모지 손 call me hand"},
	{Char: "👈", Name: "왼쪽 가리키는 손", Keywords: "이모지 손 backhand index left"},
	{Char: "👉", Name: "오른쪽 가리키는 손", Keywords: "이모지 손 backhand index right"},
	{Char: "👆", Name: "위 가리키는 손", Keywords: "이모지 손 backhand index up"},
	{Char: "👇", Name: "아래 가리키는 손", Keywords: "이모지 손 backhand index down"},
	{Char: "✋", Name: "든 손", Keywords: "이모지 손 raised hand"},
	{Char: "🤚", Name: "손등", Keywords: "이모지 손 raised back of hand"},
	{Char: "🖐", Name: "손가락 편 손", Keywords: "이모지 손 hand with fingers splayed"},
	{Char: "🖖", Name: "벌칸 인사", Keywords: "이모지 손 vulcan salute"},
	{Char: "👋", Name: "흔드는 손", Keywords: "이모지 손 인사 waving hand"},
	{Char: "🤏", Name: "조금", Keywords: "이모지 손 pinching hand"},
	{Char: "✊", Name: "주먹", Keywords: "이모지 손 raised fist"},
	{Char: "👊", Name: "앞으로 내민 주먹", Keywords: "이모지 손 oncoming fist"},
	{Char: "🤛", Name: "왼쪽 주먹", Keywords: "이모지 손 left facing fist"},
	{Char: "🤜", Name: "오른쪽 주먹", Keywords: "이모지 손 right facing fist"},
	{Char: "👏", Name: "박수", Keywords: "이모지 손 clapping hands", Aliases: "clap"},
	{Char: "🙌", Name: "두 손 들기", Keywords: "이모지 손 raising hands", Aliases: "raised_hands"},
	{Char: "👐", Name: "벌린 두 손", Keywords: "이모지 손 open hands"},
	{Char: "🤲", Name: "받치는 두 손", Keywords: "이모지 손 palms up together"},
	{Char: "🤝", Name: "악수", Keywords: "이모지 손 handshake"},
	{Char: "🙏", Name: "기도하는 손", Keywords: "이모지 손 감사 folded hands please thanks", Aliases: "pray thanks"},
	{Char: "💅", Name: "매니큐어", Keywords: "이모지 손 nail polish"},
	{Char: "💪", Name: "알통", Keywords: "이모지 근육 flexed biceps muscle"},
	{Char: "👀", Name: "두 눈", Keywords: "이모지 눈 eyes", Aliases: "eyes"},
	{Char: "👁", Name: "눈", Keywords: "이모지 눈 eye"},
	{Char: "👂", Name: "귀", Keywords: "이모지 ear"},
	{Char: "👃", Name: "코", Keywords: "이모지 nose"},
	{Char: "👄", Name: "입술", Keywords: "이모지 mouth lips"},
	{Char: "👅", Name: "혀", Keywords: "이모지 tongue"},
	{Char: "🦷", Name: "이", Keywords: "이모지 tooth"},
	{Char: "🧠", Name: "뇌", Keywords: "이모지 brain"},
	{Char: "🦴", Name: "뼈", Keywords: "이모지 bone"},
	{Char: "👶", Name: "아기", Keywords: "이모지 사람 baby"},
	{Char: "🧒", Name: "아이", Keywords: "이모지 사람 child"},
	{Char: "👦", Name: "남자아이", Keywords: "이모지 사람 boy"},
	{Char: "👧", Name: "여자아이", Keywords: "이모지 사람 girl"},
	{Char: "🧑", Name: "사람", Keywords: "이모지 사람 person adult"},
	{Char: "👨", Name: "남자", Keywords: "이모지 사람 man"},
	{Char: "👩", Name: "여자", Keywords: "이모지 사람 woman"},
	{Char: "🧓", Name: "노인", Keywords: "이모지 사람 older person"},
	{Char: "👴", Name: "할아버지", Keywords: "이모지 사람 old man"},
	{Char: "👵", Name: "할머니", Keywords: "이모지 사람 old woman"},
	{Char: "🙋", Name: "손 든 사람", Keywords: "이모지 사람 person raising hand"},
	{Char: "🙇", Name: "절하는 사람", Keywords: "이모지 사람 person bowing"},
	{Char: "🤦", Name: "이마 짚는 사람", Keywords: "이모지 사람 person facepalming"},
	{Char: "🤷", Name: "어깨 으쓱", Keywords: "이모지 사람 person shrugging", Aliases: "shrug"},
	{Char: "💁", Name: "안내하는 사람", Keywords: "이모지 사람 person tipping hand"},
	{Char: "🙅", Name: "안 된다는 사람", Keywords: "이모지 사람 person gesturing no"},
	{Char: "🙆", Name: "된다는 사람", Keywords: "이모지 사람 person gesturing ok"},
	{Char: "🚶", Name: "걷는 사람", Keywords: "이모지 사람 person walking"},
	{Char: "🏃", Name: "달리는 사람", Keywords: "이모지 사람 person running"},
	{Char: "💃", Name: "춤추는 여자", Keywords: "이모지 사람 woman dancing"},
	{Char: "🕺", Name: "춤추는 남자", Keywords: "이모지 사람 man dancing"},
	{Char: "👮", Name: "경찰관", Keywords: "이모지 사람 police officer"},
	{Char: "👷", Name: "건설 노동자", Keywords: "이모지 사람 construction worker"},
	{Char: "💂", Name: "근위병", Keywords: "이모지 사람 guard"},
	{Char: "🕵", Name: "탐정", Keywords: "이모지 사람 detective"},
	{Char: "👨‍💻", Name: "개발자", Keywords: "이모지 사람 technologist developer programmer"},
	{Char: "👩‍💻", Name: "여성 개발자", Keywords: "이모지 사람 woman technologist developer"},
	{Char: "🧑‍🍳", Name: "요리사", Keywords: "이모지 사람 cook chef"},
	{Char: "🧑‍🎓", Name: "학생", Keywords: "이모지 사람 student"},
	{Char: "🧑‍🏫", Name: "선생님", Keywords: "이모지 사람 teacher"},
	{Char: "🧑‍⚕", Name: "의료인", Keywords: "이모지 사람 health worker doctor"},
	{Char: "🎅", Name: "산타클로스", Keywords: "이모지 사람 크리스마스 santa claus"},
	{Char: "🦸", Name: "슈퍼히어로", Keywords: "이모지 사람 superhero"},
	{Char: "🧙", Name: "마법사", Keywords: "이모지 사람 mage wizard"},
	{Char: "🧚", Name: "요정", Keywords: "이모지 사람 fairy"},
	{Char: "👯", Name: "토끼 귀 사람", Keywords: "이모지 사람 people with bunny ears"},
	{Char: "👪", Name: "가족", Keywords: "이모지 사람 family"},
	{Char: "👫", Name: "손잡은 남녀", Keywords: "이모지 사람 woman and man holding hands"},
	{Char: "💏", Name: "키스하는 사람들", Keywords: "이모지 사람 kiss"},
	{Char: "💑", Name: "사랑하는 사람들", Keywords: "이모지 사람 couple with heart"},
	{Char: "👤", Name: "실루엣", Keywords: "이모지 사람 bust in silhouette"},
	{Char: "👥", Name: "실루엣 둘", Keywords: "이모지 사람 busts in silhouette"},
	{Char: "🗣", Name: "말하는 얼굴", Keywords: "이모지 사람 speaking head"},
	{Char: "🦶", Name: "발", Keywords: "이모지 foot"},
	{Char: "🦵", Name: "다리", Keywords: "이모지 leg"},

	// 이모지 감정과 기호 (emoji heart and symbol)
	{Char: "❤", Name: "빨간 하트", Keywords: "이모지 하트 사랑 red heart", Aliases: "heart"},
	{Char: "🧡", Name: "주황 하트", Keywords: "이모지 하트 사랑 orange heart"},
	{Char: "💛", Name: "노란 하트", Keywords: "이모지 하트 사랑 yellow heart"},
	{Char: "💚", Name: "초록 하트", Keywords: "이모지 하트 사랑 green heart"},
	{Char: "💙", Name: "파란 하트", Keywords: "이모지 하트 사랑 blue heart"},
	{Char: "💜", Name: "보라 하트", Keywords: "이모지 하트 사랑 purple heart"},
	{Char: "🖤", Name: "검은 하트", Keywords: "이모지 하트 사랑 black heart"},
	{Char: "🤍", Name: "흰 하트", Keywords: "이모지 하트 사랑 white heart"},
	{Char: "🤎", Name: "갈색 하트", Keywords: "이모지 하트 사랑 brown heart"},
	{Char: "💔", Name: "깨진 하트", Keywords: "이모지 하트 이별 broken heart", Aliases: "broken_heart"},
	{Char: "❣", Name: "느낌표 하트", Keywords: "이모지 하트 heart exclamation"},
	{Char: "💕", Name: "하트 두 개", Keywords: "이모지 하트 사랑 two hearts"},
	{Char: "💞", Name: "도는 하트", Keywords: "이모지 하트 사랑 revolving hearts"},
	{Char: "💓", Name: "뛰는 하트", Keywords: "이모지 하트 사랑 beating heart"},
	{Char: "💗", Name: "커지는 하트", Keywords: "이모지 하트 사랑 growing heart"},
	{Char: "💖", Name: "반짝이는 하트", Keywords: "이모지 하트 사랑 sparkling heart"},
	{Char: "💘", Name: "화살 꽂힌 하트", Keywords: "이모지 하트 사랑 heart with arrow cupid"},
	{Char: "💝", Name: "리본 달린 하트", Keywords: "이모지 하트 선물 heart with ribbon"},
	{Char: "💟", Name: "하트 장식", Keywords: "이모지 하트 heart decoration"},
	{Char: "💌", Name: "연애편지", Keywords: "이모지 하트 love letter"},
	{Char: "💋", Name: "입술 자국", Keywords: "이모지 뽀뽀 kiss mark"},
	{Char: "💯", Name: "백점", Keywords: "이모지 hundred points", Aliases: "100"},
	{Char: "💢", Name: "분노 표시", Keywords: "이모지 화 anger symbol"},
	{Char: "💥", Name: "충돌", Keywords: "이모지 collision boom"},
	{Char: "💫", Name: "어지러움", Keywords: "이모지 별 dizzy star"},
	{Char: "💦", Name: "땀방울", Keywords: "이모지 땀 sweat droplets"},
	{Char: "💨", Name: "쌩", Keywords: "이모지 dashing away"},
	{Char: "🕳", Name: "구멍", Keywords: "이모지 hole"},
	{Char: "💣", Name: "폭탄", Keywords: "이모지 bomb"},
	{Char: "💬", Name: "말풍선", Keywords: "이모지 speech balloon"},
	{Char: "💭", Name: "생각 풍선", Keywords: "이모지 thought balloon"},
	{Char: "🗯", Name: "분노 풍선", Keywords: "이모지 right anger bubble"},
	{Char: "💤", Name: "잠", Keywords: "이모지 zzz sleep"},
	{Char: "🔥", Name: "불", Keywords: "이모지 fire", Aliases: "fire"},
	{Char: "⭐", Name: "별", Keywords: "이모지 별 star", Aliases: "star"},
	{Char: "🌟", Name: "반짝이는 별", Keywords: "이모지 별 glowing star"},
	{Char: "✅", Name: "초록 체크", Keywords: "이모지 체크 확인 check mark button", Aliases: "white_check_mark check"},
	{Char: "❌", Name: "엑스 표시", Keywords: "이모지 엑스 취소 cross mark", Aliases: "x cross"},
	{Char: "❎", Name: "엑스 상자", Keywords: "이모지 엑스 cross mark button"},
	{Char: "➕", Name: "더하기", Keywords: "이모지 plus"},
	{Char: "➖", Name: "빼기", Keywords: "이모지 minus"},
	{Char: "➗", Name: "나누기", Keywords: "이모지 divide"},
	{Char: "❓", Name: "물음표", Keywords: "이모지 question mark"},
	{Char: "❔", Name: "흰 물음표", Keywords: "이모지 white question mark"},
	{Char: "❗", Name: "느낌표", Keywords: "이모지 exclamation mark"},
	{Char: "❕", Name: "흰 느낌표", Keywords: "이모지 white exclamation mark"},
	{Char: "🚫", Name: "금지", Keywords: "이모지 prohibited no entry"},
	{Char: "⛔", Name: "진입 금지", Keywords: "이모지 no entry"},
	{Char: "💡", Name: "전구", Keywords: "이모지 아이디어 light bulb idea", Aliases: "bulb idea"},
	{Char: "🔔", Name: "종", Keywords: "이모지 알림 bell"},
	{Char: "🔕", Name: "종 금지", Keywords: "이모지 알림 bell with slash mute"},
	{Char: "📌", Name: "압정", Keywords: "이모지 pushpin", Aliases: "pushpin"},
	{Char: "📍", Name: "위치 핀", Keywords: "이모지 위치 round pushpin location"},
	{Char: "🔖", Name: "책갈피", Keywords: "이모지 bookmark"},
	{Char: "🏷", Name: "꼬리표", Keywords: "이모지 label tag"},
	{Char: "🔗", Name: "고리", Keywords: "이모지 링크 link", Aliases: "link"},
	{Char: "📎", Name: "클립", Keywords: "이모지 paperclip"},
	{Char: "🔒", Name: "잠김", Keywords: "이모지 locked", Aliases: "lock"},
	{Char: "🔓", Name: "열림", Keywords: "이모지 unlocked"},
	{Char: "🔑", Name: "열쇠", Keywords: "이모지 key"},
	{Char: "🔍", Name: "돋보기", Keywords: "이모지 검색 magnifying glass search"},
	{Char: "🔎", Name: "오른쪽 돋보기", Keywords: "이모지 검색 magnifying glass right"},
	{Char: "🔄", Name: "순환 화살표", Keywords: "이모지 새로고침 counterclockwise arrows refresh"},
	{Char: "🔁", Name: "반복", Keywords: "이모지 repeat"},
	{Char: "🔀", Name: "섞기", Keywords: "이모지 shuffle"},
	{Char: "🆗", Name: "오케이", Keywords: "이모지 ok button"},
	{Char: "🆕", Name: "새로움", Keywords: "이모지 new button"},
	{Char: "🆙", Name: "업", Keywords: "이모지 up button"},
	{Char: "🔝", Name: "맨 위", Keywords: "이모지 top arrow"},
	{Char: "🎉", Name: "크래커", Keywords: "이모지 축하 party popper", Aliases: "tada"},
	{Char: "🎊", Name: "색종이 공", Keywords: "이모지 축하 confetti ball"},
	{Char: "🎈", Name: "풍선", Keywords: "이모지 축하 balloon"},
	{Char: "🎁", Name: "선물", Keywords: "이모지 선물 gift"},
	{Char: "🏆", Name: "트로피", Keywords: "이모지 상 trophy"},
	{Char: "🥇", Name: "금메달", Keywords: "이모지 상 gold medal"},
	{Char: "🥈", Name: "은메달", Keywords: "이모지 상 silver medal"},
	{Char: "🥉", Name: "동메달", Keywords: "이모지 상 bronze medal"},
	{Char: "🎯", Name: "과녁", Keywords: "이모지 목표 direct hit target", Aliases: "dart"},
	{Char: "🚀", Name: "로켓", Keywords: "이모지 rocket", Aliases: "rocket"},
	{Char: "💎", Name: "보석", Keywords: "이모지 gem stone diamond"},
	{Char: "👑", Name: "왕관", Keywords: "이모지 crown"},

	// 이모지 동물과 자연 (emoji animal and nature)
	{Char: "🐶", Name: "강아지 얼굴", Keywords: "이모지 동물 개 dog face"},
	{Char: "🐕", Name: "개", Keywords: "이모지 동물 dog"},
	{Char: "🐱", Name: "고양이 얼굴", Keywords: "이모지 동물 고양이 cat face"},
	{Char: "🐈", Name: "고양이", Keywords: "이모지 동물 cat"},
	{Char: "🐭", Name: "쥐 얼굴", Keywords: "이모지 동물 mouse face"},
	{Char: "🐹", Name: "햄스터", Keywords: "이모지 동물 hamster"},
	{Char: "🐰", Name: "토끼 얼굴", Keywords: "이모지 동물 rabbit face"},
	{Char: "🦊", Name: "여우", Keywords: "이모지 동물 fox"},
	{Char: "🐻", Name: "곰", Keywords: "이모지 동물 bear"},
	{Char: "🐼", Name: "판다", Keywords: "이모지 동물 panda"},
	{Char: "🐨", Name: "코알라", Keywords: "이모지 동물 koala"},
	{Char: "🐯", Name: "호랑이 얼굴", Keywords: "이모지 동물 tiger face"},
	{Char: "🦁", Name: "사자", Keywords: "이모지 동물 lion"},
	{Char: "🐮", Name: "소 얼굴", Keywords: "이모지 동물 cow face"},
	{Char: "🐷", Name: "돼지 얼굴", Keywords: "이모지 동물 pig face"},
	{Char: "🐽", Name: "돼지 코", Keywords: "이모지 동물 pig nose"},
	{Char: "🐸", Name: "개구리", Keywords: "이모지 동물 frog"},
	{Char: "🐵", Name: "원숭이 얼굴", Keywords: "이모지 동물 monkey face"},
	{Char: "🐒", Name: "원숭이", Keywords: "이모지 동물 monkey"},
	{Char: "🐔", Name: "닭", Keywords: "이모지 동물 chicken"},
	{Char: "🐧", Name: "펭귄", Keywords: "이모지 동물 penguin"},
	{Char: "🐦", Name: "새", Keywords: "이모지 동물 bird"},
	{Char: "🐤", Name: "병아리", Keywords: "이모지 동물 baby chick"},
	{Char: "🦆", Name: "오리", Keywords: "이모지 동물 duck"},
	{Char: "🦅", Name: "독수리", Keywords: "이모지 동물 eagle"},
	{Char: "🦉", Name: "올빼미", Keywords: "이모지 동물 owl"},
	{Char: "🦇", Name: "박쥐", Keywords: "이모지 동물 bat"},
	{Char: "🐺", Name: "늑대", Keywords: "이모지 동물 wolf"},
	{Char: "🐗", Name: "멧돼지", Keywords: "이모지 동물 boar"},
	{Char: "🐴", Name: "말 얼굴", Keywords: "이모지 동물 horse face"},
	{Char: "🦄", Name: "유니콘", Keywords: "이모지 동물 unicorn"},
	{Char: "🐝", Name: "꿀벌", Keywords: "이모지 동물 honeybee"},
	{Char: "🐛", Name: "애벌레", Keywords: "이모지 동물 bug caterpillar", Aliases: "bug"},
	{Char: "🦋", Name: "나비", Keywords: "이모지 동물 butterfly"},
	{Char: "🐌", Name: "달팽이", Keywords: "이모지 동물 snail"},
	{Char: "🐞", Name: "무당벌레", Keywords: "이모지 동물 lady beetle"},
	{Char: "🐜", Name: "개미", Keywords: "이모지 동물 ant"},
	{Char: "🕷", Name: "거미", Keywords: "이모지 동물 spider"},
	{Char: "🕸", Name: "거미줄", Keywords: "이모지 spider web"},
	{Char: "🦂", Name: "전갈", Keywords: "이모지 동물 scorpion"},
	{Char: "🐢", Name: "거북", Keywords: "이모지 동물 turtle"},
	{Char: "🐍", Name: "뱀", Keywords: "이모지 동물 snake"},
	{Char: "🦎", Name: "도마뱀", Keywords: "이모지 동물 lizard"},
	{Char: "🐙", Name: "문어", Keywords: "이모지 동물 octopus"},
	{Char: "🦑", Name: "오징어", Keywords: "이모지 동물 squid"},
	{Char: "🦐", Name: "새우", Keywords: "이모지 동물 shrimp"},
	{Char: "🦀", Name: "게", Keywords: "이모지 동물 crab"},
	{Char: "🐡", Name: "복어", Keywords: "이모지 동물 blowfish"},
	{Char: "🐠", Name: "열대어", Keywords: "이모지 동물 tropical fish"},
	{Char: "🐟", Name: "물고기", Keywords: "이모지 동물 fish"},
	{Char: "🐬", Name: "돌고래", Keywords: "이모지 동물 dolphin"},
	{Char: "🐳", Name: "고래", Keywords: "이모지 동물 whale"},
	{Char: "🦈", Name: "상어", Keywords: "이모지 동물 shark"},
	{Char: "🐊", Name: "악어", Keywords: "이모지 동물 crocodile"},
	{Char: "🐘", Name: "코끼리", Keywords: "이모지 동물 elephant"},
	{Char: "🦏", Name: "코뿔소", Keywords: "이모지 동물 rhinoceros"},
	{Char: "🐪", Name: "낙타", Keywords: "이모지 동물 camel"},
	{Char: "🦒", Name: "기린", Keywords: "이모지 동물 giraffe"},
	{Char: "🐇", Name: "토끼", Keywords: "이모지 동물 rabbit"},
	{Char: "🐿", Name: "다람쥐", Keywords: "이모지 동물 chipmunk"},
	{Char: "🦔", Name: "고슴도치", Keywords: "이모지 동물 hedgehog"},
	{Char: "🐾", Name: "발자국", Keywords: "이모지 동물 paw prints"},
	{Char: "🌸", Name: "벚꽃", Keywords: "이모지 꽃 cherry blossom"},
	{Char: "💮", Name: "흰 꽃", Keywords: "이모지 꽃 white flower"},
	{Char: "🌹", Name: "장미", Keywords: "이모지 꽃 rose"},
	{Char: "🥀", Name: "시든 꽃", Keywords: "이모지 꽃 wilted flower"},
	{Char: "🌺", Name: "무궁화", Keywords: "이모지 꽃 hibiscus"},
	{Char: "🌻", Name: "해바라기", Keywords: "이모지 꽃 sunflower"},
	{Char: "🌼", Name: "블로섬", Keywords: "이모지 꽃 blossom"},
	{Char: "🌷", Name: "튤립", Keywords: "이모지 꽃 tulip"},
	{Char: "🌱", Name: "새싹", Keywords: "이모지 식물 seedling"},
	{Char: "🌲", Name: "침엽수", Keywords: "이모지 나무 evergreen tree"},
	{Char: "🌳", Name: "활엽수", Keywords: "이모지 나무 deciduous tree"},
	{Char: "🌴", Name: "야자수", Keywords: "이모지 나무 palm tree"},
	{Char: "🌵", Name: "선인장", Keywords: "이모지 식물 cactus"},
	{Char: "🍀", Name: "네잎클로버", Keywords: "이모지 행운 four leaf clover"},
	{Char: "🍁", Name: "단풍잎", Keywords: "이모지 잎 maple leaf"},
	{Char: "🍂", Name: "낙엽", Keywords: "이모지 잎 fallen leaf"},
	{Char: "🍃", Name: "바람에 날리는 잎", Keywords: "이모지 잎 leaf fluttering"},
	{Char: "🌾", Name: "벼", Keywords: "이모지 식물 sheaf of rice"},
	{Char: "🌍", Name: "지구 유럽아프리카", Keywords: "이모지 지구 globe europe africa"},
	{Char: "🌏", Name: "지구 아시아", Keywords: "이모지 지구 globe asia australia"},
	{Char: "🌎", Name: "지구 아메리카", Keywords: "이모지 지구 globe americas"},
	{Char: "🌕", Name: "보름달", Keywords: "이모지 달 full moon"},
	{Char: "🌑", Name: "삭", Keywords: "이모지 달 new moon"},
	{Char: "🌙", Name: "초승달", Keywords: "이모지 달 crescent moon"},
	{Char: "🌛", Name: "웃는 상현달", Keywords: "이모지 달 first quarter moon face"},
	{Char: "🌞", Name: "웃는 해", Keywords: "이모지 날씨 sun with face"},
	{Char: "⛅", Name: "구름 낀 해", Keywords: "이모지 날씨 sun behind cloud"},
	{Char: "🌧", Name: "비 오는 구름", Keywords: "이모지 날씨 비 cloud with rain"},
	{Char: "⛈", Name: "번개 치는 구름", Keywords: "이모지 날씨 cloud with lightning rain"},
	{Char: "🌩", Name: "번개", Keywords: "이모지 날씨 cloud with lightning"},
	{Char: "⛄", Name: "눈사람 없는 눈", Keywords: "이모지 날씨 눈 snowman without snow"},
	{Char: "🌈", Name: "무지개", Keywords: "이모지 날씨 rainbow"},
	{Char: "🌊", Name: "파도", Keywords: "이모지 물 water wave"},
	{Char: "💧", Name: "물방울", Keywords: "이모지 물 droplet"},
	{Char: "🌋", Name: "화산", Keywords: "이모지 자연 volcano"},
	{Char: "⛰", Name: "산", Keywords: "이모지 자연 mountain"},
	{Char: "🏔", Name: "눈 덮인 산", Keywords: "이모지 자연 snow capped mountain"},
	{Char: "🌅", Name: "일출", Keywords: "이모지 자연 sunrise"},
	{Char: "🌄", Name: "산 위 일출", Keywords: "이모지 자연 sunrise over mountains"},
	{Char: "🌇", Name: "일몰", Keywords: "이모지 자연 sunset"},
	{Char: "🌌", Name: "은하수", Keywords: "이모지 자연 milky way"},

	// 이모지 음식 (emoji food)
	{Char: "🍎", Name: "빨간 사과", Keywords: "이모지 음식 과일 red apple"},
	{Char: "🍏", Name: "초록 사과", Keywords: "이모지 음식 과일 green apple"},
	{Char: "🍐", Name: "배", Keywords: "이모지 음식 과일 pear"},
	{Char: "🍊", Name: "귤", Keywords: "이모지 음식 과일 tangerine orange"},
	{Char: "🍋", Name: "레몬", Keywords: "이모지 음식 과일 lemon"},
	{Char: "🍌", Name: "바나나", Keywords: "이모지 음식 과일 banana"},
	{Char: "🍉", Name: "수박", Keywords: "이모지 음식 과일 watermelon"},
	{Char: "🍇", Name: "포도", Keywords: "이모지 음식 과일 grapes"},
	{Char: "🍓", Name: "딸기", Keywords: "이모지 음식 과일 strawberry"},
	{Char: "🍑", Name: "복숭아", Keywords: "이모지 음식 과일 peach"},
	{Char: "🍒", Name: "체리", Keywords: "이모지 음식 과일 cherries"},
	{Char: "🥝", Name: "키위", Keywords: "이모지 음식 과일 kiwi"},
	{Char: "🍍", Name: "파인애플", Keywords: "이모지 음식 과일 pineapple"},
	{Char: "🥥", Name: "코코넛", Keywords: "이모지 음식 과일 coconut"},
	{Char: "🥑", Name: "아보카도", Keywords: "이모지 음식 avocado"},
	{Char: "🍅", Name: "토마토", Keywords: "이모지 음식 tomato"},
	{Char: "🍆", Name: "가지", Keywords: "이모지 음식 eggplant"},
	{Char: "🥕", Name: "당근", Keywords: "이모지 음식 carrot"},
	{Char: "🌽", Name: "옥수수", Keywords: "이모지 음식 corn"},
	{Char: "🌶", Name: "고추", Keywords: "이모지 음식 hot pepper"},
	{Char: "🥔", Name: "감자", Keywords: "이모지 음식 potato"},
	{Char: "🍠", Name: "고구마", Keywords: "이모지 음식 roasted sweet potato"},
	{Char: "🧄", Name: "마늘", Keywords: "이모지 음식 garlic"},
	{Char: "🧅", Name: "양파", Keywords: "이모지 음식 onion"},
	{Char: "🥦", Name: "브로콜리", Keywords: "이모지 음식 broccoli"},
	{Char: "🍄", Name: "버섯", Keywords: "이모지 음식 mushroom"},
	{Char: "🥜", Name: "땅콩", Keywords: "이모지 음식 peanuts"},
	{Char: "🌰", Name: "밤", Keywords: "이모지 음식 chestnut"},
	{Char: "🍞", Name: "식빵", Keywords: "이모지 음식 bread"},
	{Char: "🥐", Name: "크루아상", Keywords: "이모지 음식 croissant"},
	{Char: "🥖", Name: "바게트", Keywords: "이모지 음식 baguette"},
	{Char: "🥨", Name: "프레첼", Keywords: "이모지 음식 pretzel"},
	{Char: "🧀", Name: "치즈", Keywords: "이모지 음식 cheese"},
	{Char: "🥚", Name: "달걀", Keywords: "이모지 음식 egg"},
	{Char: "🍳", Name: "달걀 프라이", Keywords: "이모지 음식 cooking fried egg"},
	{Char: "🥞", Name: "팬케이크", Keywords: "이모지 음식 pancakes"},
	{Char: "🥓", Name: "베이컨", Keywords: "이모지 음식 bacon"},
	{Char: "🍔", Name: "햄버거", Keywords: "이모지 음식 hamburger"},
	{Char: "🍟", Name: "감자튀김", Keywords: "이모지 음식 french fries"},
	{Char: "🍕", Name: "피자", Keywords: "이모지 음식 pizza"},
	{Char: "🌭", Name: "핫도그", Keywords: "이모지 음식 hot dog"},
	{Char: "🥪", Name: "샌드위치", Keywords: "이모지 음식 sandwich"},
	{Char: "🌮", Name: "타코", Keywords: "이모지 음식 taco"},
	{Char: "🌯", Name: "부리토", Keywords: "이모지 음식 burrito"},
	{Char: "🥗", Name: "샐러드", Keywords: "이모지 음식 green salad"},
	{Char: "🍝", Name: "스파게티", Keywords: "이모지 음식 spaghetti"},
	{Char: "🍜", Name: "라면", Keywords: "이모지 음식 steaming bowl ramen"},
	{Char: "🍲", Name: "전골", Keywords: "이모지 음식 pot of food"},
	{Char: "🍛", Name: "카레", Keywords: "이모지 음식 curry rice"},
	{Char: "🍚", Name: "밥", Keywords: "이모지 음식 cooked rice"},
	{Char: "🍙", Name: "주먹밥", Keywords: "이모지 음식 rice ball"},
	{Char: "🍘", Name: "전병", Keywords: "이모지 음식 rice cracker"},
	{Char: "🍢", Name: "어묵꼬치", Keywords: "이모지 음식 oden"},
	{Char: "🍡", Name: "경단", Keywords: "이모지 음식 dango"},
	{Char: "🍣", Name: "초밥", Keywords: "이모지 음식 sushi"},
	{Char: "🍤", Name: "새우튀김", Keywords: "이모지 음식 fried shrimp"},
	{Char: "🍥", Name: "어묵", Keywords: "이모지 음식 fish cake"},
	{Char: "🥟", Name: "만두", Keywords: "이모지 음식 dumpling"},
	{Char: "🍦", Name: "소프트 아이스크림", Keywords: "이모지 음식 soft ice cream"},
	{Char: "🍨", Name: "아이스크림", Keywords: "이모지 음식 ice cream"},
	{Char: "🍧", Name: "빙수", Keywords: "이모지 음식 shaved ice"},
	{Char: "🍩", Name: "도넛", Keywords: "이모지 음식 doughnut"},
	{Char: "🍪", Name: "쿠키", Keywords: "이모지 음식 cookie"},
	{Char: "🎂", Name: "생일 케이크", Keywords: "이모지 음식 birthday cake"},
	{Char: "🍰", Name: "조각 케이크", Keywords: "이모지 음식 shortcake"},
	{Char: "🧁", Name: "컵케이크", Keywords: "이모지 음식 cupcake"},
	{Char: "🍫", Name: "초콜릿", Keywords: "이모지 음식 chocolate bar"},
	{Char: "🍬", Name: "사탕", Keywords: "이모지 음식 candy"},
	{Char: "🍭", Name: "막대사탕", Keywords: "이모지 음식 lollipop"},
	{Char: "🍮", Name: "푸딩", Keywords: "이모지 음식 custard pudding"},
	{Char: "🍯", Name: "꿀", Keywords: "이모지 음식 honey pot"},
	{Char: "🥛", Name: "우유", Keywords: "이모지 음료 glass of milk"},
	{Char: "🍵", Name: "녹차", Keywords: "이모지 음료 teacup"},
	{Char: "🍶", Name: "사케", Keywords: "이모지 음료 sake"},
	{Char: "🍺", Name: "맥주", Keywords: "이모지 음료 beer mug"},
	{Char: "🍻", Name: "맥주 건배", Keywords: "이모지 음료 clinking beer mugs"},
	{Char: "🥂", Name: "샴페인 건배", Keywords: "이모지 음료 clinking glasses"},
	{Char: "🍷", Name: "와인", Keywords: "이모지 음료 wine glass"},
	{Char: "🥃", Name: "위스키", Keywords: "이모지 음료 tumbler glass"},
	{Char: "🍸", Name: "칵테일", Keywords: "이모지 음료 cocktail glass"},
	{Char: "🍹", Name: "트로피컬 음료", Keywords: "이모지 음료 tropical drink"},
	{Char: "🍾", Name: "샴페인", Keywords: "이모지 음료 bottle with popping cork"},
	{Char: "🧊", Name: "얼음", Keywords: "이모지 음료 ice"},
	{Char: "🥄", Name: "숟가락", Keywords: "이모지 식기 spoon"},
	{Char: "🍴", Name: "포크와 나이프", Keywords: "이모지 식기 fork and knife"},
	{Char: "🍽", Name: "접시와 식기", Keywords: "이모지 식기 plate with cutlery"},
	{Char: "🥢", Name: "젓가락", Keywords: "이모지 식기 chopsticks"},

	// 이모지 사물과 활동 (emoji object and activity)
	{Char: "💻", Name: "노트북", Keywords: "이모지 컴퓨터 laptop"},
	{Char: "🖥", Name: "데스크톱", Keywords: "이모지 컴퓨터 desktop computer"},
	{Char: "🖨", Name: "프린터", Keywords: "이모지 printer"},
	{Char: "⌨", Name: "키보드", Keywords: "이모지 keyboard"},
	{Char: "🖱", Name: "마우스", Keywords: "이모지 computer mouse"},
	{Char: "💾", Name: "플로피 디스크", Keywords: "이모지 저장 floppy disk save"},
	{Char: "💿", Name: "시디", Keywords: "이모지 optical disk cd"},
	{Char: "📀", Name: "디비디", Keywords: "이모지 dvd"},
	{Char: "💽", Name: "미니 디스크", Keywords: "이모지 computer disk"},
	{Char: "📱", Name: "휴대전화", Keywords: "이모지 mobile phone"},
	{Char: "📲", Name: "전화 오는 휴대전화", Keywords: "이모지 mobile phone with arrow"},
	{Char: "📞", Name: "수화기", Keywords: "이모지 telephone receiver"},
	{Char: "📟", Name: "호출기", Keywords: "이모지 pager"},
	{Char: "📠", Name: "팩스", Keywords: "이모지 fax machine"},
	{Char: "🔋", Name: "배터리", Keywords: "이모지 battery"},
	{Char: "🔌", Name: "플러그", Keywords: "이모지 electric plug"},
	{Char: "🔦", Name: "손전등", Keywords: "이모지 flashlight"},
	{Char: "📷", Name: "사진기", Keywords: "이모지 camera"},
	{Char: "📸", Name: "플래시 사진기", Keywords: "이모지 camera with flash"},
	{Char: "📹", Name: "비디오 카메라", Keywords: "이모지 video camera"},
	{Char: "🎥", Name: "영화 카메라", Keywords: "이모지 movie camera"},
	{Char: "📺", Name: "텔레비전", Keywords: "이모지 television"},
	{Char: "📻", Name: "라디오", Keywords: "이모지 radio"},
	{Char: "🎙", Name: "마이크", Keywords: "이모지 studio microphone"},
	{Char: "🎤", Name: "노래 마이크", Keywords: "이모지 microphone"},
	{Char: "🎧", Name: "헤드폰", Keywords: "이모지 headphone"},
	{Char: "🎵", Name: "음표", Keywords: "이모지 음악 musical note"},
	{Char: "🎶", Name: "여러 음표", Keywords: "이모지 음악 musical notes"},
	{Char: "🎼", Name: "악보", Keywords: "이모지 음악 musical score"},
	{Char: "🎹", Name: "건반", Keywords: "이모지 음악 musical keyboard piano"},
	{Char: "🎸", Name: "기타", Keywords: "이모지 음악 guitar"},
	{Char: "🥁", Name: "드럼", Keywords: "이모지 음악 drum"},
	{Char: "🎺", Name: "트럼펫", Keywords: "이모지 음악 trumpet"},
	{Char: "🎻", Name: "바이올린", Keywords: "이모지 음악 violin"},
	{Char: "📖", Name: "펼친 책", Keywords: "이모지 책 open book"},
	{Char: "📚", Name: "책 여러 권", Keywords: "이모지 책 books"},
	{Char: "📕", Name: "닫힌 책", Keywords: "이모지 책 closed book"},
	{Char: "📓", Name: "공책", Keywords: "이모지 책 notebook"},
	{Char: "📔", Name: "장식 공책", Keywords: "이모지 책 notebook with cover"},
	{Char: "📒", Name: "장부", Keywords: "이모지 책 ledger"},
	{Char: "📃", Name: "말린 문서", Keywords: "이모지 문서 page with curl"},
	{Char: "📄", Name: "문서", Keywords: "이모지 문서 page facing up"},
	{Char: "📑", Name: "책갈피 탭", Keywords: "이모지 문서 bookmark tabs"},
	{Char: "📊", Name: "막대 그래프", Keywords: "이모지 그래프 bar chart"},
	{Char: "📈", Name: "오름 그래프", Keywords: "이모지 그래프 chart increasing"},
	{Char: "📉", Name: "내림 그래프", Keywords: "이모지 그래프 chart decreasing"},
	{Char: "📋", Name: "클립보드", Keywords: "이모지 clipboard"},
	{Char: "📁", Name: "폴더", Keywords: "이모지 file folder"},
	{Char: "📂", Name: "열린 폴더", Keywords: "이모지 open file folder"},
	{Char: "🗂", Name: "분류 폴더", Keywords: "이모지 card index dividers"},
	{Char: "🗃", Name: "서류함", Keywords: "이모지 card file box"},
	{Char: "🗄", Name: "캐비닛", Keywords: "이모지 file cabinet"},
	{Char: "🗑", Name: "휴지통", Keywords: "이모지 삭제 wastebasket trash"},
	{Char: "🖊", Name: "볼펜", Keywords: "이모지 pen"},
	{Char: "🖋", Name: "만년필", Keywords: "이모지 fountain pen"},
	{Char: "🖌", Name: "붓", Keywords: "이모지 paintbrush"},
	{Char: "🖍", Name: "크레용", Keywords: "이모지 crayon"},
	{Char: "📝", Name: "메모", Keywords: "이모지 memo writing", Aliases: "memo"},
	{Char: "📐", Name: "삼각자", Keywords: "이모지 triangular ruler"},
	{Char: "📏", Name: "직선자", Keywords: "이모지 straight ruler"},
	{Char: "🔨", Name: "망치", Keywords: "이모지 도구 hammer"},
	{Char: "🔧", Name: "렌치", Keywords: "이모지 도구 wrench"},
	{Char: "🔩", Name: "나사", Keywords: "이모지 도구 nut and bolt"},
	{Char: "🧰", Name: "공구함", Keywords: "이모지 도구 toolbox"},
	{Char: "🪛", Name: "드라이버", Keywords: "이모지 도구 screwdriver"},
	{Char: "⛏", Name: "곡괭이", Keywords: "이모지 도구 pick"},
	{Char: "🧲", Name: "자석", Keywords: "이모지 magnet"},
	{Char: "🧪", Name: "시험관", Keywords: "이모지 과학 test tube"},
	{Char: "🔬", Name: "현미경", Keywords: "이모지 과학 microscope"},
	{Char: "🔭", Name: "망원경", Keywords: "이모지 과학 telescope"},
	{Char: "💉", Name: "주사기", Keywords: "이모지 의료 syringe"},
	{Char: "💊", Name: "알약", Keywords: "이모지 의료 pill"},
	{Char: "🩹", Name: "반창고", Keywords: "이모지 의료 adhesive bandage"},
	{Char: "🛏", Name: "침대", Keywords: "이모지 bed"},
	{Char: "🚪", Name: "문", Keywords: "이모지 door"},
	{Char: "🪟", Name: "창문", Keywords: "이모지 window"},
	{Char: "🧹", Name: "빗자루", Keywords: "이모지 broom"},
	{Char: "🧺", Name: "바구니", Keywords: "이모지 basket"},
	{Char: "💰", Name: "돈주머니", Keywords: "이모지 돈 money bag"},
	{Char: "💵", Name: "달러 지폐", Keywords: "이모지 돈 dollar banknote"},
	{Char: "💳", Name: "신용카드", Keywords: "이모지 돈 credit card"},
	{Char: "🧾", Name: "영수증", Keywords: "이모지 돈 receipt"},
	{Char: "📦", Name: "상자", Keywords: "이모지 package box"},
	{Char: "📮", Name: "우체통", Keywords: "이모지 postbox"},
	{Char: "📧", Name: "이메일", Keywords: "이모지 메일 e-mail"},
	{Char: "📨", Name: "받은 편지", Keywords: "이모지 메일 incoming envelope"},
	{Char: "📩", Name: "보낸 편지", Keywords: "이모지 메일 envelope with arrow"},
	{Char: "🔐", Name: "잠긴 자물쇠와 열쇠", Keywords: "이모지 보안 locked with key"},
	{Char: "🛡", Name: "방패", Keywords: "이모지 보안 shield"},
	{Char: "⚽", Name: "축구공", Keywords: "이모지 운동 soccer ball"},
	{Char: "🏀", Name: "농구공", Keywords: "이모지 운동 basketball"},
	{Char: "⚾", Name: "야구공", Keywords: "이모지 운동 baseball"},
	{Char: "🎾", Name: "테니스공", Keywords: "이모지 운동 tennis"},
	{Char: "🏐", Name: "배구공", Keywords: "이모지 운동 volleyball"},
	{Char: "🏈", Name: "미식축구공", Keywords: "이모지 운동 american football"},
	{Char: "🎱", Name: "당구공", Keywords: "이모지 운동 pool 8 ball"},
	{Char: "🏓", Name: "탁구", Keywords: "이모지 운동 ping pong"},
	{Char: "🏸", Name: "배드민턴", Keywords: "이모지 운동 badminton"},
	{Char: "🥊", Name: "권투 글러브", Keywords: "이모지 운동 boxing glove"},
	{Char: "🎮", Name: "게임 패드", Keywords: "이모지 게임 video game"},
	{Char: "🕹", Name: "조이스틱", Keywords: "이모지 게임 joystick"},
	{Char: "🎲", Name: "주사위", Keywords: "이모지 게임 game die"},
	{Char: "🧩", Name: "퍼즐", Keywords: "이모지 게임 puzzle piece"},
	{Char: "♟", Name: "체스 폰", Keywords: "이모지 게임 chess pawn"},
	{Char: "🎬", Name: "슬레이트", Keywords: "이모지 영화 clapper board"},
	{Char: "🎭", Name: "가면", Keywords: "이모지 예술 performing arts"},
	{Char: "🎨", Name: "팔레트", Keywords: "이모지 예술 artist palette"},
	{Char: "🚗", Name: "자동차", Keywords: "이모지 교통 car"},
	{Char: "🚕", Name: "택시", Keywords: "이모지 교통 taxi"},
	{Char: "🚌", Name: "버스", Keywords: "이모지 교통 bus"},
	{Char: "🚑", Name: "구급차", Keywords: "이모지 교통 ambulance"},
	{Char: "🚒", Name: "소방차", Keywords: "이모지 교통 fire engine"},
	{Char: "🚲", Name: "자전거", Keywords: "이모지 교통 bicycle"},
	{Char: "🛴", Name: "킥보드", Keywords: "이모지 교통 kick scooter"},
	{Char: "🏍", Name: "오토바이", Keywords: "이모지 교통 motorcycle"},
	{Char: "🚂", Name: "기관차", Keywords: "이모지 교통 locomotive"},
	{Char: "🚆", Name: "기차", Keywords: "이모지 교통 train"},
	{Char: "🚇", Name: "지하철", Keywords: "이모지 교통 metro"},
	{Char: "🚁", Name: "헬리콥터", Keywords: "이모지 교통 helicopter"},
	{Char: "🚢", Name: "배", Keywords: "이모지 교통 ship"},
	{Char: "⛵", Name: "돛단배", Keywords: "이모지 교통 sailboat"},
	{Char: "🚦", Name: "신호등", Keywords: "이모지 교통 traffic light"},
	{Char: "🏠", Name: "집", Keywords: "이모지 장소 house"},
	{Char: "🏢", Name: "건물", Keywords: "이모지 장소 office building"},
	{Char: "🏫", Name: "학교", Keywords: "이모지 장소 school"},
	{Char: "🏥", Name: "병원", Keywords: "이모지 장소 hospital"},
	{Char: "🏦", Name: "은행", Keywords: "이모지 장소 bank"},
	{Char: "🏪", Name: "편의점", Keywords: "이모지 장소 convenience store"},
	{Char: "⛺", Name: "텐트", Keywords: "이모지 장소 tent"},
	{Char: "🗺", Name: "지도", Keywords: "이모지 장소 world map"},
	{Char: "🧭", Name: "나침반", Keywords: "이모지 장소 compass"},
	{Char: "🕐", Name: "한 시", Keywords: "이모지 시계 one o clock"},
	{Char: "📅", Name: "달력", Keywords: "이모지 날짜 calendar"},
	{Char: "📆", Name: "찢는 달력", Keywords: "이모지 날짜 tear off calendar"},
}
