package core

// 특수문자 drawer 가 먼저 보여주는 글자 표다. 한국어 이름으로 찾을 수 있는 것이 여기까지다
// (ADR-0056).
//
// 유니코드 공식 이름은 영문뿐이라(`BLACK UP-POINTING TRIANGLE`) `삼각형` 으로는 걸리지
// 않는다. 그래서 자주 쓰는 것만 손으로 적는다. 여기 없는 글자도 목록에는 있지만 영문
// 이름으로만 찾을 수 있다(symbol.go 의 indexSymbols).
//
// **새 글자는 이 표에 한 줄이 는다.** paletteCommands 와 같은 방식이다(palette.go).
// 갈래는 눈으로 찾기 위한 주석일 뿐이고 코드가 읽지 않는다 — 걸러내는 것은 이름과 keywords 다.
//
// 보이지 않는 글자(`NO-BREAK SPACE`·`ZERO WIDTH SPACE`) 는 넣지 않았다. 격자에서 빈 칸으로
// 보여 서로 구별되지 않는다. 영문 이름으로는 그대로 찾을 수 있다.
var curatedSymbols = []symbol{
	// 화살표 (arrow)
	{char: "←", name: "왼쪽 화살표", keywords: "화살표 arrow left"},
	{char: "→", name: "오른쪽 화살표", keywords: "화살표 arrow right"},
	{char: "↑", name: "위쪽 화살표", keywords: "화살표 arrow up"},
	{char: "↓", name: "아래쪽 화살표", keywords: "화살표 arrow down"},
	{char: "↔", name: "좌우 화살표", keywords: "화살표 arrow left right"},
	{char: "↕", name: "위아래 화살표", keywords: "화살표 arrow up down"},
	{char: "↖", name: "왼쪽 위 화살표", keywords: "화살표 arrow upper left"},
	{char: "↗", name: "오른쪽 위 화살표", keywords: "화살표 arrow upper right"},
	{char: "↘", name: "오른쪽 아래 화살표", keywords: "화살표 arrow lower right"},
	{char: "↙", name: "왼쪽 아래 화살표", keywords: "화살표 arrow lower left"},
	{char: "↚", name: "왼쪽 화살표 부정", keywords: "화살표 arrow left not"},
	{char: "↛", name: "오른쪽 화살표 부정", keywords: "화살표 arrow right not"},
	{char: "↝", name: "물결 오른쪽 화살표", keywords: "화살표 물결 arrow squiggle right"},
	{char: "↞", name: "왼쪽 두겹 머리 화살표", keywords: "화살표 arrow left two head"},
	{char: "↠", name: "오른쪽 두겹 머리 화살표", keywords: "화살표 arrow right two head"},
	{char: "↢", name: "왼쪽 꼬리 화살표", keywords: "화살표 arrow left tail"},
	{char: "↣", name: "오른쪽 꼬리 화살표", keywords: "화살표 arrow right tail"},
	{char: "↦", name: "오른쪽 막대 화살표", keywords: "화살표 arrow maps to"},
	{char: "↩", name: "왼쪽 갈고리 화살표", keywords: "화살표 arrow hook left"},
	{char: "↪", name: "오른쪽 갈고리 화살표", keywords: "화살표 arrow hook right"},
	{char: "↰", name: "위에서 왼쪽 화살표", keywords: "화살표 arrow up left"},
	{char: "↱", name: "위에서 오른쪽 화살표", keywords: "화살표 arrow up right"},
	{char: "↲", name: "아래에서 왼쪽 화살표", keywords: "화살표 arrow down left"},
	{char: "↳", name: "아래에서 오른쪽 화살표", keywords: "화살표 arrow down right"},
	{char: "↵", name: "줄바꿈 화살표", keywords: "화살표 엔터 arrow return enter newline"},
	{char: "↶", name: "반시계 반원 화살표", keywords: "화살표 되돌리기 arrow undo anticlockwise"},
	{char: "↷", name: "시계 반원 화살표", keywords: "화살표 다시하기 arrow redo clockwise"},
	{char: "↺", name: "반시계 열린 원 화살표", keywords: "화살표 회전 arrow rotate anticlockwise"},
	{char: "↻", name: "시계 열린 원 화살표", keywords: "화살표 회전 arrow rotate clockwise"},
	{char: "↼", name: "왼쪽 위 갈래 화살표", keywords: "화살표 arrow harpoon left up"},
	{char: "⇀", name: "오른쪽 위 갈래 화살표", keywords: "화살표 arrow harpoon right up"},
	{char: "⇄", name: "오른쪽 왼쪽 화살표", keywords: "화살표 교환 arrow swap right left"},
	{char: "⇅", name: "위아래 나란한 화살표", keywords: "화살표 arrow up down pair"},
	{char: "⇆", name: "왼쪽 오른쪽 화살표", keywords: "화살표 교환 arrow swap left right"},
	{char: "⇇", name: "왼쪽 겹 화살표", keywords: "화살표 arrow left pair"},
	{char: "⇉", name: "오른쪽 겹 화살표", keywords: "화살표 arrow right pair"},
	{char: "⇐", name: "왼쪽 두 줄 화살표", keywords: "화살표 arrow double left"},
	{char: "⇑", name: "위쪽 두 줄 화살표", keywords: "화살표 arrow double up"},
	{char: "⇒", name: "오른쪽 두 줄 화살표", keywords: "화살표 함의 arrow double right implies"},
	{char: "⇓", name: "아래쪽 두 줄 화살표", keywords: "화살표 arrow double down"},
	{char: "⇔", name: "좌우 두 줄 화살표", keywords: "화살표 동치 arrow double left right iff"},
	{char: "⇕", name: "위아래 두 줄 화살표", keywords: "화살표 arrow double up down"},
	{char: "⇠", name: "왼쪽 점선 화살표", keywords: "화살표 점선 arrow dashed left"},
	{char: "⇡", name: "위쪽 점선 화살표", keywords: "화살표 점선 arrow dashed up"},
	{char: "⇢", name: "오른쪽 점선 화살표", keywords: "화살표 점선 arrow dashed right"},
	{char: "⇣", name: "아래쪽 점선 화살표", keywords: "화살표 점선 arrow dashed down"},
	{char: "⇦", name: "왼쪽 흰 화살표", keywords: "화살표 arrow white left"},
	{char: "⇧", name: "위쪽 흰 화살표", keywords: "화살표 시프트 arrow white up shift"},
	{char: "⇨", name: "오른쪽 흰 화살표", keywords: "화살표 arrow white right"},
	{char: "⇩", name: "아래쪽 흰 화살표", keywords: "화살표 arrow white down"},
	{char: "⇥", name: "오른쪽 막대 화살표 탭", keywords: "화살표 탭 arrow tab right"},
	{char: "⇤", name: "왼쪽 막대 화살표 탭", keywords: "화살표 탭 arrow tab left"},
	{char: "⌁", name: "되돌림", keywords: "arrow delete escape"},
	{char: "⌃", name: "위 꺾쇠 컨트롤", keywords: "컨트롤 control caret up"},
	{char: "⌄", name: "아래 꺾쇠", keywords: "caret down"},
	{char: "⌘", name: "커맨드 키", keywords: "맥 명령 command mac cloverleaf"},
	{char: "⌥", name: "옵션 키", keywords: "맥 알트 option alt mac"},
	{char: "⎋", name: "이스케이프 키", keywords: "이스케이프 escape esc"},
	{char: "⏎", name: "리턴 키", keywords: "엔터 리턴 return enter"},
	{char: "⏏", name: "꺼내기", keywords: "이젝트 eject"},
	{char: "⌫", name: "지우기 왼쪽", keywords: "백스페이스 backspace delete"},
	{char: "⌦", name: "지우기 오른쪽", keywords: "딜리트 delete forward"},
	{char: "➔", name: "굵은 오른쪽 화살표", keywords: "화살표 arrow heavy right"},
	{char: "➜", name: "굵은 둥근 오른쪽 화살표", keywords: "화살표 arrow heavy round right"},
	{char: "➡", name: "오른쪽 화살표 그림", keywords: "화살표 arrow right black"},
	{char: "⬅", name: "왼쪽 화살표 그림", keywords: "화살표 arrow left black"},
	{char: "⬆", name: "위쪽 화살표 그림", keywords: "화살표 arrow up black"},
	{char: "⬇", name: "아래쪽 화살표 그림", keywords: "화살표 arrow down black"},
	{char: "⤴", name: "위로 굽은 화살표", keywords: "화살표 arrow curve up"},
	{char: "⤵", name: "아래로 굽은 화살표", keywords: "화살표 arrow curve down"},
	{char: "⟵", name: "긴 왼쪽 화살표", keywords: "화살표 arrow long left"},
	{char: "⟶", name: "긴 오른쪽 화살표", keywords: "화살표 arrow long right"},
	{char: "⟷", name: "긴 좌우 화살표", keywords: "화살표 arrow long left right"},
	{char: "⟸", name: "긴 왼쪽 두 줄 화살표", keywords: "화살표 arrow long double left"},
	{char: "⟹", name: "긴 오른쪽 두 줄 화살표", keywords: "화살표 arrow long double right"},
	{char: "⟺", name: "긴 좌우 두 줄 화살표", keywords: "화살표 arrow long double left right"},
	{char: "↯", name: "번개 화살표", keywords: "화살표 번개 arrow lightning"},
	{char: "⇋", name: "평형 화살표", keywords: "화살표 평형 arrow equilibrium"},
	{char: "⇌", name: "평형 화살표 반대", keywords: "화살표 평형 arrow equilibrium"},

	// 도형 (shape)
	{char: "▲", name: "검은 위쪽 삼각형", keywords: "삼각형 세모 triangle up black"},
	{char: "△", name: "흰 위쪽 삼각형", keywords: "삼각형 세모 triangle up white"},
	{char: "▼", name: "검은 아래쪽 삼각형", keywords: "삼각형 세모 triangle down black"},
	{char: "▽", name: "흰 아래쪽 삼각형", keywords: "삼각형 세모 triangle down white"},
	{char: "◀", name: "검은 왼쪽 삼각형", keywords: "삼각형 세모 triangle left black"},
	{char: "◁", name: "흰 왼쪽 삼각형", keywords: "삼각형 세모 triangle left white"},
	{char: "▶", name: "검은 오른쪽 삼각형", keywords: "삼각형 세모 triangle right black"},
	{char: "▷", name: "흰 오른쪽 삼각형", keywords: "삼각형 세모 triangle right white"},
	{char: "▴", name: "검은 작은 위쪽 삼각형", keywords: "삼각형 세모 triangle up small black"},
	{char: "▵", name: "흰 작은 위쪽 삼각형", keywords: "삼각형 세모 triangle up small white"},
	{char: "▾", name: "검은 작은 아래쪽 삼각형", keywords: "삼각형 세모 triangle down small black"},
	{char: "▿", name: "흰 작은 아래쪽 삼각형", keywords: "삼각형 세모 triangle down small white"},
	{char: "◂", name: "검은 작은 왼쪽 삼각형", keywords: "삼각형 세모 triangle left small black"},
	{char: "◃", name: "흰 작은 왼쪽 삼각형", keywords: "삼각형 세모 triangle left small white"},
	{char: "▸", name: "검은 작은 오른쪽 삼각형", keywords: "삼각형 세모 triangle right small black"},
	{char: "▹", name: "흰 작은 오른쪽 삼각형", keywords: "삼각형 세모 triangle right small white"},
	{char: "◤", name: "검은 왼쪽 위 삼각형", keywords: "삼각형 세모 triangle upper left"},
	{char: "◥", name: "검은 오른쪽 위 삼각형", keywords: "삼각형 세모 triangle upper right"},
	{char: "◣", name: "검은 왼쪽 아래 삼각형", keywords: "삼각형 세모 triangle lower left"},
	{char: "◢", name: "검은 오른쪽 아래 삼각형", keywords: "삼각형 세모 triangle lower right"},
	{char: "⊿", name: "직각 삼각형", keywords: "삼각형 세모 triangle right angle"},
	{char: "■", name: "검은 사각형", keywords: "네모 사각형 square black"},
	{char: "□", name: "흰 사각형", keywords: "네모 사각형 square white"},
	{char: "▪", name: "검은 작은 사각형", keywords: "네모 사각형 square small black"},
	{char: "▫", name: "흰 작은 사각형", keywords: "네모 사각형 square small white"},
	{char: "▬", name: "검은 가로 막대", keywords: "네모 막대 rectangle black"},
	{char: "▭", name: "흰 가로 막대", keywords: "네모 막대 rectangle white"},
	{char: "▮", name: "검은 세로 막대", keywords: "네모 막대 rectangle vertical black"},
	{char: "▯", name: "흰 세로 막대", keywords: "네모 막대 rectangle vertical white"},
	{char: "◆", name: "검은 마름모", keywords: "마름모 다이아 diamond black"},
	{char: "◇", name: "흰 마름모", keywords: "마름모 다이아 diamond white"},
	{char: "◈", name: "마름모 속 마름모", keywords: "마름모 다이아 diamond in diamond"},
	{char: "◊", name: "마름모꼴", keywords: "마름모 다이아 lozenge"},
	{char: "●", name: "검은 원", keywords: "동그라미 원 circle black"},
	{char: "○", name: "흰 원", keywords: "동그라미 원 circle white"},
	{char: "◎", name: "겹동그라미", keywords: "동그라미 원 circle bullseye"},
	{char: "◉", name: "가운데 찬 동그라미", keywords: "동그라미 원 circle fisheye"},
	{char: "◌", name: "점선 동그라미", keywords: "동그라미 원 circle dotted"},
	{char: "◯", name: "큰 원", keywords: "동그라미 원 circle large"},
	{char: "⬤", name: "큰 검은 원", keywords: "동그라미 원 circle large black"},
	{char: "◐", name: "왼쪽 반 검은 원", keywords: "동그라미 반원 circle half left"},
	{char: "◑", name: "오른쪽 반 검은 원", keywords: "동그라미 반원 circle half right"},
	{char: "◒", name: "아래 반 검은 원", keywords: "동그라미 반원 circle half bottom"},
	{char: "◓", name: "위 반 검은 원", keywords: "동그라미 반원 circle half top"},
	{char: "⬛", name: "큰 검은 정사각형", keywords: "네모 사각형 square large black"},
	{char: "⬜", name: "큰 흰 정사각형", keywords: "네모 사각형 square large white"},
	{char: "⯀", name: "검은 중간 사각형", keywords: "네모 사각형 square medium black"},
	{char: "★", name: "검은 별", keywords: "별 star black"},
	{char: "☆", name: "흰 별", keywords: "별 star white"},
	{char: "✦", name: "네 꼭짓점 검은 별", keywords: "별 star four point"},
	{char: "✧", name: "네 꼭짓점 흰 별", keywords: "별 star four point white"},
	{char: "✩", name: "얇은 흰 별", keywords: "별 star outline"},
	{char: "✪", name: "동그라미 속 별", keywords: "별 star circled"},
	{char: "✫", name: "가운데 뚫린 별", keywords: "별 star open centre"},
	{char: "✮", name: "가운데 찬 별", keywords: "별 star centre"},
	{char: "✯", name: "회전한 별", keywords: "별 star pinwheel"},
	{char: "❂", name: "동그라미 속 여덟살 별", keywords: "별 star circled eight"},
	{char: "✱", name: "굵은 별표", keywords: "별표 asterisk heavy"},
	{char: "✲", name: "열린 별표", keywords: "별표 asterisk open"},
	{char: "❉", name: "여섯살 별표", keywords: "별표 asterisk six"},
	{char: "❋", name: "여덟살 별표", keywords: "별표 asterisk eight"},
	{char: "⬟", name: "검은 오각형", keywords: "오각형 pentagon black"},
	{char: "⬠", name: "흰 오각형", keywords: "오각형 pentagon white"},
	{char: "⬢", name: "검은 육각형", keywords: "육각형 hexagon black"},
	{char: "⬣", name: "흰 육각형", keywords: "육각형 hexagon white"},
	{char: "⯃", name: "검은 팔각형", keywords: "팔각형 octagon black"},
	{char: "▰", name: "검은 기울인 사각형", keywords: "네모 사각형 parallelogram black"},
	{char: "▱", name: "흰 기울인 사각형", keywords: "네모 사각형 parallelogram white"},
	{char: "◫", name: "세로로 나뉜 사각형", keywords: "네모 사각형 square divided"},
	{char: "◪", name: "반쯤 찬 사각형", keywords: "네모 사각형 square half filled"},
	{char: "▩", name: "빗금친 사각형", keywords: "네모 사각형 square crosshatch"},
	{char: "▨", name: "빗금 사각형", keywords: "네모 사각형 square diagonal hatch"},
	{char: "▤", name: "가로줄 사각형", keywords: "네모 사각형 square horizontal fill"},
	{char: "▥", name: "세로줄 사각형", keywords: "네모 사각형 square vertical fill"},
	{char: "▦", name: "격자 사각형", keywords: "네모 사각형 square grid fill"},
	{char: "░", name: "옅은 음영", keywords: "음영 블록 shade light"},
	{char: "▒", name: "중간 음영", keywords: "음영 블록 shade medium"},
	{char: "▓", name: "짙은 음영", keywords: "음영 블록 shade dark"},
	{char: "█", name: "꽉 찬 블록", keywords: "블록 block full"},
	{char: "▄", name: "아래 반 블록", keywords: "블록 block lower half"},
	{char: "▀", name: "위 반 블록", keywords: "블록 block upper half"},
	{char: "▌", name: "왼쪽 반 블록", keywords: "블록 block left half"},
	{char: "▐", name: "오른쪽 반 블록", keywords: "블록 block right half"},
	{char: "▁", name: "아래 여덟분의 일 블록", keywords: "블록 그래프 block eighth"},
	{char: "▂", name: "아래 사분의 일 블록", keywords: "블록 그래프 block quarter"},
	{char: "▃", name: "아래 팔분의 삼 블록", keywords: "블록 그래프 block"},
	{char: "▅", name: "아래 팔분의 오 블록", keywords: "블록 그래프 block"},
	{char: "▆", name: "아래 사분의 삼 블록", keywords: "블록 그래프 block"},
	{char: "▇", name: "아래 팔분의 칠 블록", keywords: "블록 그래프 block"},

	// 수학 (math)
	{char: "±", name: "플러스 마이너스", keywords: "더하기 빼기 plus minus"},
	{char: "∓", name: "마이너스 플러스", keywords: "빼기 더하기 minus plus"},
	{char: "×", name: "곱하기", keywords: "곱셈 multiply times"},
	{char: "÷", name: "나누기", keywords: "나눗셈 divide"},
	{char: "∕", name: "나눗셈 사선", keywords: "나눗셈 division slash"},
	{char: "∗", name: "별표 연산", keywords: "곱 asterisk operator"},
	{char: "∘", name: "합성", keywords: "고리 ring composition"},
	{char: "∙", name: "가운뎃점 연산", keywords: "점 bullet operator"},
	{char: "⋅", name: "점 곱", keywords: "점 dot product"},
	{char: "≠", name: "같지 않음", keywords: "부등호 not equal"},
	{char: "≈", name: "거의 같음", keywords: "근사 approximately equal"},
	{char: "≅", name: "합동", keywords: "근사 congruent"},
	{char: "≡", name: "항등", keywords: "합동 identical equivalent"},
	{char: "≢", name: "항등 아님", keywords: "not identical"},
	{char: "≒", name: "근사 등호", keywords: "근사 approximately equal"},
	{char: "≤", name: "작거나 같음", keywords: "부등호 less than or equal"},
	{char: "≥", name: "크거나 같음", keywords: "부등호 greater than or equal"},
	{char: "≪", name: "훨씬 작음", keywords: "부등호 much less than"},
	{char: "≫", name: "훨씬 큼", keywords: "부등호 much greater than"},
	{char: "∞", name: "무한대", keywords: "무한 infinity"},
	{char: "∝", name: "비례", keywords: "proportional to"},
	{char: "∂", name: "편미분", keywords: "미분 partial differential"},
	{char: "∇", name: "나블라", keywords: "델 nabla del gradient"},
	{char: "∫", name: "적분", keywords: "integral"},
	{char: "∬", name: "이중 적분", keywords: "적분 double integral"},
	{char: "∮", name: "선적분", keywords: "적분 contour integral"},
	{char: "∑", name: "시그마 합", keywords: "합 sum sigma"},
	{char: "∏", name: "파이 곱", keywords: "곱 product pi"},
	{char: "√", name: "제곱근", keywords: "루트 square root"},
	{char: "∛", name: "세제곱근", keywords: "루트 cube root"},
	{char: "∜", name: "네제곱근", keywords: "루트 fourth root"},
	{char: "∀", name: "모든", keywords: "전칭 for all"},
	{char: "∃", name: "존재", keywords: "존재 there exists"},
	{char: "∄", name: "존재하지 않음", keywords: "there does not exist"},
	{char: "∅", name: "공집합", keywords: "집합 empty set"},
	{char: "∈", name: "원소", keywords: "집합 element of"},
	{char: "∉", name: "원소 아님", keywords: "집합 not element of"},
	{char: "∋", name: "포함 원소", keywords: "집합 contains as member"},
	{char: "⊂", name: "부분집합", keywords: "집합 subset"},
	{char: "⊃", name: "포함집합", keywords: "집합 superset"},
	{char: "⊆", name: "부분집합 또는 같음", keywords: "집합 subset or equal"},
	{char: "⊇", name: "포함집합 또는 같음", keywords: "집합 superset or equal"},
	{char: "⊄", name: "부분집합 아님", keywords: "집합 not subset"},
	{char: "∪", name: "합집합", keywords: "집합 union"},
	{char: "∩", name: "교집합", keywords: "집합 intersection"},
	{char: "∖", name: "차집합", keywords: "집합 set minus"},
	{char: "∧", name: "논리곱", keywords: "그리고 logical and wedge"},
	{char: "∨", name: "논리합", keywords: "또는 logical or vee"},
	{char: "¬", name: "부정", keywords: "논리 not negation"},
	{char: "⊕", name: "배타적 논리합", keywords: "엑스오 xor circled plus"},
	{char: "⊗", name: "텐서 곱", keywords: "circled times tensor"},
	{char: "⊥", name: "수직", keywords: "직교 perpendicular"},
	{char: "∥", name: "평행", keywords: "parallel to"},
	{char: "∠", name: "각", keywords: "각도 angle"},
	{char: "∟", name: "직각", keywords: "각도 right angle"},
	{char: "°", name: "도", keywords: "각도 온도 degree"},
	{char: "′", name: "프라임", keywords: "분 prime minute"},
	{char: "″", name: "더블 프라임", keywords: "초 double prime second"},
	{char: "∴", name: "그러므로", keywords: "therefore"},
	{char: "∵", name: "왜냐하면", keywords: "because"},
	{char: "∼", name: "물결 관계", keywords: "닮음 tilde operator similar"},
	{char: "≃", name: "점근 같음", keywords: "닮음 asymptotically equal"},
	{char: "≜", name: "정의에 의해 같음", keywords: "정의 delta equal to"},
	{char: "≝", name: "정의됨", keywords: "정의 equal by definition"},
	{char: "≟", name: "같은지 물음", keywords: "questioned equal"},
	{char: "⌈", name: "천장 왼쪽", keywords: "올림 ceiling left"},
	{char: "⌉", name: "천장 오른쪽", keywords: "올림 ceiling right"},
	{char: "⌊", name: "바닥 왼쪽", keywords: "내림 floor left"},
	{char: "⌋", name: "바닥 오른쪽", keywords: "내림 floor right"},
	{char: "⟨", name: "왼쪽 꺾쇠", keywords: "괄호 angle bracket left"},
	{char: "⟩", name: "오른쪽 꺾쇠", keywords: "괄호 angle bracket right"},
	{char: "ℝ", name: "실수 집합", keywords: "집합 real numbers"},
	{char: "ℕ", name: "자연수 집합", keywords: "집합 natural numbers"},
	{char: "ℤ", name: "정수 집합", keywords: "집합 integers"},
	{char: "ℚ", name: "유리수 집합", keywords: "집합 rational numbers"},
	{char: "ℂ", name: "복소수 집합", keywords: "집합 complex numbers"},
	{char: "ℵ", name: "알레프", keywords: "aleph"},
	{char: "ℓ", name: "필기체 엘", keywords: "script small l"},
	{char: "℘", name: "바이어슈트라스 피", keywords: "weierstrass p"},
	{char: "ℏ", name: "플랑크 상수", keywords: "planck constant hbar"},
	{char: "∎", name: "증명 끝", keywords: "증명 end of proof qed"},
	{char: "⊤", name: "참", keywords: "논리 top true"},
	{char: "⊢", name: "귀결", keywords: "논리 turnstile proves"},
	{char: "⊨", name: "만족", keywords: "논리 models entails"},
	{char: "⋮", name: "세로 생략", keywords: "생략 vertical ellipsis"},
	{char: "⋯", name: "가운데 생략", keywords: "생략 midline ellipsis"},
	{char: "⋱", name: "대각 생략", keywords: "생략 diagonal ellipsis"},
	{char: "≺", name: "선행", keywords: "순서 precedes"},
	{char: "≻", name: "후행", keywords: "순서 succeeds"},
	{char: "⊑", name: "포함 사각", keywords: "순서 square image of or equal"},
	{char: "⌀", name: "지름", keywords: "공집합 diameter"},
	{char: "∆", name: "증분 델타", keywords: "델타 increment delta"},
	{char: "µ", name: "마이크로", keywords: "micro"},
	{char: "Ω", name: "옴", keywords: "옴 ohm omega"},
	{char: "Å", name: "옹스트롬", keywords: "angstrom"},
	{char: "‰", name: "퍼밀", keywords: "천분율 per mille"},
	{char: "‱", name: "퍼밀리아드", keywords: "만분율 per ten thousand"},
	{char: "%", name: "퍼센트", keywords: "백분율 percent"},

	// 구두점 (punctuation)
	{char: "…", name: "말줄임표", keywords: "생략 ellipsis dots"},
	{char: "‥", name: "두 점 말줄임", keywords: "생략 two dot leader"},
	{char: "–", name: "엔 대시", keywords: "줄표 en dash"},
	{char: "—", name: "엠 대시", keywords: "줄표 em dash"},
	{char: "―", name: "가로줄", keywords: "줄표 horizontal bar"},
	{char: "‐", name: "붙임표", keywords: "하이픈 hyphen"},
	{char: "‑", name: "안 끊기는 붙임표", keywords: "하이픈 non breaking hyphen"},
	{char: "·", name: "가운뎃점", keywords: "점 middle dot interpunct"},
	{char: "•", name: "글머리 점", keywords: "불릿 점 bullet"},
	{char: "◦", name: "흰 글머리 점", keywords: "불릿 점 bullet white"},
	{char: "‣", name: "삼각 글머리 점", keywords: "불릿 점 triangular bullet"},
	{char: "⁃", name: "하이픈 글머리 점", keywords: "불릿 점 hyphen bullet"},
	{char: "‧", name: "이음 가운뎃점", keywords: "점 hyphenation point"},
	{char: "†", name: "칼표", keywords: "각주 dagger"},
	{char: "‡", name: "겹칼표", keywords: "각주 double dagger"},
	{char: "§", name: "절 기호", keywords: "섹션 section sign"},
	{char: "¶", name: "단락 기호", keywords: "필크로 pilcrow paragraph"},
	{char: "‖", name: "겹세로줄", keywords: "double vertical line"},
	{char: "¦", name: "끊긴 세로줄", keywords: "broken bar"},
	{char: "“", name: "왼쪽 큰따옴표", keywords: "따옴표 quote left double"},
	{char: "”", name: "오른쪽 큰따옴표", keywords: "따옴표 quote right double"},
	{char: "‘", name: "왼쪽 작은따옴표", keywords: "따옴표 quote left single"},
	{char: "’", name: "오른쪽 작은따옴표", keywords: "따옴표 어퍼스트로피 quote right single apostrophe"},
	{char: "„", name: "아래 큰따옴표", keywords: "따옴표 quote low double"},
	{char: "‚", name: "아래 작은따옴표", keywords: "따옴표 quote low single"},
	{char: "«", name: "왼쪽 겹화살괄호", keywords: "따옴표 guillemet left"},
	{char: "»", name: "오른쪽 겹화살괄호", keywords: "따옴표 guillemet right"},
	{char: "‹", name: "왼쪽 홑화살괄호", keywords: "따옴표 guillemet single left"},
	{char: "›", name: "오른쪽 홑화살괄호", keywords: "따옴표 guillemet single right"},
	{char: "¡", name: "거꾸로 느낌표", keywords: "느낌표 inverted exclamation"},
	{char: "¿", name: "거꾸로 물음표", keywords: "물음표 inverted question"},
	{char: "‽", name: "물음느낌표", keywords: "interrobang"},
	{char: "⁇", name: "겹물음표", keywords: "물음표 double question"},
	{char: "⁈", name: "물음느낌", keywords: "question exclamation"},
	{char: "⁉", name: "느낌물음", keywords: "exclamation question"},
	{char: "‼", name: "겹느낌표", keywords: "느낌표 double exclamation"},
	{char: "※", name: "참고표", keywords: "코메 reference mark"},
	{char: "⁂", name: "별 세 개", keywords: "asterism"},
	{char: "⌗", name: "우물 정", keywords: "샵 해시 hash number sign"},
	{char: "№", name: "번호", keywords: "넘버 numero"},
	{char: "℗", name: "저작인접권", keywords: "phonogram copyright"},
	{char: "©", name: "저작권", keywords: "카피라이트 copyright"},
	{char: "®", name: "등록상표", keywords: "registered trademark"},
	{char: "™", name: "상표", keywords: "트레이드마크 trademark"},
	{char: "℠", name: "서비스표", keywords: "service mark"},
	{char: "＿", name: "전각 밑줄", keywords: "밑줄 fullwidth low line"},
	{char: "〜", name: "물결표", keywords: "물결 wave dash"},
	{char: "～", name: "전각 물결표", keywords: "물결 fullwidth tilde"},
	{char: "〰", name: "물결 점선", keywords: "물결 wavy dash"},
	{char: "ᵎ", name: "작은 느낌표", keywords: "느낌표 small exclamation"},
	{char: "〽", name: "노래 기호", keywords: "part alternation"},

	// 괄호 (bracket)
	{char: "「", name: "홑낫표 열기", keywords: "괄호 낫표 corner bracket left"},
	{char: "」", name: "홑낫표 닫기", keywords: "괄호 낫표 corner bracket right"},
	{char: "『", name: "겹낫표 열기", keywords: "괄호 낫표 white corner bracket left"},
	{char: "』", name: "겹낫표 닫기", keywords: "괄호 낫표 white corner bracket right"},
	{char: "〈", name: "홑화살괄호 열기", keywords: "괄호 angle bracket left"},
	{char: "〉", name: "홑화살괄호 닫기", keywords: "괄호 angle bracket right"},
	{char: "《", name: "겹화살괄호 열기", keywords: "괄호 double angle bracket left"},
	{char: "》", name: "겹화살괄호 닫기", keywords: "괄호 double angle bracket right"},
	{char: "【", name: "굵은 대괄호 열기", keywords: "괄호 black lenticular left"},
	{char: "】", name: "굵은 대괄호 닫기", keywords: "괄호 black lenticular right"},
	{char: "〔", name: "거북 등 괄호 열기", keywords: "괄호 tortoise shell left"},
	{char: "〕", name: "거북 등 괄호 닫기", keywords: "괄호 tortoise shell right"},
	{char: "〖", name: "흰 대괄호 열기", keywords: "괄호 white lenticular left"},
	{char: "〗", name: "흰 대괄호 닫기", keywords: "괄호 white lenticular right"},
	{char: "（", name: "전각 소괄호 열기", keywords: "괄호 fullwidth paren left"},
	{char: "）", name: "전각 소괄호 닫기", keywords: "괄호 fullwidth paren right"},
	{char: "［", name: "전각 대괄호 열기", keywords: "괄호 fullwidth bracket left"},
	{char: "］", name: "전각 대괄호 닫기", keywords: "괄호 fullwidth bracket right"},
	{char: "｛", name: "전각 중괄호 열기", keywords: "괄호 fullwidth brace left"},
	{char: "｝", name: "전각 중괄호 닫기", keywords: "괄호 fullwidth brace right"},
	{char: "⦗", name: "굵은 홈 괄호 열기", keywords: "괄호 tortoise shell bracket left"},
	{char: "⦘", name: "굵은 홈 괄호 닫기", keywords: "괄호 tortoise shell bracket right"},
	{char: "⟦", name: "겹대괄호 열기", keywords: "괄호 double bracket left"},
	{char: "⟧", name: "겹대괄호 닫기", keywords: "괄호 double bracket right"},
	{char: "⟪", name: "겹꺾쇠 열기", keywords: "괄호 double angle left"},
	{char: "⟫", name: "겹꺾쇠 닫기", keywords: "괄호 double angle right"},
	{char: "⌜", name: "왼쪽 위 모서리", keywords: "괄호 corner top left"},
	{char: "⌝", name: "오른쪽 위 모서리", keywords: "괄호 corner top right"},
	{char: "⌞", name: "왼쪽 아래 모서리", keywords: "괄호 corner bottom left"},
	{char: "⌟", name: "오른쪽 아래 모서리", keywords: "괄호 corner bottom right"},

	// 통화 (currency)
	{char: "₩", name: "원", keywords: "화폐 통화 won korea"},
	{char: "$", name: "달러", keywords: "화폐 통화 dollar"},
	{char: "¢", name: "센트", keywords: "화폐 통화 cent"},
	{char: "€", name: "유로", keywords: "화폐 통화 euro"},
	{char: "£", name: "파운드", keywords: "화폐 통화 pound sterling"},
	{char: "¥", name: "엔", keywords: "화폐 통화 yen japan"},
	{char: "元", name: "위안", keywords: "화폐 통화 yuan china"},
	{char: "₽", name: "루블", keywords: "화폐 통화 ruble russia"},
	{char: "₹", name: "루피", keywords: "화폐 통화 rupee india"},
	{char: "₫", name: "동", keywords: "화폐 통화 dong vietnam"},
	{char: "₺", name: "리라", keywords: "화폐 통화 lira turkey"},
	{char: "₴", name: "흐리우냐", keywords: "화폐 통화 hryvnia ukraine"},
	{char: "₦", name: "나이라", keywords: "화폐 통화 naira nigeria"},
	{char: "₱", name: "페소", keywords: "화폐 통화 peso philippines"},
	{char: "฿", name: "바트", keywords: "화폐 통화 baht thailand"},
	{char: "₪", name: "셰켈", keywords: "화폐 통화 shekel israel"},
	{char: "₸", name: "텡게", keywords: "화폐 통화 tenge kazakhstan"},
	{char: "₡", name: "콜론", keywords: "화폐 통화 colon"},
	{char: "₲", name: "과라니", keywords: "화폐 통화 guarani"},
	{char: "₵", name: "세디", keywords: "화폐 통화 cedi"},
	{char: "₭", name: "킵", keywords: "화폐 통화 kip laos"},
	{char: "₮", name: "투그릭", keywords: "화폐 통화 tugrik mongolia"},
	{char: "₾", name: "라리", keywords: "화폐 통화 lari georgia"},
	{char: "¤", name: "통화 기호", keywords: "화폐 통화 currency sign"},
	{char: "₿", name: "비트코인", keywords: "화폐 통화 bitcoin"},

	// 괘선 (box drawing)
	{char: "─", name: "가로줄", keywords: "괘선 박스 box horizontal"},
	{char: "│", name: "세로줄", keywords: "괘선 박스 box vertical"},
	{char: "┌", name: "왼쪽 위 모서리", keywords: "괘선 박스 box corner top left"},
	{char: "┐", name: "오른쪽 위 모서리", keywords: "괘선 박스 box corner top right"},
	{char: "└", name: "왼쪽 아래 모서리", keywords: "괘선 박스 box corner bottom left"},
	{char: "┘", name: "오른쪽 아래 모서리", keywords: "괘선 박스 box corner bottom right"},
	{char: "├", name: "왼쪽 갈림", keywords: "괘선 박스 box tee left"},
	{char: "┤", name: "오른쪽 갈림", keywords: "괘선 박스 box tee right"},
	{char: "┬", name: "위 갈림", keywords: "괘선 박스 box tee down"},
	{char: "┴", name: "아래 갈림", keywords: "괘선 박스 box tee up"},
	{char: "┼", name: "십자 교차", keywords: "괘선 박스 box cross"},
	{char: "━", name: "굵은 가로줄", keywords: "괘선 박스 box horizontal heavy"},
	{char: "┃", name: "굵은 세로줄", keywords: "괘선 박스 box vertical heavy"},
	{char: "┏", name: "굵은 왼쪽 위 모서리", keywords: "괘선 박스 box heavy corner"},
	{char: "┓", name: "굵은 오른쪽 위 모서리", keywords: "괘선 박스 box heavy corner"},
	{char: "┗", name: "굵은 왼쪽 아래 모서리", keywords: "괘선 박스 box heavy corner"},
	{char: "┛", name: "굵은 오른쪽 아래 모서리", keywords: "괘선 박스 box heavy corner"},
	{char: "┣", name: "굵은 왼쪽 갈림", keywords: "괘선 박스 box heavy tee"},
	{char: "┫", name: "굵은 오른쪽 갈림", keywords: "괘선 박스 box heavy tee"},
	{char: "┳", name: "굵은 위 갈림", keywords: "괘선 박스 box heavy tee"},
	{char: "┻", name: "굵은 아래 갈림", keywords: "괘선 박스 box heavy tee"},
	{char: "╋", name: "굵은 십자 교차", keywords: "괘선 박스 box heavy cross"},
	{char: "═", name: "두 줄 가로줄", keywords: "괘선 박스 box double horizontal"},
	{char: "║", name: "두 줄 세로줄", keywords: "괘선 박스 box double vertical"},
	{char: "╔", name: "두 줄 왼쪽 위 모서리", keywords: "괘선 박스 box double corner"},
	{char: "╗", name: "두 줄 오른쪽 위 모서리", keywords: "괘선 박스 box double corner"},
	{char: "╚", name: "두 줄 왼쪽 아래 모서리", keywords: "괘선 박스 box double corner"},
	{char: "╝", name: "두 줄 오른쪽 아래 모서리", keywords: "괘선 박스 box double corner"},
	{char: "╠", name: "두 줄 왼쪽 갈림", keywords: "괘선 박스 box double tee"},
	{char: "╣", name: "두 줄 오른쪽 갈림", keywords: "괘선 박스 box double tee"},
	{char: "╦", name: "두 줄 위 갈림", keywords: "괘선 박스 box double tee"},
	{char: "╩", name: "두 줄 아래 갈림", keywords: "괘선 박스 box double tee"},
	{char: "╬", name: "두 줄 십자 교차", keywords: "괘선 박스 box double cross"},
	{char: "╭", name: "둥근 왼쪽 위 모서리", keywords: "괘선 박스 box round corner"},
	{char: "╮", name: "둥근 오른쪽 위 모서리", keywords: "괘선 박스 box round corner"},
	{char: "╯", name: "둥근 오른쪽 아래 모서리", keywords: "괘선 박스 box round corner"},
	{char: "╰", name: "둥근 왼쪽 아래 모서리", keywords: "괘선 박스 box round corner"},
	{char: "╱", name: "오른쪽 위 대각선", keywords: "괘선 박스 box diagonal"},
	{char: "╲", name: "오른쪽 아래 대각선", keywords: "괘선 박스 box diagonal"},
	{char: "╳", name: "대각선 교차", keywords: "괘선 박스 box diagonal cross"},
	{char: "┄", name: "점선 가로줄", keywords: "괘선 박스 box dashed horizontal"},
	{char: "┆", name: "점선 세로줄", keywords: "괘선 박스 box dashed vertical"},
	{char: "╌", name: "짧은 점선 가로줄", keywords: "괘선 박스 box dashed horizontal"},
	{char: "╎", name: "짧은 점선 세로줄", keywords: "괘선 박스 box dashed vertical"},

	// 기호 (sign)
	{char: "✓", name: "체크", keywords: "체크 확인 check mark tick"},
	{char: "✔", name: "굵은 체크", keywords: "체크 확인 check mark heavy"},
	{char: "☑", name: "체크 상자", keywords: "체크 확인 ballot box checked"},
	{char: "☐", name: "빈 상자", keywords: "체크 ballot box empty"},
	{char: "☒", name: "엑스 상자", keywords: "체크 ballot box x"},
	{char: "✗", name: "엑스", keywords: "엑스 취소 ballot x"},
	{char: "✘", name: "굵은 엑스", keywords: "엑스 취소 ballot x heavy"},
	{char: "✕", name: "곱셈 엑스", keywords: "엑스 multiplication x"},
	{char: "✖", name: "굵은 곱셈 엑스", keywords: "엑스 multiplication x heavy"},
	{char: "✚", name: "굵은 십자", keywords: "더하기 heavy greek cross"},
	{char: "✛", name: "열린 십자", keywords: "더하기 open centre cross"},
	{char: "⚠", name: "경고", keywords: "주의 warning"},
	{char: "⚡", name: "번개", keywords: "전기 high voltage lightning"},
	{char: "☠", name: "해골", keywords: "죽음 skull crossbones"},
	{char: "☢", name: "방사능", keywords: "위험 radioactive"},
	{char: "☣", name: "생물학적 위험", keywords: "위험 biohazard"},
	{char: "♻", name: "재활용", keywords: "recycling"},
	{char: "⚙", name: "톱니바퀴", keywords: "설정 gear"},
	{char: "⚛", name: "원자", keywords: "atom"},
	{char: "⚖", name: "저울", keywords: "균형 scales balance"},
	{char: "⚓", name: "닻", keywords: "anchor"},
	{char: "⚔", name: "칼 두 자루", keywords: "무기 crossed swords"},
	{char: "⚑", name: "깃발", keywords: "flag"},
	{char: "⚐", name: "흰 깃발", keywords: "flag white"},
	{char: "⚕", name: "의료 지팡이", keywords: "의료 medical staff aesculapius"},
	{char: "☮", name: "평화", keywords: "peace"},
	{char: "☯", name: "음양", keywords: "태극 yin yang"},
	{char: "☰", name: "건 삼괘", keywords: "괘 trigram heaven"},
	{char: "☷", name: "곤 삼괘", keywords: "괘 trigram earth"},
	{char: "♠", name: "스페이드", keywords: "카드 spade"},
	{char: "♥", name: "하트", keywords: "카드 사랑 heart"},
	{char: "♦", name: "다이아몬드", keywords: "카드 diamond"},
	{char: "♣", name: "클로버", keywords: "카드 club"},
	{char: "♤", name: "흰 스페이드", keywords: "카드 spade white"},
	{char: "♡", name: "흰 하트", keywords: "카드 사랑 heart white"},
	{char: "♢", name: "흰 다이아몬드", keywords: "카드 diamond white"},
	{char: "♧", name: "흰 클로버", keywords: "카드 club white"},
	{char: "☀", name: "해", keywords: "날씨 sun"},
	{char: "☁", name: "구름", keywords: "날씨 cloud"},
	{char: "☂", name: "우산", keywords: "날씨 umbrella"},
	{char: "☃", name: "눈사람", keywords: "날씨 snowman"},
	{char: "❄", name: "눈송이", keywords: "날씨 snowflake"},
	{char: "☾", name: "초승달", keywords: "달 crescent moon"},
	{char: "☽", name: "상현달", keywords: "달 first quarter moon"},
	{char: "♀", name: "여성", keywords: "성별 female venus"},
	{char: "♂", name: "남성", keywords: "성별 male mars"},
	{char: "⚥", name: "남녀", keywords: "성별 male and female"},
	{char: "♪", name: "8분음표", keywords: "음악 음표 note eighth"},
	{char: "♫", name: "이어진 8분음표", keywords: "음악 음표 note beamed"},
	{char: "♬", name: "이어진 16분음표", keywords: "음악 음표 note beamed sixteenth"},
	{char: "♩", name: "4분음표", keywords: "음악 음표 note quarter"},
	{char: "♭", name: "플랫", keywords: "음악 flat"},
	{char: "♯", name: "샾", keywords: "음악 sharp"},
	{char: "♮", name: "제자리표", keywords: "음악 natural"},
	{char: "☎", name: "전화", keywords: "phone telephone"},
	{char: "✉", name: "편지", keywords: "메일 envelope mail"},
	{char: "✂", name: "가위", keywords: "scissors"},
	{char: "✈", name: "비행기", keywords: "airplane"},
	{char: "✏", name: "연필", keywords: "pencil"},
	{char: "✒", name: "펜촉", keywords: "nib pen"},
	{char: "☞", name: "오른쪽 손가락", keywords: "손 pointing right hand"},
	{char: "☜", name: "왼쪽 손가락", keywords: "손 pointing left hand"},
	{char: "☝", name: "위쪽 손가락", keywords: "손 pointing up hand"},
	{char: "☟", name: "아래쪽 손가락", keywords: "손 pointing down hand"},
	{char: "✍", name: "쓰는 손", keywords: "손 writing hand"},
	{char: "⌚", name: "손목시계", keywords: "시계 watch"},
	{char: "⌛", name: "모래시계", keywords: "시계 hourglass"},
	{char: "⏰", name: "알람 시계", keywords: "시계 alarm clock"},
	{char: "⏳", name: "흐르는 모래시계", keywords: "시계 hourglass flowing"},
	{char: "⏱", name: "스톱워치", keywords: "시계 stopwatch"},
	{char: "⏲", name: "타이머", keywords: "시계 timer clock"},
	{char: "⚀", name: "주사위 일", keywords: "주사위 die one"},
	{char: "⚁", name: "주사위 이", keywords: "주사위 die two"},
	{char: "⚂", name: "주사위 삼", keywords: "주사위 die three"},
	{char: "⚃", name: "주사위 사", keywords: "주사위 die four"},
	{char: "⚄", name: "주사위 오", keywords: "주사위 die five"},
	{char: "⚅", name: "주사위 육", keywords: "주사위 die six"},
	{char: "☕", name: "커피", keywords: "음료 hot beverage coffee"},
	{char: "♨", name: "온천", keywords: "hot springs"},
	{char: "⚘", name: "꽃", keywords: "flower"},
	{char: "✿", name: "겹꽃", keywords: "flower blossom"},
	{char: "❀", name: "흰 꽃", keywords: "flower white"},
	{char: "❁", name: "동그란 꽃", keywords: "flower eight petalled"},
	{char: "☘", name: "세잎클로버", keywords: "행운 shamrock"},
	{char: "⚜", name: "백합 문장", keywords: "fleur de lis"},
	{char: "〄", name: "일본 공업 규격", keywords: "jis mark"},
	{char: "♿", name: "휠체어", keywords: "장애인 wheelchair"},
	{char: "⚟", name: "위쪽 반원", keywords: "notched left semicircle"},
	{char: "⏩", name: "빨리 감기", keywords: "재생 fast forward"},
	{char: "⏪", name: "되감기", keywords: "재생 rewind"},
	{char: "⏸", name: "일시정지", keywords: "재생 pause"},
	{char: "⏹", name: "정지", keywords: "재생 stop"},
	{char: "⏺", name: "녹화", keywords: "재생 record"},
	{char: "⏯", name: "재생 일시정지", keywords: "재생 play pause"},
	{char: "♲", name: "재활용 흰색", keywords: "recycling white"},
	{char: "✳", name: "여덟살 별표", keywords: "별표 asterisk eight spoked"},
	{char: "✴", name: "여덟꼭짓점 별", keywords: "별 star eight pointed"},
	{char: "❇", name: "반짝임", keywords: "sparkle"},
	{char: "✨", name: "반짝반짝", keywords: "sparkles"},
	{char: "❖", name: "검은 마름모 꽃", keywords: "마름모 diamond minus"},
	{char: "➤", name: "검은 오른쪽 화살촉", keywords: "화살표 arrowhead right"},
	{char: "➢", name: "오른쪽 화살촉", keywords: "화살표 arrowhead right three"},
	{char: "⟡", name: "흰 마름모", keywords: "마름모 diamond"},
	{char: "⌂", name: "집", keywords: "house home"},
	{char: "⏻", name: "전원", keywords: "power symbol"},
	{char: "⏼", name: "전원 켜짐", keywords: "power on off"},
	{char: "⭘", name: "전원 끄기", keywords: "power off"},

	// 문자와 숫자 (letter and number)
	{char: "α", name: "알파", keywords: "그리스 greek alpha"},
	{char: "β", name: "베타", keywords: "그리스 greek beta"},
	{char: "γ", name: "감마", keywords: "그리스 greek gamma"},
	{char: "δ", name: "델타", keywords: "그리스 greek delta"},
	{char: "ε", name: "엡실론", keywords: "그리스 greek epsilon"},
	{char: "ζ", name: "제타", keywords: "그리스 greek zeta"},
	{char: "η", name: "에타", keywords: "그리스 greek eta"},
	{char: "θ", name: "세타", keywords: "그리스 greek theta"},
	{char: "ι", name: "이오타", keywords: "그리스 greek iota"},
	{char: "κ", name: "카파", keywords: "그리스 greek kappa"},
	{char: "λ", name: "람다", keywords: "그리스 greek lambda"},
	{char: "μ", name: "뮤", keywords: "그리스 greek mu"},
	{char: "ν", name: "뉴", keywords: "그리스 greek nu"},
	{char: "ξ", name: "크시", keywords: "그리스 greek xi"},
	{char: "π", name: "파이", keywords: "그리스 greek pi"},
	{char: "ρ", name: "로", keywords: "그리스 greek rho"},
	{char: "σ", name: "시그마", keywords: "그리스 greek sigma"},
	{char: "τ", name: "타우", keywords: "그리스 greek tau"},
	{char: "υ", name: "윕실론", keywords: "그리스 greek upsilon"},
	{char: "φ", name: "피", keywords: "그리스 greek phi"},
	{char: "χ", name: "카이", keywords: "그리스 greek chi"},
	{char: "ψ", name: "프시", keywords: "그리스 greek psi"},
	{char: "ω", name: "오메가", keywords: "그리스 greek omega"},
	{char: "Γ", name: "대문자 감마", keywords: "그리스 greek capital gamma"},
	{char: "Δ", name: "대문자 델타", keywords: "그리스 greek capital delta"},
	{char: "Θ", name: "대문자 세타", keywords: "그리스 greek capital theta"},
	{char: "Λ", name: "대문자 람다", keywords: "그리스 greek capital lambda"},
	{char: "Ξ", name: "대문자 크시", keywords: "그리스 greek capital xi"},
	{char: "Π", name: "대문자 파이", keywords: "그리스 greek capital pi"},
	{char: "Σ", name: "대문자 시그마", keywords: "그리스 greek capital sigma"},
	{char: "Φ", name: "대문자 피", keywords: "그리스 greek capital phi"},
	{char: "Ψ", name: "대문자 프시", keywords: "그리스 greek capital psi"},
	{char: "⁰", name: "0 위첨자", keywords: "위첨자 첨자 superscript 0"},
	{char: "¹", name: "1 위첨자", keywords: "위첨자 첨자 superscript 1"},
	{char: "²", name: "2 위첨자", keywords: "위첨자 첨자 superscript 2"},
	{char: "³", name: "3 위첨자", keywords: "위첨자 첨자 superscript 3"},
	{char: "⁴", name: "4 위첨자", keywords: "위첨자 첨자 superscript 4"},
	{char: "⁵", name: "5 위첨자", keywords: "위첨자 첨자 superscript 5"},
	{char: "⁶", name: "6 위첨자", keywords: "위첨자 첨자 superscript 6"},
	{char: "⁷", name: "7 위첨자", keywords: "위첨자 첨자 superscript 7"},
	{char: "⁸", name: "8 위첨자", keywords: "위첨자 첨자 superscript 8"},
	{char: "⁹", name: "9 위첨자", keywords: "위첨자 첨자 superscript 9"},
	{char: "⁺", name: "더하기 위첨자", keywords: "위첨자 첨자 superscript plus"},
	{char: "⁻", name: "빼기 위첨자", keywords: "위첨자 첨자 superscript minus"},
	{char: "ⁿ", name: "n 위첨자", keywords: "위첨자 첨자 superscript n"},
	{char: "₀", name: "0 아래첨자", keywords: "아래첨자 첨자 subscript 0"},
	{char: "₁", name: "1 아래첨자", keywords: "아래첨자 첨자 subscript 1"},
	{char: "₂", name: "2 아래첨자", keywords: "아래첨자 첨자 subscript 2"},
	{char: "₃", name: "3 아래첨자", keywords: "아래첨자 첨자 subscript 3"},
	{char: "₄", name: "4 아래첨자", keywords: "아래첨자 첨자 subscript 4"},
	{char: "₅", name: "5 아래첨자", keywords: "아래첨자 첨자 subscript 5"},
	{char: "₆", name: "6 아래첨자", keywords: "아래첨자 첨자 subscript 6"},
	{char: "₇", name: "7 아래첨자", keywords: "아래첨자 첨자 subscript 7"},
	{char: "₈", name: "8 아래첨자", keywords: "아래첨자 첨자 subscript 8"},
	{char: "₉", name: "9 아래첨자", keywords: "아래첨자 첨자 subscript 9"},
	{char: "₊", name: "더하기 아래첨자", keywords: "아래첨자 첨자 subscript plus"},
	{char: "₋", name: "빼기 아래첨자", keywords: "아래첨자 첨자 subscript minus"},
	{char: "½", name: "이분의 일", keywords: "분수 fraction half"},
	{char: "⅓", name: "삼분의 일", keywords: "분수 fraction third"},
	{char: "⅔", name: "삼분의 이", keywords: "분수 fraction two thirds"},
	{char: "¼", name: "사분의 일", keywords: "분수 fraction quarter"},
	{char: "¾", name: "사분의 삼", keywords: "분수 fraction three quarters"},
	{char: "⅕", name: "오분의 일", keywords: "분수 fraction fifth"},
	{char: "⅛", name: "팔분의 일", keywords: "분수 fraction eighth"},
	{char: "⅜", name: "팔분의 삼", keywords: "분수 fraction three eighths"},
	{char: "⅚", name: "육분의 오", keywords: "분수 fraction five sixths"},
	{char: "⅞", name: "팔분의 칠", keywords: "분수 fraction seven eighths"},
	{char: "Ⅰ", name: "로마 숫자 1", keywords: "로마 숫자 roman numeral one"},
	{char: "Ⅱ", name: "로마 숫자 2", keywords: "로마 숫자 roman numeral two"},
	{char: "Ⅲ", name: "로마 숫자 3", keywords: "로마 숫자 roman numeral three"},
	{char: "Ⅳ", name: "로마 숫자 4", keywords: "로마 숫자 roman numeral four"},
	{char: "Ⅴ", name: "로마 숫자 5", keywords: "로마 숫자 roman numeral five"},
	{char: "Ⅵ", name: "로마 숫자 6", keywords: "로마 숫자 roman numeral six"},
	{char: "Ⅶ", name: "로마 숫자 7", keywords: "로마 숫자 roman numeral seven"},
	{char: "Ⅷ", name: "로마 숫자 8", keywords: "로마 숫자 roman numeral eight"},
	{char: "Ⅸ", name: "로마 숫자 9", keywords: "로마 숫자 roman numeral nine"},
	{char: "Ⅹ", name: "로마 숫자 10", keywords: "로마 숫자 roman numeral ten"},
	{char: "①", name: "동그라미 숫자 1", keywords: "원문자 동그라미 숫자 circled number 1"},
	{char: "②", name: "동그라미 숫자 2", keywords: "원문자 동그라미 숫자 circled number 2"},
	{char: "③", name: "동그라미 숫자 3", keywords: "원문자 동그라미 숫자 circled number 3"},
	{char: "④", name: "동그라미 숫자 4", keywords: "원문자 동그라미 숫자 circled number 4"},
	{char: "⑤", name: "동그라미 숫자 5", keywords: "원문자 동그라미 숫자 circled number 5"},
	{char: "⑥", name: "동그라미 숫자 6", keywords: "원문자 동그라미 숫자 circled number 6"},
	{char: "⑦", name: "동그라미 숫자 7", keywords: "원문자 동그라미 숫자 circled number 7"},
	{char: "⑧", name: "동그라미 숫자 8", keywords: "원문자 동그라미 숫자 circled number 8"},
	{char: "⑨", name: "동그라미 숫자 9", keywords: "원문자 동그라미 숫자 circled number 9"},
	{char: "⑩", name: "동그라미 숫자 10", keywords: "원문자 동그라미 숫자 circled number 10"},
	{char: "⑪", name: "동그라미 숫자 11", keywords: "원문자 동그라미 숫자 circled number 11"},
	{char: "⑫", name: "동그라미 숫자 12", keywords: "원문자 동그라미 숫자 circled number 12"},
	{char: "⑬", name: "동그라미 숫자 13", keywords: "원문자 동그라미 숫자 circled number 13"},
	{char: "⑭", name: "동그라미 숫자 14", keywords: "원문자 동그라미 숫자 circled number 14"},
	{char: "⑮", name: "동그라미 숫자 15", keywords: "원문자 동그라미 숫자 circled number 15"},
	{char: "⑯", name: "동그라미 숫자 16", keywords: "원문자 동그라미 숫자 circled number 16"},
	{char: "⑰", name: "동그라미 숫자 17", keywords: "원문자 동그라미 숫자 circled number 17"},
	{char: "⑱", name: "동그라미 숫자 18", keywords: "원문자 동그라미 숫자 circled number 18"},
	{char: "⑲", name: "동그라미 숫자 19", keywords: "원문자 동그라미 숫자 circled number 19"},
	{char: "⑳", name: "동그라미 숫자 20", keywords: "원문자 동그라미 숫자 circled number 20"},
	{char: "❶", name: "검은 동그라미 숫자 1", keywords: "원문자 동그라미 숫자 circled number black 1"},
	{char: "❷", name: "검은 동그라미 숫자 2", keywords: "원문자 동그라미 숫자 circled number black 2"},
	{char: "❸", name: "검은 동그라미 숫자 3", keywords: "원문자 동그라미 숫자 circled number black 3"},
	{char: "❹", name: "검은 동그라미 숫자 4", keywords: "원문자 동그라미 숫자 circled number black 4"},
	{char: "❺", name: "검은 동그라미 숫자 5", keywords: "원문자 동그라미 숫자 circled number black 5"},
	{char: "❻", name: "검은 동그라미 숫자 6", keywords: "원문자 동그라미 숫자 circled number black 6"},
	{char: "❼", name: "검은 동그라미 숫자 7", keywords: "원문자 동그라미 숫자 circled number black 7"},
	{char: "❽", name: "검은 동그라미 숫자 8", keywords: "원문자 동그라미 숫자 circled number black 8"},
	{char: "❾", name: "검은 동그라미 숫자 9", keywords: "원문자 동그라미 숫자 circled number black 9"},
	{char: "❿", name: "검은 동그라미 숫자 10", keywords: "원문자 동그라미 숫자 circled number black 10"},
	{char: "⑴", name: "괄호 숫자 1", keywords: "괄호 숫자 parenthesized number 1"},
	{char: "⑵", name: "괄호 숫자 2", keywords: "괄호 숫자 parenthesized number 2"},
	{char: "⑶", name: "괄호 숫자 3", keywords: "괄호 숫자 parenthesized number 3"},
	{char: "⑷", name: "괄호 숫자 4", keywords: "괄호 숫자 parenthesized number 4"},
	{char: "⑸", name: "괄호 숫자 5", keywords: "괄호 숫자 parenthesized number 5"},
	{char: "⑹", name: "괄호 숫자 6", keywords: "괄호 숫자 parenthesized number 6"},
	{char: "⑺", name: "괄호 숫자 7", keywords: "괄호 숫자 parenthesized number 7"},
	{char: "⑻", name: "괄호 숫자 8", keywords: "괄호 숫자 parenthesized number 8"},
	{char: "⑼", name: "괄호 숫자 9", keywords: "괄호 숫자 parenthesized number 9"},
	{char: "⑽", name: "괄호 숫자 10", keywords: "괄호 숫자 parenthesized number 10"},
	{char: "㎜", name: "밀리미터", keywords: "단위 unit millimeter mm"},
	{char: "㎝", name: "센티미터", keywords: "단위 unit centimeter cm"},
	{char: "㎞", name: "킬로미터", keywords: "단위 unit kilometer km"},
	{char: "㎡", name: "제곱미터", keywords: "단위 unit square meter"},
	{char: "㎥", name: "세제곱미터", keywords: "단위 unit cubic meter"},
	{char: "㎏", name: "킬로그램", keywords: "단위 unit kilogram kg"},
	{char: "㎎", name: "밀리그램", keywords: "단위 unit milligram mg"},
	{char: "㎖", name: "밀리리터", keywords: "단위 unit milliliter ml"},
	{char: "㏄", name: "시시", keywords: "단위 unit cc"},
	{char: "㎈", name: "킬로칼로리", keywords: "단위 unit kilocalorie"},
	{char: "℃", name: "섭씨", keywords: "온도 단위 unit celsius degree"},
	{char: "℉", name: "화씨", keywords: "온도 단위 unit fahrenheit degree"},
	{char: "㎐", name: "헤르츠", keywords: "단위 unit hertz hz"},
	{char: "㎅", name: "킬로바이트", keywords: "단위 unit kilobyte kb"},
	{char: "㎆", name: "메가바이트", keywords: "단위 unit megabyte mb"},
	{char: "㎇", name: "기가바이트", keywords: "단위 unit gigabyte gb"},
	{char: "㎾", name: "킬로와트", keywords: "단위 unit kilowatt kw"},
	{char: "㏈", name: "데시벨", keywords: "단위 unit decibel db"},
	{char: "㎳", name: "밀리초", keywords: "단위 unit millisecond ms"},
	{char: "㎲", name: "마이크로초", keywords: "단위 unit microsecond"},
	{char: "㉠", name: "동그라미 ㄱ", keywords: "원문자 동그라미 한글 자음 circled hangul ㄱ"},
	{char: "㉡", name: "동그라미 ㄴ", keywords: "원문자 동그라미 한글 자음 circled hangul ㄴ"},
	{char: "㉢", name: "동그라미 ㄷ", keywords: "원문자 동그라미 한글 자음 circled hangul ㄷ"},
	{char: "㉣", name: "동그라미 ㄹ", keywords: "원문자 동그라미 한글 자음 circled hangul ㄹ"},
	{char: "㉤", name: "동그라미 ㅁ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅁ"},
	{char: "㉥", name: "동그라미 ㅂ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅂ"},
	{char: "㉦", name: "동그라미 ㅅ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅅ"},
	{char: "㉧", name: "동그라미 ㅇ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅇ"},
	{char: "㉨", name: "동그라미 ㅈ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅈ"},
	{char: "㉩", name: "동그라미 ㅊ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅊ"},
	{char: "㉪", name: "동그라미 ㅋ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅋ"},
	{char: "㉫", name: "동그라미 ㅌ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅌ"},
	{char: "㉬", name: "동그라미 ㅍ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅍ"},
	{char: "㉭", name: "동그라미 ㅎ", keywords: "원문자 동그라미 한글 자음 circled hangul ㅎ"},
	{char: "㉮", name: "동그라미 가", keywords: "원문자 동그라미 한글 circled hangul 가"},
	{char: "㉯", name: "동그라미 나", keywords: "원문자 동그라미 한글 circled hangul 나"},
	{char: "㉰", name: "동그라미 다", keywords: "원문자 동그라미 한글 circled hangul 다"},
	{char: "㉱", name: "동그라미 라", keywords: "원문자 동그라미 한글 circled hangul 라"},
	{char: "㉲", name: "동그라미 마", keywords: "원문자 동그라미 한글 circled hangul 마"},
	{char: "㉳", name: "동그라미 바", keywords: "원문자 동그라미 한글 circled hangul 바"},
	{char: "㉴", name: "동그라미 사", keywords: "원문자 동그라미 한글 circled hangul 사"},
	{char: "㉵", name: "동그라미 아", keywords: "원문자 동그라미 한글 circled hangul 아"},
	{char: "㉶", name: "동그라미 자", keywords: "원문자 동그라미 한글 circled hangul 자"},
	{char: "㉷", name: "동그라미 차", keywords: "원문자 동그라미 한글 circled hangul 차"},
	{char: "㉸", name: "동그라미 카", keywords: "원문자 동그라미 한글 circled hangul 카"},
	{char: "㉹", name: "동그라미 타", keywords: "원문자 동그라미 한글 circled hangul 타"},
	{char: "㉺", name: "동그라미 파", keywords: "원문자 동그라미 한글 circled hangul 파"},
	{char: "㉻", name: "동그라미 하", keywords: "원문자 동그라미 한글 circled hangul 하"},
	{char: "㈀", name: "괄호 ㄱ", keywords: "괄호 한글 자음 parenthesized hangul ㄱ"},
	{char: "㈁", name: "괄호 ㄴ", keywords: "괄호 한글 자음 parenthesized hangul ㄴ"},
	{char: "㈂", name: "괄호 ㄷ", keywords: "괄호 한글 자음 parenthesized hangul ㄷ"},
	{char: "㈃", name: "괄호 ㄹ", keywords: "괄호 한글 자음 parenthesized hangul ㄹ"},
	{char: "㈄", name: "괄호 ㅁ", keywords: "괄호 한글 자음 parenthesized hangul ㅁ"},
	{char: "㈅", name: "괄호 ㅂ", keywords: "괄호 한글 자음 parenthesized hangul ㅂ"},
	{char: "㈆", name: "괄호 ㅅ", keywords: "괄호 한글 자음 parenthesized hangul ㅅ"},
	{char: "㈇", name: "괄호 ㅇ", keywords: "괄호 한글 자음 parenthesized hangul ㅇ"},
	{char: "㈈", name: "괄호 ㅈ", keywords: "괄호 한글 자음 parenthesized hangul ㅈ"},
	{char: "㈉", name: "괄호 ㅊ", keywords: "괄호 한글 자음 parenthesized hangul ㅊ"},
	{char: "㈊", name: "괄호 ㅋ", keywords: "괄호 한글 자음 parenthesized hangul ㅋ"},
	{char: "㈋", name: "괄호 ㅌ", keywords: "괄호 한글 자음 parenthesized hangul ㅌ"},
	{char: "㈌", name: "괄호 ㅍ", keywords: "괄호 한글 자음 parenthesized hangul ㅍ"},
	{char: "㈍", name: "괄호 ㅎ", keywords: "괄호 한글 자음 parenthesized hangul ㅎ"},
	{char: "㈎", name: "괄호 가", keywords: "괄호 한글 parenthesized hangul 가"},
	{char: "㈏", name: "괄호 나", keywords: "괄호 한글 parenthesized hangul 나"},
	{char: "㈐", name: "괄호 다", keywords: "괄호 한글 parenthesized hangul 다"},
	{char: "㈑", name: "괄호 라", keywords: "괄호 한글 parenthesized hangul 라"},
	{char: "㈒", name: "괄호 마", keywords: "괄호 한글 parenthesized hangul 마"},
	{char: "㈓", name: "괄호 바", keywords: "괄호 한글 parenthesized hangul 바"},
	{char: "㈔", name: "괄호 사", keywords: "괄호 한글 parenthesized hangul 사"},
	{char: "㈕", name: "괄호 아", keywords: "괄호 한글 parenthesized hangul 아"},
	{char: "㈖", name: "괄호 자", keywords: "괄호 한글 parenthesized hangul 자"},
	{char: "㈗", name: "괄호 차", keywords: "괄호 한글 parenthesized hangul 차"},
	{char: "㈘", name: "괄호 카", keywords: "괄호 한글 parenthesized hangul 카"},
	{char: "㈙", name: "괄호 타", keywords: "괄호 한글 parenthesized hangul 타"},
	{char: "㈚", name: "괄호 파", keywords: "괄호 한글 parenthesized hangul 파"},
	{char: "㈛", name: "괄호 하", keywords: "괄호 한글 parenthesized hangul 하"},

	// 이모지 표정 (emoji face)
	{char: "😀", name: "활짝 웃는 얼굴", keywords: "이모지 표정 웃음 grinning face"},
	{char: "😃", name: "눈웃음 짓는 얼굴", keywords: "이모지 표정 웃음 grinning big eyes"},
	{char: "😄", name: "웃으며 눈웃음 짓는 얼굴", keywords: "이모지 표정 웃음 grinning smiling eyes"},
	{char: "😁", name: "활짝 웃으며 눈웃음", keywords: "이모지 표정 웃음 beaming face"},
	{char: "😆", name: "눈 감고 크게 웃는 얼굴", keywords: "이모지 표정 웃음 grinning squinting"},
	{char: "😅", name: "식은땀 흘리며 웃는 얼굴", keywords: "이모지 표정 웃음 땀 grinning sweat"},
	{char: "🤣", name: "바닥을 구르며 웃는 얼굴", keywords: "이모지 표정 웃음 rolling on the floor laughing"},
	{char: "😂", name: "눈물 나게 웃는 얼굴", keywords: "이모지 표정 웃음 눈물 tears of joy"},
	{char: "🙂", name: "살짝 웃는 얼굴", keywords: "이모지 표정 웃음 slightly smiling"},
	{char: "🙃", name: "거꾸로 된 얼굴", keywords: "이모지 표정 upside down face"},
	{char: "😉", name: "윙크하는 얼굴", keywords: "이모지 표정 winking face"},
	{char: "😊", name: "활짝 웃는 눈웃음 얼굴", keywords: "이모지 표정 웃음 smiling eyes"},
	{char: "😇", name: "천사 얼굴", keywords: "이모지 표정 halo angel"},
	{char: "🥰", name: "하트에 둘러싸인 얼굴", keywords: "이모지 표정 사랑 smiling hearts"},
	{char: "😍", name: "하트 눈 얼굴", keywords: "이모지 표정 사랑 heart eyes"},
	{char: "🤩", name: "별 눈 얼굴", keywords: "이모지 표정 star struck"},
	{char: "😘", name: "뽀뽀하는 얼굴", keywords: "이모지 표정 사랑 blowing a kiss"},
	{char: "😗", name: "입 오므린 얼굴", keywords: "이모지 표정 kissing face"},
	{char: "😚", name: "눈 감고 뽀뽀하는 얼굴", keywords: "이모지 표정 kissing closed eyes"},
	{char: "😙", name: "웃으며 뽀뽀하는 얼굴", keywords: "이모지 표정 kissing smiling eyes"},
	{char: "😋", name: "맛있는 얼굴", keywords: "이모지 표정 savoring food yum"},
	{char: "😛", name: "혀 내민 얼굴", keywords: "이모지 표정 tongue out"},
	{char: "😜", name: "윙크하며 혀 내민 얼굴", keywords: "이모지 표정 winking tongue"},
	{char: "🤪", name: "엉뚱한 얼굴", keywords: "이모지 표정 zany face"},
	{char: "😝", name: "눈 감고 혀 내민 얼굴", keywords: "이모지 표정 squinting tongue"},
	{char: "🤑", name: "돈 좋아하는 얼굴", keywords: "이모지 표정 돈 money mouth"},
	{char: "🤗", name: "안아주는 얼굴", keywords: "이모지 표정 hugging face"},
	{char: "🤭", name: "입 가린 얼굴", keywords: "이모지 표정 hand over mouth"},
	{char: "🤫", name: "조용히 하라는 얼굴", keywords: "이모지 표정 shushing face"},
	{char: "🤔", name: "생각하는 얼굴", keywords: "이모지 표정 thinking face"},
	{char: "🤐", name: "입 지퍼 얼굴", keywords: "이모지 표정 zipper mouth"},
	{char: "🤨", name: "눈썹 치켜올린 얼굴", keywords: "이모지 표정 raised eyebrow"},
	{char: "😐", name: "무표정한 얼굴", keywords: "이모지 표정 neutral face"},
	{char: "😑", name: "심드렁한 얼굴", keywords: "이모지 표정 expressionless"},
	{char: "😶", name: "입 없는 얼굴", keywords: "이모지 표정 no mouth"},
	{char: "😏", name: "능글맞은 얼굴", keywords: "이모지 표정 smirking face"},
	{char: "😒", name: "떨떠름한 얼굴", keywords: "이모지 표정 unamused face"},
	{char: "🙄", name: "눈 굴리는 얼굴", keywords: "이모지 표정 rolling eyes"},
	{char: "😬", name: "이 드러낸 얼굴", keywords: "이모지 표정 grimacing face"},
	{char: "🤥", name: "거짓말하는 얼굴", keywords: "이모지 표정 lying face"},
	{char: "😌", name: "안도하는 얼굴", keywords: "이모지 표정 relieved face"},
	{char: "😔", name: "시무룩한 얼굴", keywords: "이모지 표정 pensive face"},
	{char: "😪", name: "졸린 얼굴", keywords: "이모지 표정 sleepy face"},
	{char: "🤤", name: "침 흘리는 얼굴", keywords: "이모지 표정 drooling face"},
	{char: "😴", name: "자는 얼굴", keywords: "이모지 표정 sleeping face"},
	{char: "😷", name: "마스크 쓴 얼굴", keywords: "이모지 표정 medical mask"},
	{char: "🤒", name: "체온계 문 얼굴", keywords: "이모지 표정 face with thermometer"},
	{char: "🤕", name: "머리 다친 얼굴", keywords: "이모지 표정 head bandage"},
	{char: "🤢", name: "메스꺼운 얼굴", keywords: "이모지 표정 nauseated face"},
	{char: "🤮", name: "토하는 얼굴", keywords: "이모지 표정 vomiting face"},
	{char: "🤧", name: "재채기하는 얼굴", keywords: "이모지 표정 sneezing face"},
	{char: "🥵", name: "더워하는 얼굴", keywords: "이모지 표정 hot face"},
	{char: "🥶", name: "추워하는 얼굴", keywords: "이모지 표정 cold face"},
	{char: "😵", name: "어지러운 얼굴", keywords: "이모지 표정 dizzy face"},
	{char: "🤯", name: "머리 터지는 얼굴", keywords: "이모지 표정 exploding head"},
	{char: "🤠", name: "카우보이 얼굴", keywords: "이모지 표정 cowboy hat"},
	{char: "🥳", name: "파티하는 얼굴", keywords: "이모지 표정 partying face"},
	{char: "😎", name: "선글라스 낀 얼굴", keywords: "이모지 표정 sunglasses cool"},
	{char: "🤓", name: "안경 쓴 얼굴", keywords: "이모지 표정 nerd face"},
	{char: "🧐", name: "외알 안경 얼굴", keywords: "이모지 표정 monocle"},
	{char: "😕", name: "헷갈리는 얼굴", keywords: "이모지 표정 confused face"},
	{char: "😟", name: "걱정하는 얼굴", keywords: "이모지 표정 worried face"},
	{char: "🙁", name: "살짝 찡그린 얼굴", keywords: "이모지 표정 slightly frowning"},
	{char: "😮", name: "입 벌린 얼굴", keywords: "이모지 표정 open mouth"},
	{char: "😯", name: "놀란 얼굴", keywords: "이모지 표정 hushed face"},
	{char: "😲", name: "깜짝 놀란 얼굴", keywords: "이모지 표정 astonished face"},
	{char: "😳", name: "얼굴 붉힌 얼굴", keywords: "이모지 표정 flushed face"},
	{char: "🥺", name: "애원하는 얼굴", keywords: "이모지 표정 pleading face"},
	{char: "😦", name: "찡그리며 입 벌린 얼굴", keywords: "이모지 표정 frowning open mouth"},
	{char: "😨", name: "겁먹은 얼굴", keywords: "이모지 표정 fearful face"},
	{char: "😰", name: "식은땀 흘리는 얼굴", keywords: "이모지 표정 땀 anxious sweat"},
	{char: "😥", name: "슬픈 안도의 얼굴", keywords: "이모지 표정 sad but relieved"},
	{char: "😢", name: "우는 얼굴", keywords: "이모지 표정 눈물 crying face"},
	{char: "😭", name: "엉엉 우는 얼굴", keywords: "이모지 표정 눈물 loudly crying"},
	{char: "😱", name: "비명 지르는 얼굴", keywords: "이모지 표정 screaming in fear"},
	{char: "😖", name: "괴로운 얼굴", keywords: "이모지 표정 confounded face"},
	{char: "😣", name: "참고 있는 얼굴", keywords: "이모지 표정 persevering face"},
	{char: "😞", name: "실망한 얼굴", keywords: "이모지 표정 disappointed face"},
	{char: "😓", name: "식은땀 흘리며 낙담", keywords: "이모지 표정 땀 downcast sweat"},
	{char: "😩", name: "지친 얼굴", keywords: "이모지 표정 weary face"},
	{char: "😫", name: "진저리 나는 얼굴", keywords: "이모지 표정 tired face"},
	{char: "🥱", name: "하품하는 얼굴", keywords: "이모지 표정 yawning face"},
	{char: "😤", name: "씩씩대는 얼굴", keywords: "이모지 표정 face with steam"},
	{char: "😡", name: "화난 붉은 얼굴", keywords: "이모지 표정 화 pouting face"},
	{char: "😠", name: "화난 얼굴", keywords: "이모지 표정 화 angry face"},
	{char: "🤬", name: "욕하는 얼굴", keywords: "이모지 표정 화 cursing face"},
	{char: "😈", name: "뿔 달린 웃는 얼굴", keywords: "이모지 표정 devil smiling horns"},
	{char: "👿", name: "뿔 달린 화난 얼굴", keywords: "이모지 표정 angry devil"},
	{char: "💀", name: "해골", keywords: "이모지 죽음 skull"},
	{char: "💩", name: "똥", keywords: "이모지 poop"},
	{char: "🤡", name: "광대", keywords: "이모지 표정 clown face"},
	{char: "👻", name: "유령", keywords: "이모지 ghost"},
	{char: "👽", name: "외계인", keywords: "이모지 alien"},
	{char: "🤖", name: "로봇", keywords: "이모지 robot"},
	{char: "😺", name: "웃는 고양이", keywords: "이모지 고양이 grinning cat"},
	{char: "😻", name: "하트 눈 고양이", keywords: "이모지 고양이 heart eyes cat"},
	{char: "😹", name: "눈물 나게 웃는 고양이", keywords: "이모지 고양이 cat tears of joy"},
	{char: "🙀", name: "놀란 고양이", keywords: "이모지 고양이 weary cat"},
	{char: "😿", name: "우는 고양이", keywords: "이모지 고양이 crying cat"},
	{char: "🙈", name: "눈 가린 원숭이", keywords: "이모지 원숭이 see no evil monkey"},
	{char: "🙉", name: "귀 막은 원숭이", keywords: "이모지 원숭이 hear no evil monkey"},
	{char: "🙊", name: "입 막은 원숭이", keywords: "이모지 원숭이 speak no evil monkey"},

	// 이모지 손과 사람 (emoji hand and person)
	{char: "👍", name: "엄지척", keywords: "이모지 손 좋아요 thumbs up"},
	{char: "👎", name: "엄지 아래", keywords: "이모지 손 싫어요 thumbs down"},
	{char: "👌", name: "오케이 손", keywords: "이모지 손 ok hand"},
	{char: "✌", name: "브이", keywords: "이모지 손 victory hand peace"},
	{char: "🤞", name: "행운을 비는 손", keywords: "이모지 손 crossed fingers"},
	{char: "🤟", name: "사랑해 손", keywords: "이모지 손 love you gesture"},
	{char: "🤘", name: "뿔 손", keywords: "이모지 손 sign of the horns"},
	{char: "🤙", name: "전화해 손", keywords: "이모지 손 call me hand"},
	{char: "👈", name: "왼쪽 가리키는 손", keywords: "이모지 손 backhand index left"},
	{char: "👉", name: "오른쪽 가리키는 손", keywords: "이모지 손 backhand index right"},
	{char: "👆", name: "위 가리키는 손", keywords: "이모지 손 backhand index up"},
	{char: "👇", name: "아래 가리키는 손", keywords: "이모지 손 backhand index down"},
	{char: "✋", name: "든 손", keywords: "이모지 손 raised hand"},
	{char: "🤚", name: "손등", keywords: "이모지 손 raised back of hand"},
	{char: "🖐", name: "손가락 편 손", keywords: "이모지 손 hand with fingers splayed"},
	{char: "🖖", name: "벌칸 인사", keywords: "이모지 손 vulcan salute"},
	{char: "👋", name: "흔드는 손", keywords: "이모지 손 인사 waving hand"},
	{char: "🤏", name: "조금", keywords: "이모지 손 pinching hand"},
	{char: "✊", name: "주먹", keywords: "이모지 손 raised fist"},
	{char: "👊", name: "앞으로 내민 주먹", keywords: "이모지 손 oncoming fist"},
	{char: "🤛", name: "왼쪽 주먹", keywords: "이모지 손 left facing fist"},
	{char: "🤜", name: "오른쪽 주먹", keywords: "이모지 손 right facing fist"},
	{char: "👏", name: "박수", keywords: "이모지 손 clapping hands"},
	{char: "🙌", name: "두 손 들기", keywords: "이모지 손 raising hands"},
	{char: "👐", name: "벌린 두 손", keywords: "이모지 손 open hands"},
	{char: "🤲", name: "받치는 두 손", keywords: "이모지 손 palms up together"},
	{char: "🤝", name: "악수", keywords: "이모지 손 handshake"},
	{char: "🙏", name: "기도하는 손", keywords: "이모지 손 감사 folded hands please thanks"},
	{char: "💅", name: "매니큐어", keywords: "이모지 손 nail polish"},
	{char: "💪", name: "알통", keywords: "이모지 근육 flexed biceps muscle"},
	{char: "👀", name: "두 눈", keywords: "이모지 눈 eyes"},
	{char: "👁", name: "눈", keywords: "이모지 눈 eye"},
	{char: "👂", name: "귀", keywords: "이모지 ear"},
	{char: "👃", name: "코", keywords: "이모지 nose"},
	{char: "👄", name: "입술", keywords: "이모지 mouth lips"},
	{char: "👅", name: "혀", keywords: "이모지 tongue"},
	{char: "🦷", name: "이", keywords: "이모지 tooth"},
	{char: "🧠", name: "뇌", keywords: "이모지 brain"},
	{char: "🦴", name: "뼈", keywords: "이모지 bone"},
	{char: "👶", name: "아기", keywords: "이모지 사람 baby"},
	{char: "🧒", name: "아이", keywords: "이모지 사람 child"},
	{char: "👦", name: "남자아이", keywords: "이모지 사람 boy"},
	{char: "👧", name: "여자아이", keywords: "이모지 사람 girl"},
	{char: "🧑", name: "사람", keywords: "이모지 사람 person adult"},
	{char: "👨", name: "남자", keywords: "이모지 사람 man"},
	{char: "👩", name: "여자", keywords: "이모지 사람 woman"},
	{char: "🧓", name: "노인", keywords: "이모지 사람 older person"},
	{char: "👴", name: "할아버지", keywords: "이모지 사람 old man"},
	{char: "👵", name: "할머니", keywords: "이모지 사람 old woman"},
	{char: "🙋", name: "손 든 사람", keywords: "이모지 사람 person raising hand"},
	{char: "🙇", name: "절하는 사람", keywords: "이모지 사람 person bowing"},
	{char: "🤦", name: "이마 짚는 사람", keywords: "이모지 사람 person facepalming"},
	{char: "🤷", name: "어깨 으쓱", keywords: "이모지 사람 person shrugging"},
	{char: "💁", name: "안내하는 사람", keywords: "이모지 사람 person tipping hand"},
	{char: "🙅", name: "안 된다는 사람", keywords: "이모지 사람 person gesturing no"},
	{char: "🙆", name: "된다는 사람", keywords: "이모지 사람 person gesturing ok"},
	{char: "🚶", name: "걷는 사람", keywords: "이모지 사람 person walking"},
	{char: "🏃", name: "달리는 사람", keywords: "이모지 사람 person running"},
	{char: "💃", name: "춤추는 여자", keywords: "이모지 사람 woman dancing"},
	{char: "🕺", name: "춤추는 남자", keywords: "이모지 사람 man dancing"},
	{char: "👮", name: "경찰관", keywords: "이모지 사람 police officer"},
	{char: "👷", name: "건설 노동자", keywords: "이모지 사람 construction worker"},
	{char: "💂", name: "근위병", keywords: "이모지 사람 guard"},
	{char: "🕵", name: "탐정", keywords: "이모지 사람 detective"},
	{char: "👨‍💻", name: "개발자", keywords: "이모지 사람 technologist developer programmer"},
	{char: "👩‍💻", name: "여성 개발자", keywords: "이모지 사람 woman technologist developer"},
	{char: "🧑‍🍳", name: "요리사", keywords: "이모지 사람 cook chef"},
	{char: "🧑‍🎓", name: "학생", keywords: "이모지 사람 student"},
	{char: "🧑‍🏫", name: "선생님", keywords: "이모지 사람 teacher"},
	{char: "🧑‍⚕", name: "의료인", keywords: "이모지 사람 health worker doctor"},
	{char: "🎅", name: "산타클로스", keywords: "이모지 사람 크리스마스 santa claus"},
	{char: "🦸", name: "슈퍼히어로", keywords: "이모지 사람 superhero"},
	{char: "🧙", name: "마법사", keywords: "이모지 사람 mage wizard"},
	{char: "🧚", name: "요정", keywords: "이모지 사람 fairy"},
	{char: "👯", name: "토끼 귀 사람", keywords: "이모지 사람 people with bunny ears"},
	{char: "👪", name: "가족", keywords: "이모지 사람 family"},
	{char: "👫", name: "손잡은 남녀", keywords: "이모지 사람 woman and man holding hands"},
	{char: "💏", name: "키스하는 사람들", keywords: "이모지 사람 kiss"},
	{char: "💑", name: "사랑하는 사람들", keywords: "이모지 사람 couple with heart"},
	{char: "👤", name: "실루엣", keywords: "이모지 사람 bust in silhouette"},
	{char: "👥", name: "실루엣 둘", keywords: "이모지 사람 busts in silhouette"},
	{char: "🗣", name: "말하는 얼굴", keywords: "이모지 사람 speaking head"},
	{char: "🦶", name: "발", keywords: "이모지 foot"},
	{char: "🦵", name: "다리", keywords: "이모지 leg"},

	// 이모지 감정과 기호 (emoji heart and symbol)
	{char: "❤", name: "빨간 하트", keywords: "이모지 하트 사랑 red heart"},
	{char: "🧡", name: "주황 하트", keywords: "이모지 하트 사랑 orange heart"},
	{char: "💛", name: "노란 하트", keywords: "이모지 하트 사랑 yellow heart"},
	{char: "💚", name: "초록 하트", keywords: "이모지 하트 사랑 green heart"},
	{char: "💙", name: "파란 하트", keywords: "이모지 하트 사랑 blue heart"},
	{char: "💜", name: "보라 하트", keywords: "이모지 하트 사랑 purple heart"},
	{char: "🖤", name: "검은 하트", keywords: "이모지 하트 사랑 black heart"},
	{char: "🤍", name: "흰 하트", keywords: "이모지 하트 사랑 white heart"},
	{char: "🤎", name: "갈색 하트", keywords: "이모지 하트 사랑 brown heart"},
	{char: "💔", name: "깨진 하트", keywords: "이모지 하트 이별 broken heart"},
	{char: "❣", name: "느낌표 하트", keywords: "이모지 하트 heart exclamation"},
	{char: "💕", name: "하트 두 개", keywords: "이모지 하트 사랑 two hearts"},
	{char: "💞", name: "도는 하트", keywords: "이모지 하트 사랑 revolving hearts"},
	{char: "💓", name: "뛰는 하트", keywords: "이모지 하트 사랑 beating heart"},
	{char: "💗", name: "커지는 하트", keywords: "이모지 하트 사랑 growing heart"},
	{char: "💖", name: "반짝이는 하트", keywords: "이모지 하트 사랑 sparkling heart"},
	{char: "💘", name: "화살 꽂힌 하트", keywords: "이모지 하트 사랑 heart with arrow cupid"},
	{char: "💝", name: "리본 달린 하트", keywords: "이모지 하트 선물 heart with ribbon"},
	{char: "💟", name: "하트 장식", keywords: "이모지 하트 heart decoration"},
	{char: "💌", name: "연애편지", keywords: "이모지 하트 love letter"},
	{char: "💋", name: "입술 자국", keywords: "이모지 뽀뽀 kiss mark"},
	{char: "💯", name: "백점", keywords: "이모지 hundred points"},
	{char: "💢", name: "분노 표시", keywords: "이모지 화 anger symbol"},
	{char: "💥", name: "충돌", keywords: "이모지 collision boom"},
	{char: "💫", name: "어지러움", keywords: "이모지 별 dizzy star"},
	{char: "💦", name: "땀방울", keywords: "이모지 땀 sweat droplets"},
	{char: "💨", name: "쌩", keywords: "이모지 dashing away"},
	{char: "🕳", name: "구멍", keywords: "이모지 hole"},
	{char: "💣", name: "폭탄", keywords: "이모지 bomb"},
	{char: "💬", name: "말풍선", keywords: "이모지 speech balloon"},
	{char: "💭", name: "생각 풍선", keywords: "이모지 thought balloon"},
	{char: "🗯", name: "분노 풍선", keywords: "이모지 right anger bubble"},
	{char: "💤", name: "잠", keywords: "이모지 zzz sleep"},
	{char: "🔥", name: "불", keywords: "이모지 fire"},
	{char: "⭐", name: "별", keywords: "이모지 별 star"},
	{char: "🌟", name: "반짝이는 별", keywords: "이모지 별 glowing star"},
	{char: "✅", name: "초록 체크", keywords: "이모지 체크 확인 check mark button"},
	{char: "❌", name: "엑스 표시", keywords: "이모지 엑스 취소 cross mark"},
	{char: "❎", name: "엑스 상자", keywords: "이모지 엑스 cross mark button"},
	{char: "➕", name: "더하기", keywords: "이모지 plus"},
	{char: "➖", name: "빼기", keywords: "이모지 minus"},
	{char: "➗", name: "나누기", keywords: "이모지 divide"},
	{char: "❓", name: "물음표", keywords: "이모지 question mark"},
	{char: "❔", name: "흰 물음표", keywords: "이모지 white question mark"},
	{char: "❗", name: "느낌표", keywords: "이모지 exclamation mark"},
	{char: "❕", name: "흰 느낌표", keywords: "이모지 white exclamation mark"},
	{char: "🚫", name: "금지", keywords: "이모지 prohibited no entry"},
	{char: "⛔", name: "진입 금지", keywords: "이모지 no entry"},
	{char: "💡", name: "전구", keywords: "이모지 아이디어 light bulb idea"},
	{char: "🔔", name: "종", keywords: "이모지 알림 bell"},
	{char: "🔕", name: "종 금지", keywords: "이모지 알림 bell with slash mute"},
	{char: "📌", name: "압정", keywords: "이모지 pushpin"},
	{char: "📍", name: "위치 핀", keywords: "이모지 위치 round pushpin location"},
	{char: "🔖", name: "책갈피", keywords: "이모지 bookmark"},
	{char: "🏷", name: "꼬리표", keywords: "이모지 label tag"},
	{char: "🔗", name: "고리", keywords: "이모지 링크 link"},
	{char: "📎", name: "클립", keywords: "이모지 paperclip"},
	{char: "🔒", name: "잠김", keywords: "이모지 locked"},
	{char: "🔓", name: "열림", keywords: "이모지 unlocked"},
	{char: "🔑", name: "열쇠", keywords: "이모지 key"},
	{char: "🔍", name: "돋보기", keywords: "이모지 검색 magnifying glass search"},
	{char: "🔎", name: "오른쪽 돋보기", keywords: "이모지 검색 magnifying glass right"},
	{char: "🔄", name: "순환 화살표", keywords: "이모지 새로고침 counterclockwise arrows refresh"},
	{char: "🔁", name: "반복", keywords: "이모지 repeat"},
	{char: "🔀", name: "섞기", keywords: "이모지 shuffle"},
	{char: "🆗", name: "오케이", keywords: "이모지 ok button"},
	{char: "🆕", name: "새로움", keywords: "이모지 new button"},
	{char: "🆙", name: "업", keywords: "이모지 up button"},
	{char: "🔝", name: "맨 위", keywords: "이모지 top arrow"},
	{char: "🎉", name: "크래커", keywords: "이모지 축하 party popper"},
	{char: "🎊", name: "색종이 공", keywords: "이모지 축하 confetti ball"},
	{char: "🎈", name: "풍선", keywords: "이모지 축하 balloon"},
	{char: "🎁", name: "선물", keywords: "이모지 선물 gift"},
	{char: "🏆", name: "트로피", keywords: "이모지 상 trophy"},
	{char: "🥇", name: "금메달", keywords: "이모지 상 gold medal"},
	{char: "🥈", name: "은메달", keywords: "이모지 상 silver medal"},
	{char: "🥉", name: "동메달", keywords: "이모지 상 bronze medal"},
	{char: "🎯", name: "과녁", keywords: "이모지 목표 direct hit target"},
	{char: "🚀", name: "로켓", keywords: "이모지 rocket"},
	{char: "💎", name: "보석", keywords: "이모지 gem stone diamond"},
	{char: "👑", name: "왕관", keywords: "이모지 crown"},

	// 이모지 동물과 자연 (emoji animal and nature)
	{char: "🐶", name: "강아지 얼굴", keywords: "이모지 동물 개 dog face"},
	{char: "🐕", name: "개", keywords: "이모지 동물 dog"},
	{char: "🐱", name: "고양이 얼굴", keywords: "이모지 동물 고양이 cat face"},
	{char: "🐈", name: "고양이", keywords: "이모지 동물 cat"},
	{char: "🐭", name: "쥐 얼굴", keywords: "이모지 동물 mouse face"},
	{char: "🐹", name: "햄스터", keywords: "이모지 동물 hamster"},
	{char: "🐰", name: "토끼 얼굴", keywords: "이모지 동물 rabbit face"},
	{char: "🦊", name: "여우", keywords: "이모지 동물 fox"},
	{char: "🐻", name: "곰", keywords: "이모지 동물 bear"},
	{char: "🐼", name: "판다", keywords: "이모지 동물 panda"},
	{char: "🐨", name: "코알라", keywords: "이모지 동물 koala"},
	{char: "🐯", name: "호랑이 얼굴", keywords: "이모지 동물 tiger face"},
	{char: "🦁", name: "사자", keywords: "이모지 동물 lion"},
	{char: "🐮", name: "소 얼굴", keywords: "이모지 동물 cow face"},
	{char: "🐷", name: "돼지 얼굴", keywords: "이모지 동물 pig face"},
	{char: "🐽", name: "돼지 코", keywords: "이모지 동물 pig nose"},
	{char: "🐸", name: "개구리", keywords: "이모지 동물 frog"},
	{char: "🐵", name: "원숭이 얼굴", keywords: "이모지 동물 monkey face"},
	{char: "🐒", name: "원숭이", keywords: "이모지 동물 monkey"},
	{char: "🐔", name: "닭", keywords: "이모지 동물 chicken"},
	{char: "🐧", name: "펭귄", keywords: "이모지 동물 penguin"},
	{char: "🐦", name: "새", keywords: "이모지 동물 bird"},
	{char: "🐤", name: "병아리", keywords: "이모지 동물 baby chick"},
	{char: "🦆", name: "오리", keywords: "이모지 동물 duck"},
	{char: "🦅", name: "독수리", keywords: "이모지 동물 eagle"},
	{char: "🦉", name: "올빼미", keywords: "이모지 동물 owl"},
	{char: "🦇", name: "박쥐", keywords: "이모지 동물 bat"},
	{char: "🐺", name: "늑대", keywords: "이모지 동물 wolf"},
	{char: "🐗", name: "멧돼지", keywords: "이모지 동물 boar"},
	{char: "🐴", name: "말 얼굴", keywords: "이모지 동물 horse face"},
	{char: "🦄", name: "유니콘", keywords: "이모지 동물 unicorn"},
	{char: "🐝", name: "꿀벌", keywords: "이모지 동물 honeybee"},
	{char: "🐛", name: "애벌레", keywords: "이모지 동물 bug caterpillar"},
	{char: "🦋", name: "나비", keywords: "이모지 동물 butterfly"},
	{char: "🐌", name: "달팽이", keywords: "이모지 동물 snail"},
	{char: "🐞", name: "무당벌레", keywords: "이모지 동물 lady beetle"},
	{char: "🐜", name: "개미", keywords: "이모지 동물 ant"},
	{char: "🕷", name: "거미", keywords: "이모지 동물 spider"},
	{char: "🕸", name: "거미줄", keywords: "이모지 spider web"},
	{char: "🦂", name: "전갈", keywords: "이모지 동물 scorpion"},
	{char: "🐢", name: "거북", keywords: "이모지 동물 turtle"},
	{char: "🐍", name: "뱀", keywords: "이모지 동물 snake"},
	{char: "🦎", name: "도마뱀", keywords: "이모지 동물 lizard"},
	{char: "🐙", name: "문어", keywords: "이모지 동물 octopus"},
	{char: "🦑", name: "오징어", keywords: "이모지 동물 squid"},
	{char: "🦐", name: "새우", keywords: "이모지 동물 shrimp"},
	{char: "🦀", name: "게", keywords: "이모지 동물 crab"},
	{char: "🐡", name: "복어", keywords: "이모지 동물 blowfish"},
	{char: "🐠", name: "열대어", keywords: "이모지 동물 tropical fish"},
	{char: "🐟", name: "물고기", keywords: "이모지 동물 fish"},
	{char: "🐬", name: "돌고래", keywords: "이모지 동물 dolphin"},
	{char: "🐳", name: "고래", keywords: "이모지 동물 whale"},
	{char: "🦈", name: "상어", keywords: "이모지 동물 shark"},
	{char: "🐊", name: "악어", keywords: "이모지 동물 crocodile"},
	{char: "🐘", name: "코끼리", keywords: "이모지 동물 elephant"},
	{char: "🦏", name: "코뿔소", keywords: "이모지 동물 rhinoceros"},
	{char: "🐪", name: "낙타", keywords: "이모지 동물 camel"},
	{char: "🦒", name: "기린", keywords: "이모지 동물 giraffe"},
	{char: "🐇", name: "토끼", keywords: "이모지 동물 rabbit"},
	{char: "🐿", name: "다람쥐", keywords: "이모지 동물 chipmunk"},
	{char: "🦔", name: "고슴도치", keywords: "이모지 동물 hedgehog"},
	{char: "🐾", name: "발자국", keywords: "이모지 동물 paw prints"},
	{char: "🌸", name: "벚꽃", keywords: "이모지 꽃 cherry blossom"},
	{char: "💮", name: "흰 꽃", keywords: "이모지 꽃 white flower"},
	{char: "🌹", name: "장미", keywords: "이모지 꽃 rose"},
	{char: "🥀", name: "시든 꽃", keywords: "이모지 꽃 wilted flower"},
	{char: "🌺", name: "무궁화", keywords: "이모지 꽃 hibiscus"},
	{char: "🌻", name: "해바라기", keywords: "이모지 꽃 sunflower"},
	{char: "🌼", name: "블로섬", keywords: "이모지 꽃 blossom"},
	{char: "🌷", name: "튤립", keywords: "이모지 꽃 tulip"},
	{char: "🌱", name: "새싹", keywords: "이모지 식물 seedling"},
	{char: "🌲", name: "침엽수", keywords: "이모지 나무 evergreen tree"},
	{char: "🌳", name: "활엽수", keywords: "이모지 나무 deciduous tree"},
	{char: "🌴", name: "야자수", keywords: "이모지 나무 palm tree"},
	{char: "🌵", name: "선인장", keywords: "이모지 식물 cactus"},
	{char: "🍀", name: "네잎클로버", keywords: "이모지 행운 four leaf clover"},
	{char: "🍁", name: "단풍잎", keywords: "이모지 잎 maple leaf"},
	{char: "🍂", name: "낙엽", keywords: "이모지 잎 fallen leaf"},
	{char: "🍃", name: "바람에 날리는 잎", keywords: "이모지 잎 leaf fluttering"},
	{char: "🌾", name: "벼", keywords: "이모지 식물 sheaf of rice"},
	{char: "🌍", name: "지구 유럽아프리카", keywords: "이모지 지구 globe europe africa"},
	{char: "🌏", name: "지구 아시아", keywords: "이모지 지구 globe asia australia"},
	{char: "🌎", name: "지구 아메리카", keywords: "이모지 지구 globe americas"},
	{char: "🌕", name: "보름달", keywords: "이모지 달 full moon"},
	{char: "🌑", name: "삭", keywords: "이모지 달 new moon"},
	{char: "🌙", name: "초승달", keywords: "이모지 달 crescent moon"},
	{char: "🌛", name: "웃는 상현달", keywords: "이모지 달 first quarter moon face"},
	{char: "🌞", name: "웃는 해", keywords: "이모지 날씨 sun with face"},
	{char: "⛅", name: "구름 낀 해", keywords: "이모지 날씨 sun behind cloud"},
	{char: "🌧", name: "비 오는 구름", keywords: "이모지 날씨 비 cloud with rain"},
	{char: "⛈", name: "번개 치는 구름", keywords: "이모지 날씨 cloud with lightning rain"},
	{char: "🌩", name: "번개", keywords: "이모지 날씨 cloud with lightning"},
	{char: "⛄", name: "눈사람 없는 눈", keywords: "이모지 날씨 눈 snowman without snow"},
	{char: "🌈", name: "무지개", keywords: "이모지 날씨 rainbow"},
	{char: "🌊", name: "파도", keywords: "이모지 물 water wave"},
	{char: "💧", name: "물방울", keywords: "이모지 물 droplet"},
	{char: "🌋", name: "화산", keywords: "이모지 자연 volcano"},
	{char: "⛰", name: "산", keywords: "이모지 자연 mountain"},
	{char: "🏔", name: "눈 덮인 산", keywords: "이모지 자연 snow capped mountain"},
	{char: "🌅", name: "일출", keywords: "이모지 자연 sunrise"},
	{char: "🌄", name: "산 위 일출", keywords: "이모지 자연 sunrise over mountains"},
	{char: "🌇", name: "일몰", keywords: "이모지 자연 sunset"},
	{char: "🌌", name: "은하수", keywords: "이모지 자연 milky way"},

	// 이모지 음식 (emoji food)
	{char: "🍎", name: "빨간 사과", keywords: "이모지 음식 과일 red apple"},
	{char: "🍏", name: "초록 사과", keywords: "이모지 음식 과일 green apple"},
	{char: "🍐", name: "배", keywords: "이모지 음식 과일 pear"},
	{char: "🍊", name: "귤", keywords: "이모지 음식 과일 tangerine orange"},
	{char: "🍋", name: "레몬", keywords: "이모지 음식 과일 lemon"},
	{char: "🍌", name: "바나나", keywords: "이모지 음식 과일 banana"},
	{char: "🍉", name: "수박", keywords: "이모지 음식 과일 watermelon"},
	{char: "🍇", name: "포도", keywords: "이모지 음식 과일 grapes"},
	{char: "🍓", name: "딸기", keywords: "이모지 음식 과일 strawberry"},
	{char: "🍑", name: "복숭아", keywords: "이모지 음식 과일 peach"},
	{char: "🍒", name: "체리", keywords: "이모지 음식 과일 cherries"},
	{char: "🥝", name: "키위", keywords: "이모지 음식 과일 kiwi"},
	{char: "🍍", name: "파인애플", keywords: "이모지 음식 과일 pineapple"},
	{char: "🥥", name: "코코넛", keywords: "이모지 음식 과일 coconut"},
	{char: "🥑", name: "아보카도", keywords: "이모지 음식 avocado"},
	{char: "🍅", name: "토마토", keywords: "이모지 음식 tomato"},
	{char: "🍆", name: "가지", keywords: "이모지 음식 eggplant"},
	{char: "🥕", name: "당근", keywords: "이모지 음식 carrot"},
	{char: "🌽", name: "옥수수", keywords: "이모지 음식 corn"},
	{char: "🌶", name: "고추", keywords: "이모지 음식 hot pepper"},
	{char: "🥔", name: "감자", keywords: "이모지 음식 potato"},
	{char: "🍠", name: "고구마", keywords: "이모지 음식 roasted sweet potato"},
	{char: "🧄", name: "마늘", keywords: "이모지 음식 garlic"},
	{char: "🧅", name: "양파", keywords: "이모지 음식 onion"},
	{char: "🥦", name: "브로콜리", keywords: "이모지 음식 broccoli"},
	{char: "🍄", name: "버섯", keywords: "이모지 음식 mushroom"},
	{char: "🥜", name: "땅콩", keywords: "이모지 음식 peanuts"},
	{char: "🌰", name: "밤", keywords: "이모지 음식 chestnut"},
	{char: "🍞", name: "식빵", keywords: "이모지 음식 bread"},
	{char: "🥐", name: "크루아상", keywords: "이모지 음식 croissant"},
	{char: "🥖", name: "바게트", keywords: "이모지 음식 baguette"},
	{char: "🥨", name: "프레첼", keywords: "이모지 음식 pretzel"},
	{char: "🧀", name: "치즈", keywords: "이모지 음식 cheese"},
	{char: "🥚", name: "달걀", keywords: "이모지 음식 egg"},
	{char: "🍳", name: "달걀 프라이", keywords: "이모지 음식 cooking fried egg"},
	{char: "🥞", name: "팬케이크", keywords: "이모지 음식 pancakes"},
	{char: "🥓", name: "베이컨", keywords: "이모지 음식 bacon"},
	{char: "🍔", name: "햄버거", keywords: "이모지 음식 hamburger"},
	{char: "🍟", name: "감자튀김", keywords: "이모지 음식 french fries"},
	{char: "🍕", name: "피자", keywords: "이모지 음식 pizza"},
	{char: "🌭", name: "핫도그", keywords: "이모지 음식 hot dog"},
	{char: "🥪", name: "샌드위치", keywords: "이모지 음식 sandwich"},
	{char: "🌮", name: "타코", keywords: "이모지 음식 taco"},
	{char: "🌯", name: "부리토", keywords: "이모지 음식 burrito"},
	{char: "🥗", name: "샐러드", keywords: "이모지 음식 green salad"},
	{char: "🍝", name: "스파게티", keywords: "이모지 음식 spaghetti"},
	{char: "🍜", name: "라면", keywords: "이모지 음식 steaming bowl ramen"},
	{char: "🍲", name: "전골", keywords: "이모지 음식 pot of food"},
	{char: "🍛", name: "카레", keywords: "이모지 음식 curry rice"},
	{char: "🍚", name: "밥", keywords: "이모지 음식 cooked rice"},
	{char: "🍙", name: "주먹밥", keywords: "이모지 음식 rice ball"},
	{char: "🍘", name: "전병", keywords: "이모지 음식 rice cracker"},
	{char: "🍢", name: "어묵꼬치", keywords: "이모지 음식 oden"},
	{char: "🍡", name: "경단", keywords: "이모지 음식 dango"},
	{char: "🍣", name: "초밥", keywords: "이모지 음식 sushi"},
	{char: "🍤", name: "새우튀김", keywords: "이모지 음식 fried shrimp"},
	{char: "🍥", name: "어묵", keywords: "이모지 음식 fish cake"},
	{char: "🥟", name: "만두", keywords: "이모지 음식 dumpling"},
	{char: "🍦", name: "소프트 아이스크림", keywords: "이모지 음식 soft ice cream"},
	{char: "🍨", name: "아이스크림", keywords: "이모지 음식 ice cream"},
	{char: "🍧", name: "빙수", keywords: "이모지 음식 shaved ice"},
	{char: "🍩", name: "도넛", keywords: "이모지 음식 doughnut"},
	{char: "🍪", name: "쿠키", keywords: "이모지 음식 cookie"},
	{char: "🎂", name: "생일 케이크", keywords: "이모지 음식 birthday cake"},
	{char: "🍰", name: "조각 케이크", keywords: "이모지 음식 shortcake"},
	{char: "🧁", name: "컵케이크", keywords: "이모지 음식 cupcake"},
	{char: "🍫", name: "초콜릿", keywords: "이모지 음식 chocolate bar"},
	{char: "🍬", name: "사탕", keywords: "이모지 음식 candy"},
	{char: "🍭", name: "막대사탕", keywords: "이모지 음식 lollipop"},
	{char: "🍮", name: "푸딩", keywords: "이모지 음식 custard pudding"},
	{char: "🍯", name: "꿀", keywords: "이모지 음식 honey pot"},
	{char: "🥛", name: "우유", keywords: "이모지 음료 glass of milk"},
	{char: "🍵", name: "녹차", keywords: "이모지 음료 teacup"},
	{char: "🍶", name: "사케", keywords: "이모지 음료 sake"},
	{char: "🍺", name: "맥주", keywords: "이모지 음료 beer mug"},
	{char: "🍻", name: "맥주 건배", keywords: "이모지 음료 clinking beer mugs"},
	{char: "🥂", name: "샴페인 건배", keywords: "이모지 음료 clinking glasses"},
	{char: "🍷", name: "와인", keywords: "이모지 음료 wine glass"},
	{char: "🥃", name: "위스키", keywords: "이모지 음료 tumbler glass"},
	{char: "🍸", name: "칵테일", keywords: "이모지 음료 cocktail glass"},
	{char: "🍹", name: "트로피컬 음료", keywords: "이모지 음료 tropical drink"},
	{char: "🍾", name: "샴페인", keywords: "이모지 음료 bottle with popping cork"},
	{char: "🧊", name: "얼음", keywords: "이모지 음료 ice"},
	{char: "🥄", name: "숟가락", keywords: "이모지 식기 spoon"},
	{char: "🍴", name: "포크와 나이프", keywords: "이모지 식기 fork and knife"},
	{char: "🍽", name: "접시와 식기", keywords: "이모지 식기 plate with cutlery"},
	{char: "🥢", name: "젓가락", keywords: "이모지 식기 chopsticks"},

	// 이모지 사물과 활동 (emoji object and activity)
	{char: "💻", name: "노트북", keywords: "이모지 컴퓨터 laptop"},
	{char: "🖥", name: "데스크톱", keywords: "이모지 컴퓨터 desktop computer"},
	{char: "🖨", name: "프린터", keywords: "이모지 printer"},
	{char: "⌨", name: "키보드", keywords: "이모지 keyboard"},
	{char: "🖱", name: "마우스", keywords: "이모지 computer mouse"},
	{char: "💾", name: "플로피 디스크", keywords: "이모지 저장 floppy disk save"},
	{char: "💿", name: "시디", keywords: "이모지 optical disk cd"},
	{char: "📀", name: "디비디", keywords: "이모지 dvd"},
	{char: "💽", name: "미니 디스크", keywords: "이모지 computer disk"},
	{char: "📱", name: "휴대전화", keywords: "이모지 mobile phone"},
	{char: "📲", name: "전화 오는 휴대전화", keywords: "이모지 mobile phone with arrow"},
	{char: "📞", name: "수화기", keywords: "이모지 telephone receiver"},
	{char: "📟", name: "호출기", keywords: "이모지 pager"},
	{char: "📠", name: "팩스", keywords: "이모지 fax machine"},
	{char: "🔋", name: "배터리", keywords: "이모지 battery"},
	{char: "🔌", name: "플러그", keywords: "이모지 electric plug"},
	{char: "🔦", name: "손전등", keywords: "이모지 flashlight"},
	{char: "📷", name: "사진기", keywords: "이모지 camera"},
	{char: "📸", name: "플래시 사진기", keywords: "이모지 camera with flash"},
	{char: "📹", name: "비디오 카메라", keywords: "이모지 video camera"},
	{char: "🎥", name: "영화 카메라", keywords: "이모지 movie camera"},
	{char: "📺", name: "텔레비전", keywords: "이모지 television"},
	{char: "📻", name: "라디오", keywords: "이모지 radio"},
	{char: "🎙", name: "마이크", keywords: "이모지 studio microphone"},
	{char: "🎤", name: "노래 마이크", keywords: "이모지 microphone"},
	{char: "🎧", name: "헤드폰", keywords: "이모지 headphone"},
	{char: "🎵", name: "음표", keywords: "이모지 음악 musical note"},
	{char: "🎶", name: "여러 음표", keywords: "이모지 음악 musical notes"},
	{char: "🎼", name: "악보", keywords: "이모지 음악 musical score"},
	{char: "🎹", name: "건반", keywords: "이모지 음악 musical keyboard piano"},
	{char: "🎸", name: "기타", keywords: "이모지 음악 guitar"},
	{char: "🥁", name: "드럼", keywords: "이모지 음악 drum"},
	{char: "🎺", name: "트럼펫", keywords: "이모지 음악 trumpet"},
	{char: "🎻", name: "바이올린", keywords: "이모지 음악 violin"},
	{char: "📖", name: "펼친 책", keywords: "이모지 책 open book"},
	{char: "📚", name: "책 여러 권", keywords: "이모지 책 books"},
	{char: "📕", name: "닫힌 책", keywords: "이모지 책 closed book"},
	{char: "📓", name: "공책", keywords: "이모지 책 notebook"},
	{char: "📔", name: "장식 공책", keywords: "이모지 책 notebook with cover"},
	{char: "📒", name: "장부", keywords: "이모지 책 ledger"},
	{char: "📃", name: "말린 문서", keywords: "이모지 문서 page with curl"},
	{char: "📄", name: "문서", keywords: "이모지 문서 page facing up"},
	{char: "📑", name: "책갈피 탭", keywords: "이모지 문서 bookmark tabs"},
	{char: "📊", name: "막대 그래프", keywords: "이모지 그래프 bar chart"},
	{char: "📈", name: "오름 그래프", keywords: "이모지 그래프 chart increasing"},
	{char: "📉", name: "내림 그래프", keywords: "이모지 그래프 chart decreasing"},
	{char: "📋", name: "클립보드", keywords: "이모지 clipboard"},
	{char: "📁", name: "폴더", keywords: "이모지 file folder"},
	{char: "📂", name: "열린 폴더", keywords: "이모지 open file folder"},
	{char: "🗂", name: "분류 폴더", keywords: "이모지 card index dividers"},
	{char: "🗃", name: "서류함", keywords: "이모지 card file box"},
	{char: "🗄", name: "캐비닛", keywords: "이모지 file cabinet"},
	{char: "🗑", name: "휴지통", keywords: "이모지 삭제 wastebasket trash"},
	{char: "🖊", name: "볼펜", keywords: "이모지 pen"},
	{char: "🖋", name: "만년필", keywords: "이모지 fountain pen"},
	{char: "🖌", name: "붓", keywords: "이모지 paintbrush"},
	{char: "🖍", name: "크레용", keywords: "이모지 crayon"},
	{char: "📝", name: "메모", keywords: "이모지 memo writing"},
	{char: "📐", name: "삼각자", keywords: "이모지 triangular ruler"},
	{char: "📏", name: "직선자", keywords: "이모지 straight ruler"},
	{char: "🔨", name: "망치", keywords: "이모지 도구 hammer"},
	{char: "🔧", name: "렌치", keywords: "이모지 도구 wrench"},
	{char: "🔩", name: "나사", keywords: "이모지 도구 nut and bolt"},
	{char: "🧰", name: "공구함", keywords: "이모지 도구 toolbox"},
	{char: "🪛", name: "드라이버", keywords: "이모지 도구 screwdriver"},
	{char: "⛏", name: "곡괭이", keywords: "이모지 도구 pick"},
	{char: "🧲", name: "자석", keywords: "이모지 magnet"},
	{char: "🧪", name: "시험관", keywords: "이모지 과학 test tube"},
	{char: "🔬", name: "현미경", keywords: "이모지 과학 microscope"},
	{char: "🔭", name: "망원경", keywords: "이모지 과학 telescope"},
	{char: "💉", name: "주사기", keywords: "이모지 의료 syringe"},
	{char: "💊", name: "알약", keywords: "이모지 의료 pill"},
	{char: "🩹", name: "반창고", keywords: "이모지 의료 adhesive bandage"},
	{char: "🛏", name: "침대", keywords: "이모지 bed"},
	{char: "🚪", name: "문", keywords: "이모지 door"},
	{char: "🪟", name: "창문", keywords: "이모지 window"},
	{char: "🧹", name: "빗자루", keywords: "이모지 broom"},
	{char: "🧺", name: "바구니", keywords: "이모지 basket"},
	{char: "💰", name: "돈주머니", keywords: "이모지 돈 money bag"},
	{char: "💵", name: "달러 지폐", keywords: "이모지 돈 dollar banknote"},
	{char: "💳", name: "신용카드", keywords: "이모지 돈 credit card"},
	{char: "🧾", name: "영수증", keywords: "이모지 돈 receipt"},
	{char: "📦", name: "상자", keywords: "이모지 package box"},
	{char: "📮", name: "우체통", keywords: "이모지 postbox"},
	{char: "📧", name: "이메일", keywords: "이모지 메일 e-mail"},
	{char: "📨", name: "받은 편지", keywords: "이모지 메일 incoming envelope"},
	{char: "📩", name: "보낸 편지", keywords: "이모지 메일 envelope with arrow"},
	{char: "🔐", name: "잠긴 자물쇠와 열쇠", keywords: "이모지 보안 locked with key"},
	{char: "🛡", name: "방패", keywords: "이모지 보안 shield"},
	{char: "⚽", name: "축구공", keywords: "이모지 운동 soccer ball"},
	{char: "🏀", name: "농구공", keywords: "이모지 운동 basketball"},
	{char: "⚾", name: "야구공", keywords: "이모지 운동 baseball"},
	{char: "🎾", name: "테니스공", keywords: "이모지 운동 tennis"},
	{char: "🏐", name: "배구공", keywords: "이모지 운동 volleyball"},
	{char: "🏈", name: "미식축구공", keywords: "이모지 운동 american football"},
	{char: "🎱", name: "당구공", keywords: "이모지 운동 pool 8 ball"},
	{char: "🏓", name: "탁구", keywords: "이모지 운동 ping pong"},
	{char: "🏸", name: "배드민턴", keywords: "이모지 운동 badminton"},
	{char: "🥊", name: "권투 글러브", keywords: "이모지 운동 boxing glove"},
	{char: "🎮", name: "게임 패드", keywords: "이모지 게임 video game"},
	{char: "🕹", name: "조이스틱", keywords: "이모지 게임 joystick"},
	{char: "🎲", name: "주사위", keywords: "이모지 게임 game die"},
	{char: "🧩", name: "퍼즐", keywords: "이모지 게임 puzzle piece"},
	{char: "♟", name: "체스 폰", keywords: "이모지 게임 chess pawn"},
	{char: "🎬", name: "슬레이트", keywords: "이모지 영화 clapper board"},
	{char: "🎭", name: "가면", keywords: "이모지 예술 performing arts"},
	{char: "🎨", name: "팔레트", keywords: "이모지 예술 artist palette"},
	{char: "🚗", name: "자동차", keywords: "이모지 교통 car"},
	{char: "🚕", name: "택시", keywords: "이모지 교통 taxi"},
	{char: "🚌", name: "버스", keywords: "이모지 교통 bus"},
	{char: "🚑", name: "구급차", keywords: "이모지 교통 ambulance"},
	{char: "🚒", name: "소방차", keywords: "이모지 교통 fire engine"},
	{char: "🚲", name: "자전거", keywords: "이모지 교통 bicycle"},
	{char: "🛴", name: "킥보드", keywords: "이모지 교통 kick scooter"},
	{char: "🏍", name: "오토바이", keywords: "이모지 교통 motorcycle"},
	{char: "🚂", name: "기관차", keywords: "이모지 교통 locomotive"},
	{char: "🚆", name: "기차", keywords: "이모지 교통 train"},
	{char: "🚇", name: "지하철", keywords: "이모지 교통 metro"},
	{char: "🚁", name: "헬리콥터", keywords: "이모지 교통 helicopter"},
	{char: "🚢", name: "배", keywords: "이모지 교통 ship"},
	{char: "⛵", name: "돛단배", keywords: "이모지 교통 sailboat"},
	{char: "🚦", name: "신호등", keywords: "이모지 교통 traffic light"},
	{char: "🏠", name: "집", keywords: "이모지 장소 house"},
	{char: "🏢", name: "건물", keywords: "이모지 장소 office building"},
	{char: "🏫", name: "학교", keywords: "이모지 장소 school"},
	{char: "🏥", name: "병원", keywords: "이모지 장소 hospital"},
	{char: "🏦", name: "은행", keywords: "이모지 장소 bank"},
	{char: "🏪", name: "편의점", keywords: "이모지 장소 convenience store"},
	{char: "⛺", name: "텐트", keywords: "이모지 장소 tent"},
	{char: "🗺", name: "지도", keywords: "이모지 장소 world map"},
	{char: "🧭", name: "나침반", keywords: "이모지 장소 compass"},
	{char: "🕐", name: "한 시", keywords: "이모지 시계 one o clock"},
	{char: "📅", name: "달력", keywords: "이모지 날짜 calendar"},
	{char: "📆", name: "찢는 달력", keywords: "이모지 날짜 tear off calendar"},
}
